### ISSUE TITLE
无法运行swift

### ISSUE THREAD

**Issue by JYC-JYC-Users** [modelscope/ms-swift#1107]
**使用swift web-ui时发生错误**
(swift_venv) D:\AI\LLM\SWIFT\swift>swift web-ui
run sh: `python d:\ai\llm\swift\swift\swift\cli\web_ui.py`
Traceback (most recent call last):
  File "d:\ai\llm\swift\swift\swift\cli\web_ui.py", line 2, in <module>
    from swift.ui.app import run_ui
ModuleNotFoundError: No module named 'swift'

**使用文档里的第二种方法装的swift**

**Comment by wuweinero** [comment]
直接执行 python d:\ai\llm\swift\swift\swift\cli\web_ui.py  试试

**Comment by JYC-JYC-Users** [comment]
(swift_venv) D:\AI\LLM\SWIFT\swift\swift\cli>python web_ui.py
2024-06-10 15:05:42,849 - modelscope - INFO - PyTorch version 2.3.1+cu121 Found.
2024-06-10 15:05:42,853 - modelscope - INFO - Loading ast index from C:\Users\JYC\.cache\modelscope\ast_indexer
2024-06-10 15:05:43,155 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 23e3242406c50ae3699433273a08497f and a total number of 980 components indexed
[INFO:swift] Successfully registered `d:\ai\llm\swift\swift\swift\llm\data\dataset_info.json`
Running on local URL:  http://127.0.0.1:7860
Traceback (most recent call last):
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpcore\_sync\http_proxy.py", line 207, in handle_request
    return self._connection.handle_request(proxy_request)
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpcore\_sync\connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpcore\_backends\sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "c:\program files\python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AI\LLM\SWIFT\swift\swift\cli\web_ui.py", line 5, in <module>
    run_ui()
  File "d:\ai\llm\swift\swift\swift\ui\app.py", line 72, in run_ui
    app.queue(**concurrent).launch(
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\gradio\blocks.py", line 2358, in launch
    httpx.get(
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpx\_api.py", line 198, in get
    return request(
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpx\_api.py", line 106, in request
    return client.request(
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpx\_transports\default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "c:\program files\python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\AI\LLM\SWIFT\swift_venv\lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**这回报这个错**

**Comment by cyj95** [comment]
同问，我也有连接的问题

[INFO:swift] Successfully registered `/data/cuiyajie/swift-main/swift/llm/data/dataset_info.json`
Running on local URL:  http://127.0.0.1:7860
Traceback (most recent call last):
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_r                                                                                                                                                                     equest
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_r                                                                                                                                                                     equest
    httplib_response = conn.getresponse()
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.167.32.133', port=8080): Max retries exceeded with url: htt                                                                                                                                                                     p://127.0.0.1:7860/startup-events (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed                                                                                                                                                                      connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/cuiyajie/swift-main/swift/cli/web_ui.py", line 5, in <module>
    run_ui()
  File "/data/cuiyajie/swift-main/swift/ui/app.py", line 64, in run_ui
    app.queue(**concurrent).launch(
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/gradio/blocks.py", line 2075, in launch
    requests.get(f"{self.local_url}startup-events", verify=ssl_verify)
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/data/cuiyajie/anaconda3/envs/swift/lib/python3.10/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='10.167.32.133', port=8080): Max retries exceeded with url: http:                                                                                                                                                                     //127.0.0.1:7860/startup-events (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed c                                                                                                                                                                     onnection without response')))

**Comment by tastelikefeet** [comment]
一般这个问题都是多虚拟环境导致的，看下python环境是不是有多套
下面的连接问题一般是端口被占用等问题，可以尝试重新运行下，一般都会好
