### ISSUE TITLE
Internvl-chat-v1.5使用多卡推理报错

### ISSUE THREAD

**Issue by rookie-J** [modelscope/ms-swift#1228]
使用单卡到4卡推理都没问题，超过4张卡就会报错：

<<< 你好
Input a media path or URL <<<
Exception in thread Thread-2 (generate):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/data/swift/swift/llm/utils/model.py", line 3341, in _new_generate
    return generate(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-Chat-V1-5/modeling_internvl_chat.py", line 348, in generate
    outputs = self.language_model.generate(
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1592, in generate
    return self.sample(
  File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2740, in sample
    next_tokens = next_tokens * unfinished_sequences + pad_token_id * (1 - unfinished_sequences)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

模型与代码均使用HF和github未改动，这个会是什么问题呢？

**Comment by hjh0119** [comment]
我们对2/4卡做了适配和测试, 更多比如八卡可能是有问题的
