### ISSUE TITLE
Finetuning LLaVA Mistral, gets error when working on multiple GPUs: ValueError: Expected input batch_size (1063) to match target batch_size (2215).

### ISSUE THREAD

**Issue by HimanshuBaurai** [modelscope/ms-swift#1399]
conda activate swift
CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft     --model_type llava1_6-mistral-7b-instruct     --dataset dataset/abc.jsonl \

Command that i am using, dont know whats wrong in it

Following is the traceback:
Traceback (most recent call last):
  File "/sensei-fs/users/abedi/reco/hbaurai/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/sensei-fs/users/abedi/reco/hbaurai/swift/swift/utils/run_utils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
  File "/sensei-fs/users/abedi/reco/hbaurai/swift/swift/llm/sft.py", line 317, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/sensei-fs/users/abedi/reco/hbaurai/swift/swift/trainers/mixin.py", line 518, in train
    res = super().train(resume_from_checkpoint, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 1932, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 2268, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 3307, in training_step
    loss = self.compute_loss(model, inputs)
  File "/sensei-fs/users/abedi/reco/hbaurai/swift/swift/trainers/trainers.py", line 183, in compute_loss
    outputs = model(**inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/operations.py", line 822, in forward
    return model_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/operations.py", line 810, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/opt/conda/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/peft/peft_model.py", line 1430, in forward
    return self.base_model(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/peft/tuners/tuners_utils.py", line 179, in forward
    return self.model.forward(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 880, in forward
    loss = loss_fct(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1185, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 3086, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
ValueError: Expected input batch_size (1063) to match target batch_size (2215).
Train:   0%|                                                                     

Highly appreciate any help.
Thanks in advance.

**Comment by Jintao-Huang** [comment]
我这里没有报错
swift main分支
transformers==4.42.*

**Comment by HimanshuBaurai** [comment]
> I don't have any errors here.
> 
> ms-swift main branch
> transformers==4.42.*

First of all thank you for the response.
I have transformers 4.42.4
Still this issue persists.
Is there any probable file that may have problem, or everything is correct regarding this, all i have to ensure is to be on correct dependencies or try around that only?

**Comment by Jintao-Huang** [comment]
测试一下这个是否正常：

```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
from swift.llm import sft_main, SftArguments

sft_main(SftArguments(model_type='llava1_6-mistral-7b-instruct', dataset='coco-en-2-mini'))

```

**Comment by HimanshuBaurai** [comment]
> Test if this works:
> 
> ```
> import os
> os.environ['CUDA_VISIBLE_DEVICES'] = '0'
> from swift.llm import sft_main, SftArguments
> 
> sft_main(SftArguments(model_type='llava1_6-mistral-7b-instruct', dataset='coco-en-2-mini'))
> ```

Yes for single GPU it was working fine, only issue in that case was GPU Out of memory, as i had 24GB VRAM only.

I am getting that batch_size issue, only when i am using it on multiple GPUs
like CUDA_VISIBLE_DEVICES=0,1,2,3

**Comment by Jintao-Huang** [comment]
Hello, could you pull the latest main branch and run the experiment again?

**Comment by Jintao-Huang** [comment]
I suspect the code is outdated

**Comment by HimanshuBaurai** [comment]
i am using this command
CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft     --model_type llava1_6-mistral-7b-instruct     --dataset dataset/annotations.jsonl \ 

getting this error now
```
  File "/hbaurai/swift/swift/llm/sft.py", line 178, in llm_sft
    train_dataset, val_dataset = get_dataset(
                                 ^^^^^^^^^^^^
  File "/hbaurai/swift/swift/llm/utils/dataset.py", line 2390, in get_dataset
    dataset_info = DATASET_MAPPING[dataset_name]
                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '_1 _1'
```

normally those datasets which are mentioned would work, but now
using the following command
```
CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
    --model_type llava1_6-mistral-7b-instruct \
    --dataset coco-en-2-mini \ 
    ```
    its not even recognizing coco dataset, which is mentioned in the file
    showing similar error of dataset mapping

**Comment by Jintao-Huang** [comment]
`NPROC_PER_NODE=2 CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft --model_type llava1_6-mistral-7b-instruct --dataset dataset/annotations.jsonl`

Try again. The issue with KeyError: '_1 _1' is due to commented lines in the .sh file.

**Comment by HimanshuBaurai** [comment]
> `NPROC_PER_NODE=2 CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft --model_type llava1_6-mistral-7b-instruct --dataset dataset/annotations.jsonl`
> 
> Try again. The issue with KeyError: '_1 _1' is due to commented lines in the .sh file.

Yes i tried this, but now encountering this error, though i have 4 GPUs sufficient memory
```
Traceback (most recent call last):
  File "/opt/conda/envs/swift2/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/swift2/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/swift2/lib/python3.12/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/opt/conda/envs/swift2/lib/python3.12/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/opt/conda/envs/swift2/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/swift2/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

Can torch version dependy may be the issue, although installed all dependencies via mentioned pip '[llm]' only
