### ISSUE TITLE
微调后模型进行量化出现错误

### ISSUE THREAD

**Issue by badmic** [modelscope/ms-swift#1533]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

导出脚本：
CUDA_VISIBLE_DEVICES=0  swift export     --ckpt_dir '/data/project/ys/swift/output_2/llama3_1-405b-instruct/v17-20240729-124233/checkpoint-2500'     --merge_lora true --quant_bits 4     --load_dataset_config true --quant_method awq

报错：
(swift_cu) root@m1:/data/project/ys/swift# CUDA_VISIBLE_DEVICES=0  swift export     --ckpt_dir '/data/project/ys/swift/output_2/llama3_1-405b-instruct/v17-20240729-124233/checkpoint-2500'     --merge_lora true --quant_bits 4     --load_dataset_config true --quant_method awq
run sh: `python /data/project/ys/swift/swift/cli/export.py --ckpt_dir /data/project/ys/swift/output_2/llama3_1-405b-instruct/v17-20240729-124233/checkpoint-2500 --merge_lora true --quant_bits 4 --load_dataset_config true --quant_method awq`
[INFO:swift] Successfully registered `/data/project/ys/swift/swift/llm/data/dataset_info.json`
[INFO:swift] Start time of running main: 2024-07-30 11:30:28.690430
[INFO:swift] Setting args.dtype: fp16
[INFO:swift] ckpt_dir: /data/project/ys/swift/output_2/llama3_1-405b-instruct/v17-20240729-124233/checkpoint-2500
[INFO:swift] Setting model_info['revision']: master
[INFO:swift] Setting self.eval_human: False
[INFO:swift] Setting overwrite_generation_config: True
[INFO:swift] Setting args.quant_output_dir: /data/project/ys/swift/output_2/llama3_1-405b-instruct/v17-20240729-124233/checkpoint-2500-awq-int4
[INFO:swift] args: ExportArguments(model_type='llama3_1-405b-instruct', model_id_or_path='/data/models/Meta-Llama-3.1-405B-Instruct', model_revision='master', sft_type='lora', template_type='llama3', infer_backend='vllm', ckpt_dir='/data/project/ys/swift/output_2/llama3_1-405b-instruct/v17-20240729-124233/checkpoint-2500', load_args_from_ckpt_dir=True, load_dataset_config=True, eval_human=False, seed=42, dtype='fp16', dataset=['/data/project/ys/data/QA-chinese/output_subset.jsonl'], val_dataset=[], dataset_seed=42, dataset_test_ratio=0.01, show_dataset_sample=10, save_result=True, system=None, tools_prompt='react_en', max_length=None, truncation_strategy='delete', check_dataset_strategy='none', model_name=[None, None], model_author=[None, None], quant_method='awq', quantization_bit=0, hqq_axis=0, hqq_dynamic_config_path=None, bnb_4bit_comp_dtype='bf16', bnb_4bit_quant_type='nf4', bnb_4bit_use_double_quant=True, bnb_4bit_quant_storage=None, max_new_tokens=2048, do_sample=True, temperature=0.3, top_k=20, top_p=0.7, repetition_penalty=1.0, num_beams=1, stop_words=[], rope_scaling=None, use_flash_attn=None, ignore_args_error=False, stream=True, merge_lora=True, merge_device_map='cpu', save_safetensors=True, overwrite_generation_config=True, verbose=None, local_repo_path=None, custom_register_path=None, custom_dataset_info=None, device_map_config_path=None, device_max_memory=[], hub_token=None, gpu_memory_utilization=0.9, tensor_parallel_size=1, max_model_len=None, disable_custom_all_reduce=True, enforce_eager=False, vllm_enable_lora=False, vllm_max_lora_rank=16, lora_modules=[], image_input_shape=None, image_feature_size=None, self_cognition_sample=0, train_dataset_sample=-1, val_dataset_sample=None, safe_serialization=None, model_cache_dir=None, merge_lora_and_save=None, custom_train_dataset_path=[], custom_val_dataset_path=[], vllm_lora_modules=None, to_peft_format=False, to_ollama=False, ollama_output_dir=None, gguf_file=None, quant_bits=4, quant_n_samples=256, quant_seqlen=2048, quant_device_map='cpu', quant_output_dir='/data/project/ys/swift/output_2/llama3_1-405b-instruct/v17-20240729-124233/checkpoint-2500-awq-int4', push_to_hub=False, hub_model_id=None, hub_private_repo=False, commit_message='update files', to_megatron=False, to_hf=False, megatron_output_dir=None, hf_output_dir=None, tp=1, pp=1, check_model_forward=False)
[INFO:swift] Global seed set to 42
[INFO:swift] replace_if_exists: False
[INFO:swift] merged_lora_path: `/data/project/ys/swift/output_2/llama3_1-405b-instruct/v17-20240729-124233/checkpoint-2500-merged`
[INFO:swift] merge_device_map: cpu
[INFO:swift] device_count: 1
[INFO:swift] Loading the model using model_dir: /data/models/Meta-Llama-3.1-405B-Instruct
[INFO:swift] model_kwargs: {'device_map': 'cpu'}
Traceback (most recent call last):
  File "/data/project/ys/swift/swift/cli/export.py", line 5, in <module>
    export_main()
  File "/data/project/ys/swift/swift/utils/run_utils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
  File "/data/project/ys/swift/swift/llm/export.py", line 127, in llm_export
    merge_lora(args, device_map=args.merge_device_map)
  File "/data/project/ys/swift/swift/llm/infer.py", line 112, in merge_lora
    model, template = prepare_model_template(args, device_map=device_map, verbose=False)
  File "/data/project/ys/swift/swift/llm/infer.py", line 184, in prepare_model_template
    model, tokenizer = get_model_tokenizer(
  File "/data/project/ys/swift/swift/llm/utils/model.py", line 5897, in get_model_tokenizer
    model, tokenizer = get_function(model_dir, torch_dtype, model_kwargs, load_model, **kwargs)
  File "/data/project/ys/swift/swift/llm/utils/model.py", line 4546, in get_model_tokenizer_llama2
    return get_model_tokenizer_with_flash_attn(
  File "/data/project/ys/swift/swift/llm/utils/model.py", line 2466, in get_model_tokenizer_with_flash_attn
    return get_model_tokenizer_from_repo(
  File "/data/project/ys/swift/swift/llm/utils/model.py", line 974, in get_model_tokenizer_from_repo
    model = automodel_class.from_pretrained(
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/modelscope/utils/hf_util.py", line 113, in from_pretrained
    module_obj = module_class.from_pretrained(model_dir, *model_args,
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/modelscope/utils/hf_util.py", line 76, in from_pretrained
    return ori_from_pretrained(cls, model_dir, *model_args, **kwargs)
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3775, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1066, in __init__
    self.model = LlamaModel(config)
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 845, in __init__
    [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 845, in <listcomp>
    [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 632, in __init__
    self.self_attn = LLAMA_ATTENTION_CLASSES[config._attn_implementation](config=config, layer_idx=layer_idx)
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 306, in __init__
    self.rotary_emb = LlamaRotaryEmbedding(config=self.config)
  File "/root/miniconda3/envs/swift_cu/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 110, in __init__
    self.rope_type = config.rope_scaling.get("rope_type", config.rope_scaling["type"])
KeyError: 'type'

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by badmic** [comment]
目前出现报错：
(swift) (miniconda3) root@A800-node33:/data/project/ys/swift# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 swift infer \
    --model_type llama3_1-405b-instruct \
    --model_id_or_path /data/models/ys/cp-merged \
    --quant_method hqq \
    --quantization_bit 4
run sh: `python /data/project/ys/swift/swift/cli/infer.py --model_type llama3_1-405b-instruct --model_id_or_path /data/models/ys/cp-merged --quant_method hqq --quantization_bit 4`
[INFO:swift] Successfully registered `/data/project/ys/swift/swift/llm/data/dataset_info.json`
[INFO:swift] Start time of running main: 2024-07-30 13:16:48.618980
[INFO:swift] ckpt_dir: None
[INFO:swift] Due to `ckpt_dir` being `None`, `load_args_from_ckpt_dir` is set to `False`.
[INFO:swift] Setting template_type: llama3
[INFO:swift] Setting self.eval_human: True
[INFO:swift] Setting overwrite_generation_config: False
[INFO:swift] args: InferArguments(model_type='llama3_1-405b-instruct', model_id_or_path='/data/models/ys/cp-merged', model_revision='master', sft_type='full', template_type='llama3', infer_backend='pt', ckpt_dir=None, load_args_from_ckpt_dir=False, load_dataset_config=False, eval_human=True, seed=42, dtype='AUTO', dataset=[], val_dataset=[], dataset_seed=42, dataset_test_ratio=0.01, show_dataset_sample=10, save_result=True, system=None, tools_prompt='react_en', max_length=None, truncation_strategy='delete', check_dataset_strategy='none', model_name=[None, None], model_author=[None, None], quant_method='hqq', quantization_bit=4, hqq_axis=0, hqq_dynamic_config_path=None, bnb_4bit_comp_dtype='AUTO', bnb_4bit_quant_type='nf4', bnb_4bit_use_double_quant=True, bnb_4bit_quant_storage=None, max_new_tokens=2048, do_sample=True, temperature=0.3, top_k=20, top_p=0.7, repetition_penalty=1.0, num_beams=1, stop_words=[], rope_scaling=None, use_flash_attn=None, ignore_args_error=False, stream=True, merge_lora=False, merge_device_map='cpu', save_safetensors=True, overwrite_generation_config=False, verbose=None, local_repo_path=None, custom_register_path=None, custom_dataset_info=None, device_map_config_path=None, device_max_memory=[], hub_token=None, gpu_memory_utilization=0.9, tensor_parallel_size=1, max_model_len=None, disable_custom_all_reduce=True, enforce_eager=False, vllm_enable_lora=False, vllm_max_lora_rank=16, lora_modules=[], image_input_shape=None, image_feature_size=None, self_cognition_sample=0, train_dataset_sample=-1, val_dataset_sample=None, safe_serialization=None, model_cache_dir=None, merge_lora_and_save=None, custom_train_dataset_path=[], custom_val_dataset_path=[], vllm_lora_modules=None)
[INFO:swift] Global seed set to 42
[INFO:swift] device_count: 8
[INFO:swift] Loading the model using model_dir: /data/models/ys/cp-merged
[INFO:swift] Setting torch_dtype: torch.bfloat16
[INFO:swift] model_kwargs: {'low_cpu_mem_usage': True, 'device_map': 'auto', 'quantization_config': HqqConfig {
  "offload_meta": false,
  "scale_quant_params": null,
  "weight_quant_params": {
    "axis": 0,
    "channel_wise": true,
    "group_size": 64,
    "nbits": 4,
    "optimize": true,
    "round_zero": true,
    "view_as_float": false
  },
  "zero_quant_params": {
    "channel_wise": false,
    "group_size": null,
    "nbits": 8,
    "optimize": false
  }
}
}
Traceback (most recent call last):
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1586, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/root/miniconda3/envs/swift/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 32, in <module>
    from ...modeling_flash_attention_utils import _flash_attention_forward
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/modeling_flash_attention_utils.py", line 27, in <module>
    from flash_attn.bert_padding import index_first_axis, pad_input, unpad_input  # noqa
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/flash_attn-2.5.5-py3.10-linux-x86_64.egg/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/flash_attn-2.5.5-py3.10-linux-x86_64.egg/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /root/miniconda3/envs/swift/lib/python3.10/site-packages/flash_attn-2.5.5-py3.10-linux-x86_64.egg/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/project/ys/swift/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "/data/project/ys/swift/swift/utils/run_utils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
  File "/data/project/ys/swift/swift/llm/infer.py", line 297, in llm_infer
    model, template = prepare_model_template(args, device_map=device_map)
  File "/data/project/ys/swift/swift/llm/infer.py", line 184, in prepare_model_template
    model, tokenizer = get_model_tokenizer(
  File "/data/project/ys/swift/swift/llm/utils/model.py", line 5897, in get_model_tokenizer
    model, tokenizer = get_function(model_dir, torch_dtype, model_kwargs, load_model, **kwargs)
  File "/data/project/ys/swift/swift/llm/utils/model.py", line 4546, in get_model_tokenizer_llama2
    return get_model_tokenizer_with_flash_attn(
  File "/data/project/ys/swift/swift/llm/utils/model.py", line 2466, in get_model_tokenizer_with_flash_attn
    return get_model_tokenizer_from_repo(
  File "/data/project/ys/swift/swift/llm/utils/model.py", line 974, in get_model_tokenizer_from_repo
    model = automodel_class.from_pretrained(
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/modelscope/utils/hf_util.py", line 113, in from_pretrained
    module_obj = module_class.from_pretrained(model_dir, *model_args,
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 384, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 735, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 749, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 693, in getattribute_from_module
    if hasattr(module, attr):
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1576, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1588, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
/root/miniconda3/envs/swift/lib/python3.10/site-packages/flash_attn-2.5.5-py3.10-linux-x86_64.egg/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

**Comment by tastelikefeet** [comment]
不复现啊，考虑升级下transformers版本？
