### ISSUE TITLE
glm-v4微调报错，RuntimeError: The size of tensor a (1724) must match the size of tensor b (125) at non-singleton dimension 2

### ISSUE THREAD

**Issue by 66246764** [modelscope/ms-swift#1628]
您好，我按照你提供的数据形式组织了多模态大模型glm-4v-9b的数据，query+answer+image_path，前面一直都能跑通，直到训练到最后100%的时候报错。想请教一下这是哪里我搞错了吗：
{'loss': 2.53007813, 'grad_norm': 4.19035435, 'learning_rate': 3.46e-06, 'memory(GiB)': 64.15, 'train_speed(iter/s)': 0.09224, 'epoch': 0.89, 'global_step/max_steps': '40/45', 'percentage': '88.89%', 'elapsed_time': '7m 13s', 'remaining_time': '54s'}
{'loss': 2.59472656, 'grad_norm': 3.19378972, 'learning_rate': 0.0, 'memory(GiB)': 64.15, 'train_speed(iter/s)': 0.092565, 'epoch': 1.0, 'global_step/max_steps': '45/45', 'percentage': '100.00%', 'elapsed_time': '8m 5s', 'remaining_time': '0s'}
Train: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 45/45 [08:05<00:00, 10.48s/it]Traceback (most recent call last):
  File "/mnt/pfs/jinfeng_team/APP/chenxuanyu/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/mnt/pfs/jinfeng_team/APP/chenxuanyu/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/chenxuanyu/swift/swift/llm/sft.py", line 394, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/mnt/pfs/jinfeng_team/APP/chenxuanyu/swift/swift/trainers/mixin.py", line 538, in train
    res = super().train(resume_from_checkpoint, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/transformers/trainer.py", line 2356, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
  File "/mnt/pfs/jinfeng_team/APP/chenxuanyu/swift/swift/trainers/mixin.py", line 612, in _maybe_log_save_evaluate
    super()._maybe_log_save_evaluate(tr_loss, *args, **kwargs)
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/transformers/trainer.py", line 2804, in _maybe_log_save_evaluate
    metrics = self._evaluate(trial, ignore_keys_for_eval)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/transformers/trainer.py", line 2761, in _evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/transformers/trainer_seq2seq.py", line 180, in evaluate
    return super().evaluate(eval_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/transformers/trainer.py", line 3666, in evaluate
    output = eval_loop(
             ^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/transformers/trainer.py", line 3857, in evaluation_loop
    losses, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/chenxuanyu/swift/swift/trainers/trainers.py", line 54, in prediction_step
    return super().prediction_step(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/transformers/trainer_seq2seq.py", line 278, in prediction_step
    return super().prediction_step(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/transformers/trainer.py", line 4075, in prediction_step
    loss, outputs = self.compute_loss(model, inputs, return_outputs=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/chenxuanyu/swift/swift/trainers/trainers.py", line 179, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/accelerate/utils/operations.py", line 819, in forward
    return model_forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^

**Comment by 66246764** [comment]
不好意思没截全。错误为：RuntimeError: The size of tensor a (1724) must match the size of tensor b (125) at non-singleton dimension 2

File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/accelerate/utils/operations.py", line 819, in forward
    return model_forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/accelerate/utils/operations.py", line 807, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 43, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/peft/peft_model.py", line 1577, in forward
    return self.base_model(
           ^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 188, in forward
    return self.model.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 1179, in forward
    transformer_outputs = self.transformer(
                          ^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs/jinfeng_team/APP/kangningfei/miniconda/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 1035, in forward
    full_attention_mask = self.get_masks(inputs_embeds, past_key_values, padding_mask=attention_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 835, in get_masks
    full_attention_mask = full_attention_mask * padding_mask.unsqueeze(1)
                          ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (1724) must match the size of tensor b (125) at non-singleton dimension 2
Train: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 45/45 [08:04<00:00, 10.76s/it]

**Comment by 66246764** [comment]
只有把batch_size设为1才能正常跑通，这是为什么呢
