### ISSUE TITLE
部署后只能通过ip+端口访问，通过域名访问报错

### ISSUE THREAD

**Issue by 1SingleFeng** [modelscope/ms-swift#1642]
部署internvl2之后，参考这里的访问方式 https://github.com/modelscope/ms-swift/blob/main/docs/source/Multi-Modal/MLLM%E9%83%A8%E7%BD%B2%E6%96%87%E6%A1%A3.md#minicpm-v-v2_5-chat 当我通过ip+端口访问时，能够正常返回结果，但是通过域名访问时，会报如下错误
Traceback (most recent call last):
  File "use_openai_1_internvl2_26b.py", line 15, in <module>
    model_type = client.models.list().data[0].id
  File "/opt/conda/lib/python3.10/site-packages/openai/resources/models.py", line 80, in list
    return self._get_api_list(
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1315, in get_api_list
    return self._request_api_list(model, page, opts)
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1160, in _request_api_list
    return self.request(page, options, stream=False)
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 942, in request
    return self._request(
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1046, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: path location is not configured

**Comment by tastelikefeet** [comment]
这个源于host和ip对不上，不知道你的域名是否有DNS注册
这个还是需要你从网络层面解决的
