### ISSUE TITLE
执行swift web-ui报错

### ISSUE THREAD

**Issue by pxrgod** [modelscope/ms-swift#1686]
报错内容如下:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\python3.12\Scripts\swift.exe\__main__.py", line 4, in <module>
  File "D:\python3.12\Lib\site-packages\swift\__init__.py", line 4, in <module>
    from .utils.import_utils import _LazyModule
  File "D:\python3.12\Lib\site-packages\swift\utils\__init__.py", line 3, in <module>
    from .hub import create_ms_repo, push_to_ms_hub
  File "D:\python3.12\Lib\site-packages\swift\utils\hub.py", line 10, in <module>
    from swift.hub import HubApi, ModelScopeConfig
  File "D:\python3.12\Lib\site-packages\swift\hub\__init__.py", line 3, in <module>
    from .api import HubApi, ModelScopeConfig
  File "D:\python3.12\Lib\site-packages\swift\hub\api.py", line 24, in <module>
    from swift.utils.logger import get_logger
  File "D:\python3.12\Lib\site-packages\swift\utils\logger.py", line 7, in <module>
    from modelscope.utils.logger import get_logger as get_ms_logger
  File "D:\python3.12\Lib\site-packages\modelscope\__init__.py", line 4, in <module>
    from modelscope.utils.import_utils import (LazyImportModule,
  File "D:\python3.12\Lib\site-packages\modelscope\utils\import_utils.py", line 17, in <module>
    from modelscope.utils.ast_utils import (INDEX_KEY, MODULE_KEY, REQUIREMENT_KEY,
  File "D:\python3.12\Lib\site-packages\modelscope\utils\ast_utils.py", line 24, in <module>
    from modelscope.utils.registry import default_group
  File "D:\python3.12\Lib\site-packages\modelscope\utils\registry.py", line 11, in <module>
    logger = get_logger()
             ^^^^^^^^^^^^
  File "D:\python3.12\Lib\site-packages\modelscope\utils\logger.py", line 45, in get_logger
    from modelscope.utils.torch_utils import is_dist, is_master
  File "D:\python3.12\Lib\site-packages\modelscope\utils\torch_utils.py", line 13, in <module>
    import torch
  File "D:\python3.12\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\python3.12\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
看这个错误是说 get_logger这个方法不存在，但是我看了下这个文件，是存在的

**Comment by tastelikefeet** [comment]
torch版本不对，这个是windows独有的错误
重新安装torch可以解决
