### ISSUE TITLE
运行swift-webui出错

### ISSUE THREAD

**Issue by Distant10** [modelscope/ms-swift#1687]
按照第二种安装方法安装，执行swift-webui报错，报错报告如下：
Traceback (most recent call last):
  File "/data/swift/swift/cli/web_ui.py", line 5, in <module>
    webui_main()
  File "/data/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/data/swift/swift/ui/app.py", line 71, in run_ui
    LLMInfer.build_ui(LLMInfer)
  File "/data/swift/swift/ui/base.py", line 100, in build_ui
    cls.do_build_ui(base_tab)
  File "/data/swift/swift/ui/llm_infer/llm_infer.py", line 144, in do_build_ui
    video = gr.Video(type='filepath')
  File "/data/swift/swift/ui/base.py", line 54, in wrapper
    ret = fn(self, **kwargs)
  File "/usr/local/anaconda3/envs/swift/lib/python3.10/site-packages/gradio/component_meta.py", line 165, in wrapper
    return fn(self, **kwargs)
TypeError: Video.__init__() got an unexpected keyword argument 'type'

**Comment by xzw1008** [comment]
pycharm运行报错处点File "/data/swift/swift/ui/llm_infer/llm_infer.py", line 144, in do_build_ui转到llm_infer.py代码，
删掉video = gr.Video(type='filepath')这行括号里的type='filepath'可以运行成功，就是不知道会不会有什么别的影响
![1723532894062](https://github.com/user-attachments/assets/1bdaf8ba-1ddc-4c85-a12f-79cd9c7d8684)

**Comment by tastelikefeet** [comment]
已修复了，用最新代码试试
