### ISSUE TITLE
请问qwen2Audio支持实时语音输入吗

### ISSUE THREAD

**Issue by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [modelscope/ms-swift#1693]

**Comment by tastelikefeet** [comment]
在部署之后，推理的时候可以输入audio信息，自己对实时语音进行分片输入即可：
https://swift.readthedocs.io/zh-cn/latest/Multi-Modal/qwen-audio%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.html

**Comment by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [comment]
可是我把捕获的麦克风音频流 作为audios 中内容,执行会报错啊
            data = np.concatenate(chunks)
            query = '<audio>这段语音说了什么'
            audios = [data]
            response, history = inference_stream(model, template, query, audios=audios)
报错信息如下
Traceback (most recent call last):
  File "D:\liu\FunASR-main\Qwen2实时ASRtest.py", line 102, in <module>
    recognize(1)
  File "D:\liu\FunASR-main\Qwen2实时ASRtest.py", line 94, in recognize
    response, history = inference_stream(model, template, query, audios=audios)
  File "D:\liu\anaconda3\envs\env_name\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "D:\liu\anaconda3\envs\env_name\lib\site-packages\swift\llm\utils\utils.py", line 655, in inference_stream
    inputs, tokenizer_kwargs, token_len, example = _prepare_inputs(
  File "D:\liu\anaconda3\envs\env_name\lib\site-packages\swift\llm\utils\utils.py", line 576, in _prepare_inputs
    inputs, tokenizer_kwargs = template.encode(example)
  File "D:\liu\anaconda3\envs\env_name\lib\site-packages\swift\llm\utils\template.py", line 440, in encode
    example = self.preprocess(example)
  File "D:\liu\anaconda3\envs\env_name\lib\site-packages\swift\llm\utils\template.py", line 436, in preprocess
    self._preprocess_media(example)
  File "D:\liu\anaconda3\envs\env_name\lib\site-packages\swift\llm\utils\template.py", line 360, in _preprocess_media
    self.add_default_tags(example)
  File "D:\liu\anaconda3\envs\env_name\lib\site-packages\swift\llm\utils\template.py", line 319, in add_default_tags
    example[media_key] = [m for m in example[media_key] if m]
  File "D:\liu\anaconda3\envs\env_name\lib\site-packages\swift\llm\utils\template.py", line 319, in <listcomp>
    example[media_key] = [m for m in example[media_key] if m]
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by tastelikefeet** [comment]
不能直接用流式输入的，先分片转为mp3等格式，然后输入

**Comment by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [comment]
了解,感谢
