### ISSUE TITLE
加载自定义数据集之后，就报错:AssertionError

### ISSUE THREAD

**Issue by ArlanCooper** [modelscope/ms-swift#1705]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

运行命令：
```
# Experimental environment: 3090, A10, V100
# 20GB GPU memory

CUDA_VISIBLE_DEVICES=1 \
swift sft \
    --model_type llama3-8b-instruct \
    --model_id_or_path /data/share/rwq/Llama3-8B-Chinese-Chat \
    --model_revision master \
    --sft_type lora \
    --tuner_backend peft \
    --template_type AUTO \
    --dtype AUTO \
    --output_dir output_info \
    --dataset blossom-math-zh \
    --train_dataset_sample -1 \
    --num_train_epochs 6 \
    --max_length 3600 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules ALL \
    --gradient_checkpointing true \
    --batch_size 2 \
    --weight_decay 0.1 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --dataset /home/powerop/work/rwq/hangbian/extract_info/new_label_process/data/swift_train_hb_more_cols_0814.jsonl \
    --val_dataset /home/powerop/work/rwq/hangbian/extract_info/new_label_process/data/swift_eval_hb_more_cols_0814.jsonl



```

升级前是没有问题的，按照官方升级之后，运行上述脚本，报如下错误：

报错信息：
```
100%|██████████| 2350/2350 [00:00<00:00, 8510.43it/s]
Traceback (most recent call last):
  File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/swift/utils/run_utils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
  File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/swift/llm/sft.py", line 171, in llm_sft
    train_dataset, val_dataset = get_dataset(
  File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/swift/llm/utils/dataset.py", line 2407, in get_dataset
    train_dataset = _check_dataset(train_dataset, check_dataset_strategy)
  File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/swift/llm/utils/dataset.py", line 2183, in _check_dataset
    assert len(dataset) > 0
AssertionError

```
数据集加载完了，为什么会报这个错误呢？

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
cuda 12.1
system ubuntu 16.4
torch 2.1.2+cu118

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by ArlanCooper** [comment]
已解决，训练数据格式问题，按照要求构建成数据集格式即可

**Comment by 307yin** [comment]
> 已解决，训练数据格式问题，按照要求构建成数据集格式即可

你好 我这也是这个问题 请问是怎么解决的呢 显示无法找到我的数据.....
