### ISSUE TITLE
args.preprocess_num_proc设置为8报错 

### ISSUE THREAD

**Issue by Browallia** [modelscope/ms-swift#1718]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
v100*8  cu122 torch2.4 

**Additional context**

报错
/home/tiger/.local/lib/python3.9/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.9/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/home/tiger/.local/lib/python3.9/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tiger/.local/lib/python3.9/site-packages/multiprocess/pool.py", line 114, in worker
    task = get()
  File "/home/tiger/.local/lib/python3.9/site-packages/multiprocess/queues.py", line 370, in get
    return _ForkingPickler.loads(res)
  File "/home/tiger/.local/lib/python3.9/site-packages/dill/_dill.py", line 303, in loads
    return load(file, ignore, **kwds)
  File "/home/tiger/.local/lib/python3.9/site-packages/dill/_dill.py", line 289, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/tiger/.local/lib/python3.9/site-packages/dill/_dill.py", line 444, in load
    obj = StockUnpickler.load(self)
  File "/home/tiger/.local/lib/python3.9/site-packages/torch/storage.py", line 414, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/home/tiger/.local/lib/python3.9/site-packages/torch/serialization.py", line 1114, in load
    return _legacy_load(
  File "/home/tiger/.local/lib/python3.9/site-packages/torch/serialization.py", line 1348, in _legacy_load
    result = unpickler.load()
  File "/home/tiger/.local/lib/python3.9/site-packages/torch/serialization.py", line 1281, in persistent_load
    obj = restore_location(obj, location)
  File "/home/tiger/.local/lib/python3.9/site-packages/torch/serialization.py", line 414, in default_restore_location
    result = fn(storage, location)
  File "/home/tiger/.local/lib/python3.9/site-packages/torch/serialization.py", line 392, in _deserialize
    return obj.to(device=device)
  File "/home/tiger/.local/lib/python3.9/site-packages/torch/storage.py", line 187, in to
    return _to(self, device, non_blocking)
  File "/home/tiger/.local/lib/python3.9/site-packages/torch/_utils.py", line 75, in _to
    with device_module.device(device):
  File "/home/tiger/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 386, in __enter__
    self.prev_idx = torch.cuda._exchange_device(self.idx)
  File "/home/tiger/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 300, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

**Comment by Jintao-Huang** [comment]
什么模型啊
拉取一下main分支试试呢

**Comment by Browallia** [comment]
@Jintao-Huang qwen2用的是最新的main分支

**Comment by Browallia** [comment]
@Jintao-Huang 请问一下qwen2系列模型不支持v100 fp16微调？ 我这边loss一直为0 请问这个是什么原因 有什么gap吗 之前用LLaMA-Factory是支持的

**Comment by tastelikefeet** [comment]
> @Jintao-Huang 请问一下qwen2系列模型不支持v100 fp16微调？ 我这边loss一直为0 请问这个是什么原因 有什么gap吗 之前用LLaMA-Factory是支持的

多大的qwen2，较小的qwen2模型一般不太稳定

**Comment by Browallia** [comment]
@tastelikefeet qwen2-7b-instruct 用8卡v100 sft loss是0 grad_norm是nan

**Comment by Browallia** [comment]
![20240816-132201](https://github.com/user-attachments/assets/f6582b6f-2925-4915-bc0f-898e69ee95af)
lr一直为0

**Comment by Jintao-Huang** [comment]
V100会有这个问题，nan了，用qwen1.5好了

V100使用fp16训练导致的吧

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/issues/1131

**Comment by Jintao-Huang** [comment]
> @Jintao-Huang 请问一下qwen2系列模型不支持v100 fp16微调？ 我这边loss一直为0 请问这个是什么原因 有什么gap吗 之前用LLaMA-Factory是支持的

不会的，这个应该都不支持，你设置一下--dtype bf16或者fp32

**Comment by Jintao-Huang** [comment]
尝试一下 拉取一下最新的main分支代码，看看是否存在这个问题
