### ISSUE TITLE
这个可视化界面没办法打开啊 一直是报错 但是下载报错的包有显示无法导入。。。

### ISSUE THREAD

**Issue by 307yin** [modelscope/ms-swift#1746]
(xunihuanjing) root@dsw-429608-674f4df657-ccmmk:/mnt/workspace/swift# SWIFT_UI_LANG=en swift web-ui
Traceback (most recent call last):
  File "/mnt/workspace/xunihuanjing/lib/python3.10/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/mnt/workspace/xunihuanjing/lib/python3.10/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet.zip/wordnet/

  Searched in:
    - '/root/nltk_data'
    - '/mnt/workspace/xunihuanjing/nltk_data'
    - '/mnt/workspace/xunihuanjing/share/nltk_data'
    - '/mnt/workspace/xunihuanjing/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/workspace/xunihuanjing/bin/swift", line 33, in <module>
    sys.exit(load_entry_point('ms-swift', 'console_scripts', 'swift')())
  File "/mnt/workspace/xunihuanjing/bin/swift", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/workspace/swift/swift/__init__.py", line 4, in <module>
    from .utils.import_utils import _LazyModule
  File "/mnt/workspace/swift/swift/utils/__init__.py", line 6, in <module>
    from .metric import compute_acc_metrics, compute_nlg_metrics, preprocess_logits_for_metrics
  File "/mnt/workspace/swift/swift/utils/metric.py", line 6, in <module>
    from nltk.translate.bleu_score import SmoothingFunction, sentence_bleu
  File "/mnt/workspace/xunihuanjing/lib/python3.10/site-packages/nltk/__init__.py", line 153, in <module>
    from nltk.translate import *
  File "/mnt/workspace/xunihuanjing/lib/python3.10/site-packages/nltk/translate/__init__.py", line 24, in <module>
    from nltk.translate.meteor_score import meteor_score as meteor
  File "/mnt/workspace/xunihuanjing/lib/python3.10/site-packages/nltk/translate/meteor_score.py", line 14, in <module>
    from nltk.stem.api import StemmerI
  File "/mnt/workspace/xunihuanjing/lib/python3.10/site-packages/nltk/stem/__init__.py", line 34, in <module>
    from nltk.stem.wordnet import WordNetLemmatizer
  File "/mnt/workspace/xunihuanjing/lib/python3.10/site-packages/nltk/stem/wordnet.py", line 13, in <module>
    class WordNetLemmatizer:
  File "/mnt/workspace/xunihuanjing/lib/python3.10/site-packages/nltk/stem/wordnet.py", line 48, in WordNetLemmatizer
    morphy = wn.morphy
  File "/mnt/workspace/xunihuanjing/lib/python3.10/site-packages/nltk/corpus/util.py", line 120, in __getattr__
    self.__load()
  File "/mnt/workspace/xunihuanjing/lib/python3.10/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/mnt/workspace/xunihuanjing/lib/python3.10/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/mnt/workspace/xunihuanjing/lib/python3.10/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet

  Searched in:
    - '/root/nltk_data'
    - '/mnt/workspace/xunihuanjing/nltk_data'
    - '/mnt/workspace/xunihuanjing/share/nltk_data'
    - '/mnt/workspace/xunihuanjing/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

**Comment by tastelikefeet** [comment]
Lazy import added by #1748

**Comment by teamwong111** [comment]
使用 Lazy import 在 sft 时是否还是会报错
