### ISSUE TITLE
InternVL2-8b DPO Failed mapping

### ISSUE THREAD

**Issue by bonre** [modelscope/ms-swift#1768]
非常感谢贵组的工作！
我使用的是最新拉取的main分支下的swift版本。
我尝试使用如下脚本进行dpo：
```
nproc_per_node=8

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
NPROC_PER_NODE=$nproc_per_node \
MASTER_PORT=29500 \
swift rlhf \
    --rlhf_type dpo \
    --model_type  internvl2-8b \
    --model_id_or_path /data/SWIFT/InternVL/internvl2-8b_V0/checkpoint-2856-merged \
    --ref_model_id_or_path /data/SWIFT/InternVL/internvl2-8b_V0/checkpoint-2856-merged \
    --output_dir /data/swift/adapter/InternVL \
    --dtype bf16 \
    --beta 0.1 \
    --sft_beta 0.1 \
    --sft_type  lora \
    --init_lora_weights 'pissa' \
    --lora_rank 128 \
    --lora_alpha 256 \
    --lora_dropout_p 0.1 \
    --use_flash_attn true \
    --dataset /DPOdataset/tar_data/0819_dpo.json \
    --num_train_epochs  2  \
    --gradient_checkpointing  true  \
    --batch_size  1  \
    --per_device_train_batch_size 1 \
    --learning_rate  5e-6 \
    --gradient_accumulation_steps  $(expr 16 / $nproc_per_node)  \
    --warmup_ratio  0.03  \
    --save_total_limit  2 \
    --max_prompt_length 8192 \
    --max_length -1 
```
数据集为自定义数据集，按如下格式构造：
```
{"system": "123", "query": "11111", "response": "22222", "rejected_response": "33333", "images": ["image_path"], "history": [["query1", "response1"], ["query2", "response2"]]}
{"system": "123", "query": "aaaaa", "response": "bbbbb", "rejected_response": "ccccc", "images": ["image_path"], "history": [["query1", "response1"], ["query2", "response2"]]}
{"system": "123", "query": "AAAAA", "response": "BBBBB", "rejected_response": "CCCCC", "images": ["image_path"], "history": [["query1", "response1"], ["query2", "response2"]]}
```
按照文档说明，system和history为可选项则没有添加。
运行脚本后，我这边会警告如下：

> Parameter 'function'=<bound method DPOTrainer.tokenize_row of <swift.trainers.dpo_trainer.DPOTrainer object at 0x7f61af2a2040>> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.

/home/.cache/huggingface/hub/dataset 下会出现一个非常大的文件导致磁盘空间一直写满
请问这是否是正常的现象呢？
因为我之前没有具体使用过，所以有些疑惑，还望能帮我解答，非常感谢！
```
Map:  86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                | 1019/1188 [08:23<01:23,  2.02 examples/s]
Traceback (most recent call last):
  File "/home/anaconda3/envs/ixc2/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3468, in _map_single
    writer.write(example)
  File "/home/anaconda3/envs/ixc2/lib/python3.9/site-packages/datasets/arrow_writer.py", line 499, in write
    self.write_examples_on_file()
  File "/home/anaconda3/envs/ixc2/lib/python3.9/site-packages/datasets/arrow_writer.py", line 457, in write_examples_on_file
    self.write_batch(batch_examples=batch_examples)
  File "/home/anaconda3/envs/ixc2/lib/python3.9/site-packages/datasets/arrow_writer.py", line 571, in write_batch
    self.write_table(pa_table, writer_batch_size)
  File "/home/anaconda3/envs/ixc2/lib/python3.9/site-packages/datasets/arrow_writer.py", line 589, in write_table
    self.pa_writer.write_table(pa_table, writer_batch_size)
  File "pyarrow/ipc.pxi", line 525, in pyarrow.lib._CRecordBatchWriter.write_table
  File "/home/anaconda3/envs/ixc2/lib/python3.9/site-packages/fsspec/implementations/local.py", line 381, in write
    return self.f.write(*args, **kwargs)
OSError: [Errno 28] No space left on device
```

**Comment by GhostofAdam** [comment]
similar problem, do you solve it?

**Comment by bonre** [comment]
No,I tried to use kto and got better performance so that I give up using dpo.
I think maybe the loss dont fit my task.

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/pull/1975
