### ISSUE TITLE
MiniCPM-V2.6在自己数据上LoRA微调，训练过程中报错DataLoader worker (pid 184751) is killed by signal: Segmentation fault. 

### ISSUE THREAD

**Issue by for-code0216** [modelscope/ms-swift#1806]
使用MiniCPM-V2.6在自己数据上LoRA微调训练视频，训练到20%报错如下：

Traceback (most recent call last):
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 184751) is killed by signal: Segmentation fault. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-contentunderstanding/users/MiniCPM-V/ms-swift-main/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-contentunderstanding/users/MiniCPM-V/ms-swift-main/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-contentunderstanding/users/MiniCPM-V/ms-swift-main/swift/llm/sft.py", line 406, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-contentunderstanding/users/MiniCPM-V/ms-swift-main/swift/trainers/mixin.py", line 538, in train
    res = super().train(resume_from_checkpoint, *args, **kwargs)
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/transformers/trainer.py", line 2165, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/accelerate/data_loader.py", line 464, in __iter__
    next_batch = next(dataloader_iter)
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1145, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 184751) exited unexpectedly
[2024-08-22 20:24:50,097] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 176538 closing signal SIGTERM
[2024-08-22 20:24:50,098] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 176542 closing signal SIGTERM
[2024-08-22 20:24:50,099] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 176544 closing signal SIGTERM
[2024-08-22 20:24:50,102] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 176545 closing signal SIGTERM
[2024-08-22 20:24:50,103] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 176546 closing signal SIGTERM
[2024-08-22 20:24:50,625] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 176540) of binary: /workdir/users/anaconda3/envs/users/bin/python3.9
Traceback (most recent call last):
  File "/workdir/users/anaconda3/envs/users/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/workdir/users/anaconda3/envs/users/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/dolphinfs/hdd_pool/docker/user/hadoop-contentunderstanding/users/MiniCPM-V/ms-swift-main/swift/cli/sft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-22_20:24:50
  host      : set-zw04-mlp-codelab-pc443.mt
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 176540)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html 

请问这个错误是自己的数据（视频）有问题吗？
谢谢！

**Comment by Jintao-Huang** [comment]
看起来是内存不足
