### ISSUE TITLE
GLM-4V-9B fine-tuning error: ValueError: 151339 is not in list

### ISSUE THREAD

**Issue by tw-repository** [modelscope/ms-swift#1840]
Traceback (most recent call last):
  File "/home/sa/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/home/sa/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/home/sa/swift/swift/llm/sft.py", line 417, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/home/sa/swift/swift/trainers/mixin.py", line 552, in train
    res = super().train(resume_from_checkpoint, *args, **kwargs)
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 1932, in train
    return inner_training_loop(
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 2268, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/transformers/trainer.py", line 3307, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/sa/swift/swift/trainers/trainers.py", line 165, in compute_loss
    outputs = model(**inputs)
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1582, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/accelerate/utils/operations.py", line 819, in forward
    return model_forward(*args, **kwargs)
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/accelerate/utils/operations.py", line 807, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/peft/peft_model.py", line 1577, in forward
    return self.base_model(
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sa/anaconda3/envs/glm4v/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 188, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/sa/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 1198, in forward
    boi_token_pos, eoi_token_pos = input_id.index(self.config.boi_token_id), input_id.index(
ValueError: 151339 is not in list

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/issues/1712

**Comment by tw-repository** [comment]
> #1712

我的数据里面是包含了图片路径的，我也检查了路径是正确的

**Comment by Jintao-Huang** [comment]
你看看数据中的是image字段 还是 images. 感觉没有读入进去

**Comment by wanghaifeng77** [comment]
我也遇到同样的问题。

**Comment by tw-repository** [comment]
> 我也遇到同样的问题。

两个方法：
（1）每条数据都有一张图片。严格按照这种数据格式，构建数据集。
{
"messages": [
{
"role": "user",
"content": "图片中的动物是什么？",
"image": "/root/images/0001.jpg"
},
{
"role": "assistant",
"content": "图片中有一只猫。"
},
{
"role": "user",
"content": "图片中的猫在做什么？"
},
{
"role": "assistant",
"content": "这只猫坐在或站在桌子上，桌上有很多食物。"
}
]
}
（2）重新下载模型或代码：https://modelscope.cn/models/ZhipuAI/glm-4-9b-chat/files
这个主要看你那里的模型或代码是什么时候的，根据官方所提供的代码，后面有他们的更新时间。模型下载过基本不用再次重下。主要是其他关联的代码文件需要更新到最新的。

完成上述以后，我这里有一个微调的命令可以参考：
CUDA_VISIBLE_DEVICES=0 swift sft \
    --model_id_or_path 所下载的模型路径/glm-4v-9b \
    --model_type glm4v-9b-chat \
    --dataset 数据集路径/xxx.json \
    --num_train_epochs 5 \
    --sft_type lora \
    --output_dir /mnt/disk/tw_data/finetune_output \
    --eval_steps 300 \
    --batch_size 1 \
    --max_length 2048 \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --gradient_checkpointing true \
    --weight_decay 0.1 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps $(expr 16 / 3) \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --save_steps 300 \
    --save_total_limit 2

**Comment by tw-repository** [comment]
> > > 我也遇到同样的问题。
> > 
> > 
> > 两个方法： （1）每条数据都有一张图片。严格按照这种数据格式，构建数据集。 { "messages": [ { "role": "user", "content": "图片中的动物是什么？", "image": "/root/images/0001.jpg" }, { "role": "assistant", "content": "图片中有一只猫。" }, { "role": "user", "content": "图片中的猫在做什么？" }, { "role": "assistant", "content": "这只猫坐在或站在桌子上，桌上有很多食物。" } ] } （2）重新下载模型或代码：https://modelscope.cn/models/ZhipuAI/glm-4-9b-chat/files 这个主要看你那里的模型或代码是什么时候的，根据官方所提供的代码，后面有他们的更新时间。模型下载过基本不用再次重下。主要是其他关联的代码文件需要更新到最新的。
> > 完成上述以后，我这里有一个微调的命令可以参考： CUDA_VISIBLE_DEVICES=0 swift sft --model_id_or_path 所下载的模型路径/glm-4v-9b --model_type glm4v-9b-chat --dataset 数据集路径/xxx.json --num_train_epochs 5 --sft_type lora --output_dir /mnt/disk/tw_data/finetune_output --eval_steps 300 --batch_size 1 --max_length 2048 --lora_rank 8 --lora_alpha 32 --lora_dropout_p 0.05 --gradient_checkpointing true --weight_decay 0.1 --learning_rate 1e-4 --gradient_accumulation_steps $(expr 16 / 3) --max_grad_norm 0.5 --warmup_ratio 0.03 --save_steps 300 --save_total_limit 2
> 
> 数据格式按照你说的调整了，但是我下载的模型是glm-4v-9b：[https://modelscope.cn/models/ZhipuAI/glm-4v-9b/files，也是最新的文件，和你用的模型：https://modelscope.cn/models/ZhipuAI/glm-4-9b-chat/files不同，结果还是同样的问题，不知道是不是模型不同的原因？](https://modelscope.cn/models/ZhipuAI/glm-4v-9b/files%EF%BC%8C%E4%B9%9F%E6%98%AF%E6%9C%80%E6%96%B0%E7%9A%84%E6%96%87%E4%BB%B6%EF%BC%8C%E5%92%8C%E4%BD%A0%E7%94%A8%E7%9A%84%E6%A8%A1%E5%9E%8B%EF%BC%9Ahttps://modelscope.cn/models/ZhipuAI/glm-4-9b-chat/files%E4%B8%8D%E5%90%8C%EF%BC%8C%E7%BB%93%E6%9E%9C%E8%BF%98%E6%98%AF%E5%90%8C%E6%A0%B7%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E6%98%AF%E4%B8%8D%E6%98%AF%E6%A8%A1%E5%9E%8B%E4%B8%8D%E5%90%8C%E7%9A%84%E5%8E%9F%E5%9B%A0%EF%BC%9F)

不好意思，发错了连接，我也是glm-4v-9b。那可能再考虑一下安装环境的版本之类的问题，比如transformer那个库。此外，有时候真的重新下载模型和代码可能有奇效，也可以尝试一下。我就是重新下载解决的问题。

**Comment by wanghaifeng77** [comment]
> transformer

transformer你用的是什么版本，我来换一个试试看

**Comment by tw-repository** [comment]
4.44.0。如果还没效果，只能重新下载模型和代码再试一下了。

**Comment by wanghaifeng77** [comment]
> 4.44.0。如果还没效果，只能重新下载模型和代码再试一下了。

重下了，不行，你的代码用的是哪个版本？

**Comment by tastelikefeet** [comment]
请问目前仍然存在问题吗？

**Comment by tw-repository** [comment]
> 请问目前仍然存在问题吗？

问题已解决

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/issues/1712

**Comment by Greywan** [comment]
> > 请问目前仍然存在问题吗？
> 
> 问题已解决

请问怎么解决的？

**Comment by ao-te-man** [comment]
> 我也遇到同样的问题。

想问下解决了吗？
