### ISSUE TITLE
qwen2-vl-7b-instruct 以VLLM形式启动推理引擎失败“ assert "factor" in rope_scaling”

### ISSUE THREAD

**Issue by wyclike** [modelscope/ms-swift#1954]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
命令：CUDA_VISIBLE_DEVICES=0 swift infer --model_type qwen2-vl-7b-instruct  --infer_backend vllm --max_model_len 4096

[INFO:swift] Loading the model using model_dir: /vepfs/fs_users/weiyuancheng-test/ckpt/hub/qwen/Qwen2-VL-7B-Instruct
Traceback (most recent call last):
  File "/vepfs/fs_users/weiyuancheng-test/swift/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "/vepfs/fs_users/weiyuancheng-test/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/vepfs/fs_users/weiyuancheng-test/swift/swift/llm/infer.py", line 282, in llm_infer
    llm_engine, template = prepare_vllm_engine_template(args)
  File "/vepfs/fs_users/weiyuancheng-test/swift/swift/llm/utils/vllm_utils.py", line 583, in prepare_vllm_engine_template
    llm_engine = get_vllm_engine(
  File "/vepfs/fs_users/weiyuancheng-test/swift/swift/llm/utils/vllm_utils.py", line 103, in get_vllm_engine
    llm_engine = llm_engine_cls.from_engine_args(engine_args)
  File "/vepfs/fs_users/weiyuancheng-test/envs/main/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 438, in from_engine_args
    engine_config = engine_args.create_engine_config()
  File "/vepfs/fs_users/weiyuancheng-test/envs/main/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 699, in create_engine_config
    model_config = ModelConfig(
  File "/vepfs/fs_users/weiyuancheng-test/envs/main/lib/python3.10/site-packages/vllm/config.py", line 167, in __init__
    self.max_model_len = _get_and_verify_max_len(
  File "/vepfs/fs_users/weiyuancheng-test/envs/main/lib/python3.10/site-packages/vllm/config.py", line 1506, in _get_and_verify_max_len
    assert "factor" in rope_scaling
AssertionError

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
4090
torch：2.3.1

**Comment by zhangfan-algo** [comment]
＋1

**Comment by wangaocheng** [comment]
遇到相同的问题。

**Comment by Jintao-Huang** [comment]
https://github.com/QwenLM/Qwen2-VL/issues/96
