### ISSUE TITLE
mplug-owl3-7b-chat fine-tuning document

### ISSUE THREAD

**Issue by Jintao-Huang** [modelscope/ms-swift#1969]
Model:
- ModelScope: https://www.modelscope.cn/models/iic/mPLUG-Owl3-7B-240728
- Huggingface: https://huggingface.co/mPLUG/mPLUG-Owl3-7B-240728

Usually, fine-tuning a multimodal large model involves using a custom dataset for fine-tuning. Here, we will demonstrate a runnable demo.

Fine-tuned Dataset: 
- https://www.modelscope.cn/datasets/modelscope/coco_2014_caption
- https://www.modelscope.cn/datasets/swift/VideoChatGPT

Before starting the fine-tuning, please ensure that your environment is properly prepared.

```bash
git clone https://github.com/modelscope/ms-swift.git
cd swift
pip install -e .[llm]

pip install decord icecream
```

## Inference
```
# ModelScope
CUDA_VISIBLE_DEVICES=0 swift infer \
  --model_type mplug-owl3-7b-chat \
  --model_id_or_path iic/mPLUG-Owl3-7B-240728 \

# HuggingFace
USE_HF=1 CUDA_VISIBLE_DEVICES=0 swift infer \
  --model_type mplug-owl3-7b-chat \
  --model_id_or_path mPLUG/mPLUG-Owl3-7B-240728 \
```

**Results**

```
<<< who are you
I am an AI language model, designed to assist with a variety of tasks such as answering questions and providing information. I do not have a physical form, but rather exist as a program running on a computer. Is there anything specific you would like me to help you with?
--------------------------------------------------
<<< <image>describe the image
Input an image path or URL <<< http://modelscope-open.oss-cn-hangzhou.aliyuncs.com/images/cat.png
[INFO:swift] Setting max_num_frames: 16. You can adjust this hyperparameter through the environment variable: `MAX_NUM_FRAMES`.
This is a very cute photo of a kitten! The kitten has beautiful blue eyes and a very fluffy coat. It's adorable to see how it looks at the camera. The colors in the photo are very natural and well-balanced, which adds to the overall cuteness of the image. Great job capturing this adorable moment!
--------------------------------------------------
<<< clear
<<< <video>describe the video
Input a video path or URL <<< https://modelscope-open.oss-cn-hangzhou.aliyuncs.com/images/baby.mp4
The video captures a young child's interest in reading and learning, as they are seen sitting on a bed and flipping through the pages of a book while wearing glasses. The child appears to be engaged and curious about the content of the book.
```

**GPU Memory:**
<img width="579" alt="截屏2024-09-07 13 11 33" src="https://github.com/user-attachments/assets/2d0d82d5-c844-4b26-ad97-f67c53892544">

**Comment by Jintao-Huang** [comment]
## image fine-tuning
The format of the custom dataset is as follows (single image, multiple images, and no image):
```
{"query": "<image>55555", "response": "66666", "images": ["image_path"]}
{"query": "eeeee<image>eeeee<image>eeeee", "response": "fffff", "history": [], "images": ["image_path1", "image_path2"]}
{"query": "EEEEE", "response": "FFFFF", "history": [["query1", "response2"], ["query2", "response2"]], "images": []}
```

**Fine-tuning script:**

```
# ModelScope
CUDA_VISIBLE_DEVICES=0,1,2,3 NPROC_PER_NODE=4 swift sft \
  --model_type mplug-owl3-7b-chat \
  --model_id_or_path iic/mPLUG-Owl3-7B-240728 \
  --sft_type lora \
  --dataset coco-en-mini#20000 \
  --deepspeed default-zero2 \
  --output_dir output \
  --num_train_epochs 5
```

If you want to use a custom dataset, simply specify as follows:
```bash
  --dataset train.jsonl \
  --val_dataset val.jsonl \
```

Here is the inference script after fine-tuning, we perform inference on the automatically segmented validation set:
```
# If using HuggingFace, please add: `USE_HF=1`
# inference only
CUDA_VISIBLE_DEVICES=0 swift infer \
    --ckpt_dir output/mplug-owl3-7b-chat/vx-xxx/checkpoint-xxx \
    --load_dataset_config true --show_dataset_sample 10

# merge-lora & inference
CUDA_VISIBLE_DEVICES=0 swift infer \
    --ckpt_dir output/mplug-owl3-7b-chatt/vx-xxx/checkpoint-xxx \
    --load_dataset_config true --merge_lora true --show_dataset_sample 10
```

## video fine-tuning
The format of the custom dataset is as follows:
```
{"query": "<video>55555", "response": "66666", "videos": ["video_path"]}
{"query": "eeeee<video>eeeee<video>eeeee", "response": "fffff", "history": [], "videos": ["video_path1", "video_path2"]}
{"query": "EEEEE", "response": "FFFFF", "history": [["query1", "response2"], ["query2", "response2"]], "videos": []}
```

**Fine-tuning script:**

```bash
# ModelScope
CUDA_VISIBLE_DEVICES=0,1,2,3 NPROC_PER_NODE=4 swift sft \
  --model_type mplug-owl3-7b-chat \
  --model_id_or_path iic/mPLUG-Owl3-7B-240728 \
  --sft_type lora \
  --dataset video-chatgpt \
  --deepspeed default-zero2 \
  --output_dir output \
  --num_train_epochs 5
```

**Comment by ozhyo** [comment]
你好，试了下image fine-tuning的示例代码，发现训练过程中模型并没有用到image和media offset，data_collator貌似忽略了这两个值，导致模型在forward的过程中并没有用到图像

**Comment by Jintao-Huang** [comment]
我修复一下

**Comment by Jintao-Huang** [comment]
> 你好，试了下image fine-tuning的示例代码，发现训练过程中模型并没有用到image和media offset，data_collator貌似忽略了这两个值，导致模型在forward的过程中并没有用到图像

fixed

**Comment by ozhyo** [comment]
你好，感谢修复。
我测试了下，现在已经能利用image和media offset进行模型forward和训练了，但是只能开启batch_size=1，貌似因为media offset并没有进行padding，导致长度不匹配从而无法组成batch

**Comment by goodstudent9** [comment]
确实，我也试了，不能开起batchsize = 2
`[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/home/project/tools/anaconda3/envs/owl3/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/home/project/tools/anaconda3/envs/owl3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
[rank0]:     return self.collate_fn(data)
[rank0]:   File "/home/project/ruohangxu/ms-swift/swift/llm/utils/template.py", line 3318, in data_collator
[rank0]:     res['media_offset'] = torch.concat(media_offset)
[rank0]: RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 122 but got size 124 for tensor number 1 in the list.`

**Comment by Jintao-Huang** [comment]
> 确实，我也试了，不能开起batchsize = 2 `[rank0]: Original Traceback (most recent call last): [rank0]: File "/home/project/tools/anaconda3/envs/owl3/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop [rank0]: data = fetcher.fetch(index) # type: ignore[possibly-undefined] [rank0]: File "/home/project/tools/anaconda3/envs/owl3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch [rank0]: return self.collate_fn(data) [rank0]: File "/home/project/ruohangxu/ms-swift/swift/llm/utils/template.py", line 3318, in data_collator [rank0]: res['media_offset'] = torch.concat(media_offset) [rank0]: RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 122 but got size 124 for tensor number 1 in the list.`

是的 不支持batch_size=2, 我也不知道该如何支持。我尝试使用padding，但会在owl3的代码中抛错误.

**Comment by goodstudent9** [comment]
我把代码改成可以支持并行了，但是我不太确信效果如何，我正在验证我的代码和batch size=1时候在你提供的那个训练集上面的效果，如果可以的话，我再来和你交流哈



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 22, 2024 23:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [modelscope/ms-swift] mplug-owl3-7b-chat fine-tuning document(Issue #1969)




  
确实，我也试了，不能开起batchsize = 2 [rank0]: Original Traceback (most recent call last): [rank0]: File "/home/project/tools/anaconda3/envs/owl3/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop [rank0]: data = fetcher.fetch(index) # type: ignore[possibly-undefined] [rank0]: File "/home/project/tools/anaconda3/envs/owl3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch [rank0]: return self.collate_fn(data) [rank0]: File "/home/project/ruohangxu/ms-swift/swift/llm/utils/template.py", line 3318, in data_collator [rank0]: res['media_offset'] = torch.concat(media_offset) [rank0]: RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 122 but got size 124 for tensor number 1 in the list.
  
是的 不支持batch_size=2, 我也不知道该如何支持。我尝试使用padding，但会在owl3的代码中抛错误.

**Comment by goodstudent9** [comment]
所以那个padding标记到底是什么呢？就是你在训练的时候用的这个media offset的padding



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 22, 2024 23:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [modelscope/ms-swift] mplug-owl3-7b-chat fine-tuning document(Issue #1969)




  
确实，我也试了，不能开起batchsize = 2 [rank0]: Original Traceback (most recent call last): [rank0]: File "/home/project/tools/anaconda3/envs/owl3/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop [rank0]: data = fetcher.fetch(index) # type: ignore[possibly-undefined] [rank0]: File "/home/project/tools/anaconda3/envs/owl3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch [rank0]: return self.collate_fn(data) [rank0]: File "/home/project/ruohangxu/ms-swift/swift/llm/utils/template.py", line 3318, in data_collator [rank0]: res['media_offset'] = torch.concat(media_offset) [rank0]: RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 122 but got size 124 for tensor number 1 in the list.
  
是的 不支持batch_size=2, 我也不知道该如何支持。我尝试使用padding，但会在owl3的代码中抛错误.

**Comment by Jintao-Huang** [comment]
> 我把代码改成可以支持并行了，但是我不太确信效果如何，我正在验证我的代码和batch size=1时候在你提供的那个训练集上面的效果，如果可以的话，我再来和你交流哈

如果发现效果可以，欢迎提供PR哈

**Comment by goodstudent9** [comment]
你那边有你提供的这个脚本的实验结果吗？可以分享一下coco-en-mini#20000数据集的结果来做一个比较吗？
我说的脚本是指：
CUDA_VISIBLE_DEVICES=0,1,2,3 NPROC_PER_NODE=4 swift sft \   --model_type mplug-owl3-7b-chat \   --model_id_or_path iic/mPLUG-Owl3-7B-240728 \   --sft_type lora \   --dataset coco-en-mini#20000 \   --deepspeed default-zero2 \   --output_dir output \   --num_train_epochs 5
&nbsp;


onlysword
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月22日(星期天) 晚上11:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [modelscope/ms-swift] mplug-owl3-7b-chat fine-tuning document (Issue #1969)














  
我把代码改成可以支持并行了，但是我不太确信效果如何，我正在验证我的代码和batch size=1时候在你提供的那个训练集上面的效果，如果可以的话，我再来和你交流哈
  
如果发现效果可以，欢迎提供PR哈

**Comment by ozhyo** [comment]
按照论文的说法，有图的时候padding [0, 0]，无图的时候则全为[0, -1000000]（这里任意负值都可以]，是这样吗？

**Comment by goodstudent9** [comment]
论文里有提到0，0 padding吗？我咋没读到哎。而且就算在有图的时候给了0，0的padding，会报错的，我已经试过了
我现在做了就是把最后一个token扩充到padding的长度，也就是batch的最长长度，代码可以正常运行，但是实验效果很不好。所以我猜测作者原来训练肯定不是复制序列末尾元素的方式来padding，但是现在无论是负数padding还是0padding我都试了，都会报错。只能问问作者了。
&nbsp;


onlysword
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Huayu ***@***.***&gt;; 
发送时间: 2024年9月23日(星期一) 上午10:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [modelscope/ms-swift] mplug-owl3-7b-chat fine-tuning document (Issue #1969)














 
按照论文的说法，有图的时候padding [0, 0]，无图的时候则全为[0, -1000000]（这里任意负值都可以]，是这样吗？

**Comment by Jintao-Huang** [comment]
PR: https://github.com/modelscope/ms-swift/pull/2100

**Comment by goodstudent9** [comment]
Found some bugs when I do full parameters finetune.
Mplug-owl3 means a lot to me, thank you so much for your valuable help! 

https://github.com/modelscope/ms-swift/issues/2158

**Comment by goodstudent9** [comment]
> Found some bugs when I do full parameters finetune. Mplug-owl3 means a lot to me, thank you so much for your valuable help!
> 
> #2158

**solved!**

**Comment by goodstudent9** [comment]
https://github.com/modelscope/ms-swift/issues/2172#issue-2555462329

**Comment by goodstudent9** [comment]
https://github.com/modelscope/ms-swift/issues/2172#issue-2555462329
Error will occur when inference with images.

**Comment by RAW-si18** [comment]
Can i add few more layers in between OWL3 2B model to fine tune for my tasks and my domain?

**Comment by RAW-si18** [comment]
Can it be finetuned for only images and then only text like that?

**Comment by RushDon** [comment]
how to fix this problem?

File "/usr/local/lib/python3.8/dist-packages/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "/usr/local/lib/python3.8/dist-packages/swift/llm/infer/infer.py", line 202, in infer_main
    return SwiftInfer(args).main()
  File "/usr/local/lib/python3.8/dist-packages/swift/llm/infer/infer.py", line 31, in __init__
    self.infer_engine, self.template = prepare_pt_engine_template(args)
  File "/usr/local/lib/python3.8/dist-packages/swift/llm/infer/utils.py", line 160, in prepare_pt_engine_template
    pt_engine: PtEngine = SwiftInfer.get_infer_engine(args, infer_backend='pt', load_model=load_model, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/swift/llm/infer/infer.py", line 70, in get_infer_engine
    return infer_engine_cls(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/swift/llm/infer/infer_engine/pt_engine.py", line 58, in __init__
    self.model, self.processor = get_model_tokenizer(
  File "/usr/local/lib/python3.8/dist-packages/swift/llm/model/register.py", line 496, in get_model_tokenizer
    model, processor = get_function(model_dir, model_info, model_kwargs, load_model, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/swift/llm/model/model/mplug.py", line 85, in get_model_tokenizer_mplug_owl3
    _use_submodel_func(model, 'language_model', func_list)
NameError: name '_use_submodel_func' is not defined

**Comment by Jintao-Huang** [comment]
swift3, please refer to here: https://github.com/modelscope/ms-swift/tree/main/examples/train/multimodal
