### ISSUE TITLE
LLaVA-NeXT-Video model configuration initialize error

### ISSUE THREAD

**Issue by VenusHui** [modelscope/ms-swift#1986]
**Describe the bug**
When deploying LLaVA-NeXT-Video-34B-hf, I find that the configuration key passed to transformers is "llava_next_video", while the accurate key in tranformers is "llava-next-video".

My deploy command:
`swift deploy --model_type llava-next-video-34b-instruct --model_id_or_path /xxx/LLaVA-NeXT-Video-34B-hf --tensor_parallel_size 2 --host 0.0.0.0 --port 7860 --tp 2 --dtype bf16 --cache_max_entry_count 0.5 --quantization_bit 4`

I hacked the source code of `transformers/models/auto/configuration_auto.py`, the function `__get_item__` in class `_LazyConfigMapping`:

```python
def __getitem__(self, key):
        if key in self._extra_content:
            return self._extra_content[key]
        if key == "llava_next_video": # hacked here
            key = "llava-next-video"
        if key not in self._mapping:
            raise KeyError(key)
        value = self._mapping[key]
        module_name = model_type_to_module_name(key)
        if module_name not in self._modules:
            self._modules[module_name] = importlib.import_module(f".{module_name}", "transformers.models")
        if hasattr(self._modules[module_name], value):
            return getattr(self._modules[module_name], value)

        # Some of the mappings have entries model_type -> config of another model type. In that case we try to grab the
        # object at the top level.
        transformers_module = importlib.import_module("transformers")
        return getattr(transformers_module, value)
```

Then the deploy command works well.

**Your hardware and system info**
CUDA Version: 12.0
Driver Version: 525.125.06
GPU: RTX 3090 * 2
Torch: 2.3.1
swift: 2.4.0.post1
transformers: 4.44.2

**Additional context**

**Comment by tastelikefeet** [comment]
May I ask where is the exact place we pass the `llava_next_video` key to transformers?

**Comment by VenusHui** [comment]
Sorry, I forgot to provide the detailed error log.
The traceback:
```
Traceback (most recent call last):
  File "/home/jinhui-hu/tools/anaconda/anaconda3/envs/pytorch/lib/python3.8/site-packages/swift/cli/deploy.py", line 5, in <module>
    deploy_main()
  File "/home/jinhui-hu/tools/anaconda/anaconda3/envs/pytorch/lib/python3.8/site-packages/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/home/jinhui-hu/tools/anaconda/anaconda3/envs/pytorch/lib/python3.8/site-packages/swift/llm/deploy.py", line 813, in llm_deploy
    model, template = prepare_model_template(args)
  File "/home/jinhui-hu/tools/anaconda/anaconda3/envs/pytorch/lib/python3.8/site-packages/swift/llm/infer.py", line 185, in prepare_model_template
    model, tokenizer = get_model_tokenizer(
  File "/home/jinhui-hu/tools/anaconda/anaconda3/envs/pytorch/lib/python3.8/site-packages/swift/llm/utils/model.py", line 6561, in get_model_tokenizer
    model, tokenizer = get_function(model_dir, torch_dtype, model_kwargs, load_model, **kwargs)
  File "/home/jinhui-hu/tools/anaconda/anaconda3/envs/pytorch/lib/python3.8/site-packages/swift/llm/utils/model.py", line 6235, in get_model_tokenizer_llava_next_video_yi
    model, tokenizer = get_model_tokenizer_llava_next_video(*args, **kwargs)
  File "/home/jinhui-hu/tools/anaconda/anaconda3/envs/pytorch/lib/python3.8/site-packages/swift/llm/utils/model.py", line 6222, in get_model_tokenizer_llava_next_video
    return get_model_tokenizer_llava_hf(*args, **kwargs)
  File "/home/jinhui-hu/tools/anaconda/anaconda3/envs/pytorch/lib/python3.8/site-packages/swift/llm/utils/model.py", line 6036, in get_model_tokenizer_llava_hf
    model, tokenizer = get_model_tokenizer_with_flash_attn(model_dir, *args, **kwargs)
  File "/home/jinhui-hu/tools/anaconda/anaconda3/envs/pytorch/lib/python3.8/site-packages/swift/llm/utils/model.py", line 2549, in get_model_tokenizer_with_flash_attn
    model_config = AutoConfig.from_pretrained(model_dir, trust_remote_code=True)
  File "/home/jinhui-hu/tools/anaconda/anaconda3/envs/pytorch/lib/python3.8/site-packages/modelscope/utils/hf_util.py", line 113, in from_pretrained
    module_obj = module_class.from_pretrained(model_dir, *model_args,
  File "/home/jinhui-hu/tools/anaconda/anaconda3/envs/pytorch/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 995, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `llava_next_video` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
```
I think the problem is caused by this class `LlavaNextVideoForConditionalGeneration` 
```python
# line 6219
def get_model_tokenizer_llava_next_video(*args, **kwargs):
    from transformers import LlavaNextVideoForConditionalGeneration
    kwargs['automodel_class'] = LlavaNextVideoForConditionalGeneration
    return get_model_tokenizer_llava_hf(*args, **kwargs)
```
And maybe this is a bug of transformers?
I'm not that good at python, qwq.

**Comment by Jintao-Huang** [comment]
升级一下transformers呢
