### ISSUE TITLE
Can't do RLHF with InternVL2-4B

### ISSUE THREAD

**Issue by yuanf8** [modelscope/ms-swift#1987]
**Describe the bug**
Can't seem to do DPO or ORPO with InternVL2-4B:

 - RLHF command:
```bash
CUDA_VISIBLE_DEVICES=0 \
swift rlhf \
    --model_type internvl2-4b \
    --dataset /rlhf_train.json \
    --dataset_test_ratio 0.1 \
    --dtype fp16 \
    --rlhf_type orpo \
    --beta 0.1 \
    --sft_type lora \
    --lora_rank 64 \
    --max_length 8192 \
    --output_dir output \
    --batch_size 4 \
    --gradient_accumulation_steps 4 \
    --learning_rate 2.5e-5 \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.1 \
    --num_train_epochs 3 \
    --eval_batch_size 4 \
    --eval_steps 500 \
    --evaluation_strategy steps
```
 - Training data sample:
 ```json
 {
      "query": "What is in the picture?",
      "response": "SKITCHEN Berlin Pan Bundle",
      "rejected_response": "Berlin Pan Bundle",
      "images": [
          "test.jpg"
      ]
  }
```
- Error message:
```log
Train:   0%|                               | 0/2184 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/swift/cli/rlhf.py", line 5, in <module>
    rlhf_main()
  File "/usr/local/lib/python3.10/dist-packages/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/swift/llm/rlhf.py", line 229, in llm_rlhf
    trainer.train(training_args.resume_from_checkpoint)
  File "/usr/local/lib/python3.10/dist-packages/swift/trainers/dpo_trainer.py", line 64, in train
    res = super().train(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/swift/trainers/mixin.py", line 409, in train
    res = super().train(resume_from_checkpoint, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2216, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 3238, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py", line 1408, in compute_loss
    loss, metrics = self.get_batch_loss_metrics(model, inputs, train_eval="train")
  File "/usr/local/lib/python3.10/dist-packages/swift/trainers/dpo_trainer.py", line 209, in get_batch_loss_metrics
    forward_output = self.concatenated_forward(model, batch)
  File "/usr/local/lib/python3.10/dist-packages/swift/trainers/dpo_trainer.py", line 330, in concatenated_forward
    outputs = model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    args_kwargs_result = hook(self, args, kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/swift/llm/utils/template.py", line 321, in _pre_forward_hook
    res_extra.append(self._post_encode(d))
  File "/usr/local/lib/python3.10/dist-packages/swift/llm/utils/template.py", line 1895, in _post_encode
    inputs_embeds[selected] = vit_embeds.reshape(-1, vit_embeds.shape[-1])
RuntimeError: shape mismatch: value tensor of shape [2560, 3072] cannot be broadcast to indexing result of shape [1280, 3072]
```

**Your hardware and system info**
- torch 2.3.1
- CUDA 12.1

**Comment by hjh0119** [comment]
Is this issue present in the latest code? It should have been fixed.

**Comment by yuanf8** [comment]
The issue persists in ms-swift version 2.4.0
