### ISSUE TITLE
LISA训练要么OOM，要么使用deepseed就报错

### ISSUE THREAD

**Issue by LIUKAI0815** [modelscope/ms-swift#2035]
export VLLM_USE_MODELSCOPE=false
CUDA_VISIBLE_DEVICES=5,6 \
    NPROC_PER_NODE=2 \
    swift sft \
    --model_type qwen2-7b-instruct \
    --model_id_or_path /workspace/model/llm/Qwen/Qwen2-7B-Instruct \
    --dataset /workspace/data/llm/rewrite_and_classify/train_total_rewrite_0914.jsonl \
    --output_dir /workspace/output/nlp_rewrite/qwen \
    --system """You are a helpful dialogue rewriter""" \
    --num_train_epochs 2 \
    --batch_size 1 \
    --sft_type full \
    --use_flash_attn True \
    --use_liger True \
    --lisa_activated_layers 2\
    --lisa_step_interval 20 \
    --deepspeed default-zero3 \

如果是单卡4090就会出现OOM，使用多卡不用deepseed也会OOM，使用deepseed就会报错

[INFO:swift] The SftArguments will be saved in: /workspace/output/nlp_rewrite/qwen/qwen2-7b-instruct/v4-20240914-101631/sft_args.json
[INFO:swift] The Seq2SeqTrainingArguments will be saved in: /workspace/output/nlp_rewrite/qwen/qwen2-7b-instruct/v4-20240914-101631/training_args.json
[INFO:swift] The logging file will be saved in: /workspace/output/nlp_rewrite/qwen/qwen2-7b-instruct/v4-20240914-101631/logging.jsonl
Using /root/.cache/torch_extensions/py310_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py310_cu121/fused_adam/build.ninja...
/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_adam...
Time to load fused_adam op: 0.10750508308410645 seconds
Parameter Offload: Total persistent parameters: 333312 in 141 params
Train:   0%|          | 0/9588 [00:00<?, ?it/s][rank0]:[E ProcessGroupNCCL.cpp:563] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=_REDUCE_SCATTER_BASE, NumelIn=3584, NumelOut=1792, Timeout(ms)=600000) ran for 600033 milliseconds before timing out.
[rank0]:[E ProcessGroupNCCL.cpp:1537] [PG 1 Rank 0] Timeout at NCCL work: 2, last enqueued NCCL work: 4, last completed NCCL work: 1.
[rank0]:[E ProcessGroupNCCL.cpp:577] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank0]:[E ProcessGroupNCCL.cpp:583] [Rank 0] To avoid data inconsistency, we are taking the entire process down.
[rank0]:[E ProcessGroupNCCL.cpp:1414] [PG 1 Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=_REDUCE_SCATTER_BASE, NumelIn=3584, NumelOut=1792, Timeout(ms)=600000) ran for 600033 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:565 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f627eacf897 in /root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7f6232a7b1b2 in /root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1a0 (0x7f6232a7ffd0 in /root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7f6232a8131c in /root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdc253 (0x7f6286636253 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x7f628ff48ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x126850 (0x7f628ffda850 in /usr/lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG 1 Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=_REDUCE_SCATTER_BASE, NumelIn=3584, NumelOut=1792, Timeout(ms)=600000) ran for 600033 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:565 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f627eacf897 in /root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7f6232a7b1b2 in /root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1a0 (0x7f6232a7ffd0 in /root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7f6232a8131c in /root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdc253 (0x7f6286636253 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x7f628ff48ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x126850 (0x7f628ffda850 in /usr/lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1418 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f627eacf897 in /root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe32e33 (0x7f6232703e33 in /root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xdc253 (0x7f6286636253 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #3: <unknown function> + 0x94ac3 (0x7f628ff48ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x126850 (0x7f628ffda850 in /usr/lib/x86_64-linux-gnu/libc.so.6)

W0914 10:27:27.986000 139894184810304 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 3982363 closing signal SIGTERM
E0914 10:27:28.302000 139894184810304 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: -6) local_rank: 0 (pid: 3982362) of binary: /root/miniconda3/envs/swift/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/swift/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/swift/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in <module>
    main()
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
========================================================
/workspace/model/server/swift/swift/cli/sft.py FAILED
--------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-14_10:27:27
  host      : 4f02e20d4ced
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 3982362)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 3982362
========================================================

**Comment by zhuqh19** [comment]
请问这个问题解决了吗

**Comment by DYF-AI** [comment]
同样使用LISA训练也是OOM，已经设为2了，3B的模型，2张24GB的显卡还是OOM

**Comment by slin000111** [comment]
> 同样使用LISA训练也是OOM，已经设为2了，3B的模型，2张24GB的显卡还是OOM

`--ddp_find_unused_parameters True`

**Comment by z0o0ey** [comment]
Please try again using the latest versions of Swift and VLLM. If the problem persists or you have any new suggestions or comments, please feel free to create a new question.
