### ISSUE TITLE
AttributeError: 'Qwen2VLForConditionalGeneration' object has no attribute 'quantize'. Did you mean: 'dequantize'?

### ISSUE THREAD

**Issue by CachCheng** [modelscope/ms-swift#2039]
[INFO:swift] Qwen2VLForConditionalGeneration: 8291.3756M Params (0.0000M Trainable [0.0000%]), 234.8828M Buffers.
[INFO:swift] system: You are a helpful assistant.
[INFO:swift] Quantization dataset: ['ms-bench']
[INFO:swift] Start quantizing the model...
Traceback (most recent call last):
  File "/meta/cash/llm/swift/swift/cli/export.py", line 5, in <module>
    export_main()
  File "/meta/cash/llm/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/meta/cash/llm/swift/swift/llm/export.py", line 252, in llm_export
    awq_model_quantize(model, template.tokenizer, args.quant_batch_size)
  File "/meta/cash/llm/swift/swift/llm/export.py", line 138, in awq_model_quantize
    awq_model.quantize(tokenizer, quant_config=quant_config, n_parallel_calib_samples=batch_size)
  File "/home/ahs/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Qwen2VLForConditionalGeneration' object has no attribute 'quantize'. Did you mean: 'dequantize'?

**Comment by Jintao-Huang** [comment]
fixed

**Comment by CachCheng** [comment]
I have update the ms-swift and transformers to the latest, but this error still exist:

[INFO:swift] Start quantizing the model...
Traceback (most recent call last):
  File "/meta/cash/llm/swift/swift/cli/export.py", line 5, in <module>
    export_main()
  File "/meta/cash/llm/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/meta/cash/llm/swift/swift/llm/export.py", line 259, in llm_export
    awq_model_quantize(model, template.tokenizer, args.quant_batch_size)
  File "/meta/cash/llm/swift/swift/llm/export.py", line 93, in awq_model_quantize
    awq_model.quantize(tokenizer, quant_config=quant_config, n_parallel_calib_samples=batch_size)
  File "/home/ahs/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Qwen2VLForConditionalGeneration' object has no attribute 'quantize'. Did you mean: 'dequantize'?

**Comment by Jintao-Huang** [comment]
please use ms-swift>=2.5

**Comment by CachCheng** [comment]
$ pip list | grep ms-swift
ms-swift                          2.6.0.dev0           /meta/cash/llm/swift

I have used the latest version from source code

**Comment by Jintao-Huang** [comment]
please use gptq

awq not support qwen2vl

https://github.com/casper-hansen/AutoAWQ/pull/599
