### ISSUE TITLE
Florence2 finetuning failed (Florence2LanguageForConditionalGeneration.forward() got an unexpected keyword argument '_data')

### ISSUE THREAD

**Issue by lluo-Desktop** [modelscope/ms-swift#2115]
1. I setup swift project and can infer Florence2 model using `CUDA_VISIBLE_DEVICES=0 swift infer --model_type florence-2-large-ft --max_new_tokens 1024 --stream false`
2. When I try to run demo
  `CUDA_VISIBLE_DEVICES=0 swift sft --model_type florence-2-large-ft  --dataset coco-en-2-mini  --sft_type full`
  It failed and the error log is :
```
  Traceback (most recent call last):
  File "/home/code/ms-swift-main/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/home/code/ms-swift-main/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/home/code/ms-swift-main/swift/llm/sft.py", line 505, in llm_sft
    return trainer_train(args, model, template, train_dataset, val_dataset, callbacks=callbacks, msg=msg)
  File "/home/code/ms-swift-main/swift/llm/sft.py", line 455, in trainer_train
    trainer.train(training_args.resume_from_checkpoint)
  File "/home/code/ms-swift-main/swift/trainers/mixin.py", line 424, in train
    res = super().train(resume_from_checkpoint, *args, **kwargs)
  File "/home/env/ms-swif/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
  File "/home/env/ms-swif/lib/python3.10/site-packages/transformers/trainer.py", line 2279, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/env/ms-swif/lib/python3.10/site-packages/transformers/trainer.py", line 3318, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/code/ms-swift-main/swift/trainers/trainers.py", line 161, in compute_loss
    outputs = model(**inputs)
  File "/home/env/ms-swif/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/env/ms-swif/lib/python3.10/site-packages/accelerate/utils/operations.py", line 819, in forward
    return model_forward(*args, **kwargs)
  File "/home/env/ms-swif/lib/python3.10/site-packages/accelerate/utils/operations.py", line 807, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/env/ms-swif/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/code/ms-swift-main/swift/llm/utils/model.py", line 4460, in _new_func
    res = _old_func(submodel, *args, **kwargs)
TypeError: Florence2LanguageForConditionalGeneration.forward() got an unexpected keyword argument '_data'
```

**Comment by Jintao-Huang** [comment]
Please use torch>=2.0.

**Comment by lluo-Desktop** [comment]
> Please use torch>=2.0.

Thanks for your quick suggest, problem solved.
