### ISSUE TITLE
qwen2-vl-7b-instruct推理报错：torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 39.25 GiB. 

### ISSUE THREAD

**Issue by wanghaifeng77** [modelscope/ms-swift#2127]
swift infer命令： CUDA_VISIBLE_DEVICES=1,0 swift infer --model_type qwen2-vl-7b-instruct   --model_id_or_path /data1/gpt/model/qwen2-vl-7b-instruct
输入：
描述视频
Input a video path or URL <<< /data1/qwen2vl/test/test.mp4
报错：
Exception in thread Thread-3 (_model_generate):
Traceback (most recent call last):
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/qwen2vl/ms-swift/swift/llm/utils/utils.py", line 745, in _model_generate
    res = model.generate(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/transformers/generation/utils.py", line 2045, in generate
    result = self._sample(
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/transformers/generation/utils.py", line 3009, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1698, in forward
    video_embeds = self.visual(pixel_values_videos, grid_thw=video_grid_thw)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1128, in forward
    hidden_states = blk(hidden_states, cu_seqlens=cu_seqlens, rotary_pos_emb=rotary_pos_emb)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 431, in forward
    hidden_states = hidden_states + self.attn(
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/anaconda3/envs/qwen2vl/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 404, in forward
    attn_output = F.scaled_dot_product_attention(q, k, v, attention_mask, dropout_p=0.0)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 39.25 GiB. GPU 0 has a total capacity of 23.65 GiB of which 3.33 GiB is free. Process 1097573 has 2.15 GiB memory in use. Including non-PyTorch memory, this process has 18.16 GiB memory in use. Of the allocated memory 11.84 GiB is allocated by PyTorch, and 4.62 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
系统信息：
Ubuntu 22.04.2 LTS (GNU/Linux 5.19.0-43-generic x86_64)
CUDA Version: 12.0  
Name: torch Version: 2.4.0
GPU：2个4090
其他信息：
视频大小：2.5M，12s
Tried to allocate 39.25 GiB. GPU，这个39G的GPU分配是正常的吗？

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/blob/main/docs/source/Instruction/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%95%B4%E7%90%86.md#q6-qwen2-vl%E6%8E%A8%E7%90%86%E7%88%86%E6%98%BE%E5%AD%98

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/issues/2010
