### ISSUE TITLE
用全量微调过的llava-onevision-qwen2-0_5b-ov权重在chartqa数据集上进行eval遇到RuntimeError: Failed to import swift.llm.deploy because of the following error (look up to see its traceback): cannot import name 'add_vllm_request' from 'swift.llm.utils' (/data/swift/swift/llm/utils/__init__.py)问题

### ISSUE THREAD

**Issue by Psycho-9** [modelscope/ms-swift#2128]
用经过full stf之后的权重在chartqa和docvqa等进行验证，命令是swift eval --model_type llava-onevision-qwen2-0_5b-ov --local_repo_path /data/swift/LLaVA/ --ckpt_dir /data/swift/llava-onevision-qwen2-0_5b-ov/checkpoint-20200/ --eval_dataset ChartQA_TEST --eval_output_dir eval_outputs/llava-onevision-qwen2-0_5b-ov-chartqa `，但是发生下面错误
```
Traceback (most recent call last):
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/swift/swift/llmTraceback (most recent call last):
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/swift/swift/llm/eval.py", line 140, in run_custom_model
    from swift.llm import deploy_main
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/data/swift/swift/utils/import_utils.py", line 54, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/data/swift/swift/utils/import_utils.py", line 66, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import swift.llm.deploy because of the following error (look up to see its traceback):
cannot import name 'add_vllm_request' from 'swift.llm.utils' (/data/swift/swift/llm/utils/__init__.py)
[ERROR:swift] Cannot get model_type from the deploy service, please check the error to continue eval
[INFO:swift] The deployment process has been terminated.
Traceback (most recent call last):
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused/eval.py", line 140, in run_custom_model
    from swift.llm import deploy_main
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/data/swift/swift/utils/import_utils.py", line 54, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/data/swift/swift/utils/import_utils.py", line 66, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import swift.llm.deploy because of the following error (look up to see its traceback):
cannot import name 'add_vllm_request' from 'swift.llm.utils' (/data/swift/swift/llm/utils/__init__.py)
[ERROR:swift] Cannot get model_type from the deploy service, please check the error to continue eval
[INFO:swift] The deployment process has been terminated.
Traceback (most recent call last):
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/data/qdluo/anaconda3/envs/swift/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refuse
```，请问是什么原因呢？

**Comment by Jintao-Huang** [comment]
fixed
