### ISSUE TITLE
请问支持Mac M系列机器吗

### ISSUE THREAD

**Issue by mobguang** [modelscope/ms-swift#2163]
你好，

在M2 ultra机器上通过源码安装了了swift的Web-UI，尝试基于已下载的minicpm_2.6模型进行推理，但系统报错，请问是哪里配置有问题吗，谢谢。

Traceback (most recent call last):
  File "/user/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/blocks.py", line 1532, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/utils.py", line 671, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/utils.py", line 664, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/anaconda3/envs/swift/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/anaconda3/envs/swift/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/user/anaconda3/envs/swift/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/utils.py", line 647, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/user/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/utils.py", line 809, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "/Volumes/M2SSD/Space/Workspace/llm/ms-swift/swift/cli/../../swift/ui/llm_infer/llm_infer.py", line 458, in send_message
    _, args = Runtime.parse_info_from_cmdline(running_task)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/M2SSD/Space/Workspace/llm/ms-swift/swift/cli/../../swift/ui/llm_infer/runtime.py", line 222, in parse_info_from_cmdline
    slash = task.find('/')
            ^^^^^^^^^

**设置参数如下：**
![image](https://github.com/user-attachments/assets/6bf412af-a63f-4031-87cc-916c977054c0)

**Comment by jiahansu** [comment]
Mac有自帶名稱相同的指令swift,所以用web-ui是無法呼叫到正確的ms-swift指令，要去修改web-ui的原始代碼，將swift指令指到python路徑下的swift例如
`~/.pyenv/versions/3.12.5/bin/swift`

**Comment by mobguang** [comment]
@jiahansu 
谢谢你的回复，请问具体要如何修改代码呢，能否详细指导一下，感谢。

**Comment by slin000111** [comment]
推理框架(--infer_backend)尝试选pt
