### ISSUE TITLE
qwen2-vl-7b-instruct vllm inference assert "factor" in rope_scaling

### ISSUE THREAD

**Issue by daje0601** [modelscope/ms-swift#2188]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

```python
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
[INFO:swift] args: InferArguments(model_type='qwen2-vl-7b-instruct', model_id_or_path='qwen/Qwen2-VL-7B-Instruct', model_revision='master', sft_type='lora', template_type='qwen2-vl', infer_backend='vllm', ckpt_dir='/home/datadriven/ds/iitp-Data/model_text-k-fold/model5/qwen2-vl-7b-instruct/v0-20241003-040534/checkpoint-400', result_dir=None, load_args_from_ckpt_dir=True, load_dataset_config=False, eval_human=False, seed=42, dtype='bf16', model_kwargs={}, dataset=['./data/k-fold-text/test_5_query_format.json'], val_dataset=[], dataset_seed=42, dataset_test_ratio=1.0, show_dataset_sample=-1, save_result=True, system='You are a helpful assistant.', tools_prompt='react_en', max_length=None, truncation_strategy='delete', check_dataset_strategy='none', model_name=[None, None], model_author=[None, None], quant_method=None, quantization_bit=0, hqq_axis=0, hqq_dynamic_config_path=None, bnb_4bit_comp_dtype='bf16', bnb_4bit_quant_type='nf4', bnb_4bit_use_double_quant=True, bnb_4bit_quant_storage=None, max_new_tokens=2048, do_sample=None, temperature=None, top_k=None, top_p=None, repetition_penalty=None, num_beams=1, stop_words=[], rope_scaling=None, use_flash_attn=None, ignore_args_error=False, stream=True, merge_lora=False, merge_device_map='cpu', save_safetensors=True, overwrite_generation_config=False, verbose=None, local_repo_path=None, custom_register_path=None, custom_dataset_info=None, device_map_config=None, device_max_memory=[], hub_token=None, gpu_memory_utilization=0.9, tensor_parallel_size=1, max_num_seqs=256, max_model_len=None, disable_custom_all_reduce=True, enforce_eager=False, limit_mm_per_prompt=None, vllm_enable_lora=True, vllm_max_lora_rank=16, lora_modules=['default-lora=/home/datadriven/ds/iitp-Data/model_text-k-fold/model5/qwen2-vl-7b-instruct/v0-20241003-040534/checkpoint-400'], max_logprobs=20, tp=1, cache_max_entry_count=0.8, quant_policy=0, vision_batch_size=1, self_cognition_sample=0, train_dataset_sample=-1, val_dataset_sample=None, safe_serialization=None, model_cache_dir=None, merge_lora_and_save=None, custom_train_dataset_path=[], custom_val_dataset_path=[], vllm_lora_modules=None, device_map_config_path=None)
[INFO:swift] Global seed set to 42
[INFO:swift] device_count: 1
[INFO:swift] Downloading the model from ModelScope Hub, model_id: qwen/Qwen2-VL-7B-Instruct
[WARNING:modelscope] Using branch: master as version is unstable, use with caution
[INFO:swift] Loading the model using model_dir: /home/datadriven/.cache/modelscope/hub/qwen/Qwen2-VL-7B-Instruct
Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_section'}
Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_section'}
Traceback (most recent call last):
  File "/data/ds/ms-swift/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "/data/ds/ms-swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/data/ds/ms-swift/swift/llm/infer.py", line 283, in llm_infer
    llm_engine, template = prepare_vllm_engine_template(args)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/ds/ms-swift/swift/llm/utils/vllm_utils.py", line 618, in prepare_vllm_engine_template
    llm_engine = get_vllm_engine(
                 ^^^^^^^^^^^^^^^^
  File "/data/ds/ms-swift/swift/llm/utils/vllm_utils.py", line 123, in get_vllm_engine
    llm_engine = llm_engine_cls.from_engine_args(engine_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datadriven/anaconda3/envs/swift/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 561, in from_engine_args
    engine_config = engine_args.create_engine_config()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datadriven/anaconda3/envs/swift/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 874, in create_engine_config
    model_config = self.create_model_config()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datadriven/anaconda3/envs/swift/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 811, in create_model_config
    return ModelConfig(
           ^^^^^^^^^^^^
  File "/home/datadriven/anaconda3/envs/swift/lib/python3.11/site-packages/vllm/config.py", line 207, in __init__
    self.max_model_len = _get_and_verify_max_len(
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datadriven/anaconda3/envs/swift/lib/python3.11/site-packages/vllm/config.py", line 1746, in _get_and_verify_max_len
    assert "factor" in rope_scaling
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

I want to use `--infer_backend vllm`, `--vllm_enable_lora true` parameter. 
But, I met this error. Is this not available on the H100?

And that's how the installation went:

```python 
(aivl) $ git clone https://github.com/modelscope/ms-swift.git
(aivl) $ cd ms-swift
(aivl) $ pip install -e .[llm]

pip install git+https://github.com/huggingface/transformers.git
pip install pyav qwen_vl_utils
#!< https://github.com/modelscope/ms-swift/issues/2064 
# qwen2-vl 
# https://github.com/QwenLM/Qwen2-VL/issues/96
pip install git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830
pip install vllm>=0.6.1
```

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

CUDA Version: 12.4
system: ubuntu
GPU : H100 
torch version : '2.4.0+cu121'

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/issues/1954
