### ISSUE TITLE
llama-omni推理报错，importlib.metadata.PackageNotFoundError: No package metadata was found for The 'whisper' distribution was not found and is required by this application. 

### ISSUE THREAD

**Issue by sixbenzene** [modelscope/ms-swift#2231]
INFO:swift] Start time of running main: 2024-10-12 08:09:39.056207
[INFO:swift] ckpt_dir: None
[INFO:swift] Due to `ckpt_dir` being `None`, `load_args_from_ckpt_dir` is set to `False`.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/utils/versions.py", line 102, in require_version
    got_ver = importlib.metadata.version(pkg)
  File "/home/ubuntu/anaconda3/envs/swift/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/home/ubuntu/anaconda3/envs/swift/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/ubuntu/anaconda3/envs/swift/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for whisper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/lgq/project/swift/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "/home/ubuntu/lgq/project/swift/swift/utils/run_utils.py", line 22, in x_main
    args, remaining_argv = parse_args(args_class, argv)
  File "/home/ubuntu/lgq/project/swift/swift/utils/utils.py", line 131, in parse_args
    args, remaining_args = parser.parse_args_into_dataclasses(argv, return_remaining_strings=True)
  File "/home/ubuntu/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/hf_argparser.py", line 339, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 86, in __init__
  File "/home/ubuntu/lgq/project/swift/swift/llm/utils/argument.py", line 1469, in __post_init__
    self.set_model_type()
  File "/home/ubuntu/lgq/project/swift/swift/llm/utils/argument.py", line 535, in set_model_type
    require_version(require)
  File "/home/ubuntu/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/utils/versions.py", line 104, in require_version
    raise importlib.metadata.PackageNotFoundError(
importlib.metadata.PackageNotFoundError: No package metadata was found for The 'whisper' distribution was not found and is required by this application. 

使用的新环境
git clone https://github.com/modelscope/swift.git
cd swift
pip install -e '.[llm]'
通过这个方式构建的环境
CUDA_VISIBLE_DEVICES=0 swift infer --model_type llama3_1-8b-omni执行这个指令推理
发现报错后
使用pip install openai-whisper，还是报这个错

**Comment by sixbenzene** [comment]
已经解决，pip install whisper
