### ISSUE TITLE
swift export 量化 qwen1half-7b-chat 出错

### ISSUE THREAD

**Issue by Liufeiran123** [modelscope/ms-swift#2233]
命令为
CUDA_VISIBLE_DEVICES=0 swift export     --model_type qwen1half-7b-chat --quant_bits 4     --dataset alpaca-zh alpaca-en --quant_method gptq

报错为
AttributeError: 'Qwen2ForCausalLM' object has no attribute ''

包版本信息为：
ms-swift                  2.6.0.dev0
optimum                   1.23.1
auto-gptq                 0.8.0.dev0+cu121

**Comment by Jintao-Huang** [comment]
报错截图看看

**Comment by Liufeiran123** [comment]
[INFO:swift] Split into 21 blocks
Traceback (most recent call last):
  File "/mnt/d/ai/swift/swift/cli/export.py", line 5, in <module>
    export_main()
  File "/mnt/d/ai/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/mnt/d/ai/swift/swift/llm/export.py", line 263, in llm_export
    gptq_quantizer = gptq_model_quantize(model, template.tokenizer, args.quant_batch_size)
  File "/mnt/d/ai/swift/swift/llm/export.py", line 162, in gptq_model_quantize
    gptq_quantizer.quantize_model(model, tokenizer)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 404, in quantize_model
    blocks = recurse_getattr(model, self.block_name_to_quantize)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/optimum/utils/modeling_utils.py", line 45, in recurse_getattr
    return functools.reduce(_getattr, [obj] + attr.split("."))
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/optimum/utils/modeling_utils.py", line 43, in _getattr
    return getattr(obj, attr)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Qwen2ForCausalLM' object has no attribute ''

**Comment by Jintao-Huang** [comment]
fixed, main branch

**Comment by TZJ12** [comment]
你好，请问这个问题你是怎么解决的呢？我也遇到了这个错误
