### ISSUE TITLE
llama-omni微调相关问题

### ISSUE THREAD

**Issue by sixbenzene** [modelscope/ms-swift#2237]
1，是只能微调LLM吗，我使用模型只能使用文字对话，不能传输语音数据。意思是只能使用LLM，没有speech encoder,speech adaptor?现阶段是否有论文上的stag1的微调，请告知，谢谢。
![image](https://github.com/user-attachments/assets/80829c0d-cf0a-4cf1-b2a5-a087f1037f6f)

**Comment by Jintao-Huang** [comment]
现在支持llm, vit, projector部分

speech_generator不支持训练

**Comment by sixbenzene** [comment]
> 现在支持llm, vit, projector部分
> 
> speech_generator不支持训练
谢谢！请问默认的数据集有能直接使用的吗，或者该构建怎样的数据集，是[语音指令，文本响应]这样的数据集吗？

**Comment by Jintao-Huang** [comment]
参考这里：https://github.com/modelscope/ms-swift/issues/1653

**Comment by sixbenzene** [comment]
> 参考这里：#1653

谢谢！

**Comment by learn01one** [comment]
hello，没大理解，speech adaptor是支持训练微调的还是不支持呢？

**Comment by Jintao-Huang** [comment]
支持的, 就是 generator那里是不微调的. 因为loss函数和ms-swift的数据集格式不太兼容

不过可以自己改改源代码来支持

**Comment by fromlimbo** [comment]
> 参考这里：#1653

你好，参考的文档里还是有点疑惑，想问下aishell1-zh-mini这个数据集下载下来是可以直接运行的呢，还是也要自己把它做成下面的格式，可以给一个微调的数据sample看看吗，感谢
`
[
    {"conversations": [
        {"from": "user", "value": "<audio>audio_path</audio>11111"},
        {"from": "assistant", "value": "22222"}
    ]},
    {"conversations": [
        {"from": "user", "value": "<audio>audio_path</audio><audio>audio_path2</audio><audio>audio_path3</audio>aaaaa"},
        {"from": "assistant", "value": "bbbbb"},
        {"from": "user", "value": "<audio>audio_path</audio>ccccc"},
        {"from": "assistant", "value": "ddddd"}
    ]},
    {"conversations": [
        {"from": "user", "value": "AAAAA"},
        {"from": "assistant", "value": "BBBBB"},
        {"from": "user", "value": "CCCCC"},
        {"from": "assistant", "value": "DDDDD"}
    ]}
]
`

**Comment by Shookwu** [comment]
@Jintao-Huang 请问可以支持只训练speech adaptor吗，如果要更换自己的模型是需要修改源代码吗，另外infer好像支持文本输入？谢谢🙏

**Comment by satheeshkola-532** [comment]
> 支持的, 就是 generator那里是不微调的. 因为loss函数和ms-swift的数据集格式不太兼容
> 
> 不过可以自己改改源代码来支持

@Jintao-Huang you said that "the generator is not fine-tuned. Because the loss function is not compatible with the ms-swift data set format. However, you can modify the source code yourself to support it." , so could you please modify the Llama omni pipeline code to enable the speech generator fine tuning also..., if you're okay with that we're also willing to collaborate to contribute to this(Then this will be the first end to end speech - speech language model pipeline..)

**Comment by fromlimbo** [comment]
各位加个讨论群，来看看一起搞个全量版本的微调方案吧
![img_v3_02fn_7021a358-95d0-4d47-b956-96e2f107ceeg](https://github.com/user-attachments/assets/6623adc6-ab74-4a46-b5f1-e0b49fcc0fb1)

**Comment by learn01one** [comment]
你好，请问下，lora微调是如何指定微调llm,vit, projector的一部分，如只想微调llm，或者只微调projector，如何设置呢

**Comment by enbiwudi** [comment]
> 各位加个讨论群，来看看一起搞个全量版本的微调方案吧 ![img_v3_02fn_7021a358-95d0-4d47-b956-96e2f107ceeg](https://private-user-images.githubusercontent.com/11754220/376930146-6623adc6-ab74-4a46-b5f1-e0b49fcc0fb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4ODc5MDIsIm5iZiI6MTcyOTg4NzYwMiwicGF0aCI6Ii8xMTc1NDIyMC8zNzY5MzAxNDYtNjYyM2FkYzYtYWI3NC00YTQ2LWI1ZjEtZTBiNDlmY2MwZmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDIwMjAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYWU3OTU2ZThmMDFkMTRjYzUxN2NkMDg5ZTIwZThhZGI1YmI4YTUyZGY3ZTJlMjJkZmRiMWJmMDYwYWUxYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-_xUAJc3q30VJ2b_yBwZ6B7s1_9F98qCttGaTho0cv8)

老哥能拉一下吗
enbiwudi123@gmail.com

**Comment by satheeshkola-532** [comment]
> Let's join the discussion group and see how to make a fine-tuning plan for the full version together. ![img_v3_02fn_7021a358-95d0-4d47-b956-96e2f107ceeg](https://private-user-images.githubusercontent.com/11754220/376930146-6623adc6-ab74-4a46-b5f1-e0b49fcc0fb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTIyMjUsIm5iZiI6MTcyOTkxMTkyNSwicGF0aCI6Ii8xMTc1NDIyMC8zNzY5MzAxNDYtNjYyM2FkYzYtYWI3NC00YTQ2LWI1ZjEtZTBiNDlmY2MwZmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAzMDUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkOTI3NTNhNDE0MDNmZmZiODk3ZTM2NDkyYTRiNjJmZmIwNmNmOWM3NGMzZjdhMmMzYjNlNzEzY2I2Mzc4MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ulv6-4WwEveiLp_Vsj5HQQlt9P8MgqktL7dIu0mo4jk)

can you add me in the group: satheeshkola532@gmail.com

**Comment by UNO-TTS** [comment]
你好，按照qwen-auido的格式构建数据集后，出现了如下bug：
[QUERY]<audio>/home3/nlp/llamo/dataset/speech/chunk_00000/0017.mp3</audio>
[OUTPUT]Traceback (most recent call last):
  File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/swift/llm/infer.py", line 558, in llm_infer
    response, _ = inference(
  File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/swift/llm/utils/utils.py", line 869, in inference
    generate_ids = model.generate(streamer=streamer, generation_config=generation_config, **inputs)
  File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home3/nlp/llamo/LLaMA-Omni/omni_speech/model/speech_generator/generation.py", line 62, in generate
    self._validate_assistant(assistant_model)
TypeError: _validate_assistant() missing 2 required positional arguments: 'tokenizer' and 'assistant_tokenizer'
# Ended (code 256) at Tue Oct 29 20:28:47 +08 2024, elapsed time 54 seconds
请问是哪里没有传入tokenizer吗？


> 支持的, 就是 generator那里是不微调的. 因为loss函数和ms-swift的数据集格式不太兼容
> 
> 不过可以自己改改源代码来支持

**Comment by UNO-TTS** [comment]
> 参考这里：#1653

你好，按照qwen-auido的格式构建数据集后，出现了如下bug：
[QUERY]/home3/nlp/llamo/dataset/speech/chunk_00000/0017.mp3
[OUTPUT]Traceback (most recent call last):
File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/swift/cli/infer.py", line 5, in
infer_main()
File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/swift/utils/run_utils.py", line 32, in x_main
result = llm_x(args, **kwargs)
File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/swift/llm/infer.py", line 558, in llm_infer
response, _ = inference(
File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/swift/llm/utils/utils.py", line 869, in inference
generate_ids = model.generate(streamer=streamer, generation_config=generation_config, **inputs)
File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/home3/nlp/llamo/LLaMA-Omni/omni_speech/model/speech_generator/generation.py", line 62, in generate
self._validate_assistant(assistant_model)
TypeError: _validate_assistant() missing 2 required positional arguments: 'tokenizer' and 'assistant_tokenizer'

请问是哪里没有传入tokenizer吗？

**Comment by wntg** [comment]
> 各位加个讨论群，来看看一起搞个全量版本的微调方案吧 ![img_v3_02fn_7021a358-95d0-4d47-b956-96e2f107ceeg](https://private-user-images.githubusercontent.com/11754220/376930146-6623adc6-ab74-4a46-b5f1-e0b49fcc0fb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODg2MTIsIm5iZiI6MTczMDc4ODMxMiwicGF0aCI6Ii8xMTc1NDIyMC8zNzY5MzAxNDYtNjYyM2FkYzYtYWI3NC00YTQ2LWI1ZjEtZTBiNDlmY2MwZmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA2MzE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNDFlZDc1N2Q1NjVjZDUzNmJlNjYzZTBlNWIzMGQzZjIyNmZlN2FjMWUwOTc0YmIyMTllODZkYzJiM2FkZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UYZ91xX1uuoDURnDNHKF0HNZ4kZ9FeHVLLSYwNkdS_U)

老哥能拉下我进群吗，我自己写个训练流程。

**Comment by fromlimbo** [comment]
微信群：
![20241105-151437](https://github.com/user-attachments/assets/3116a206-21e0-4ce0-bdd5-96370d0fca29)

**Comment by jin1258804025** [comment]
> > 参考这里：#1653
> 
> @Jintao-Huang 你好，按照qwen-auido的格式构建数据集后，出现了如下bug： [QUERY]/home3/nlp/llamo/dataset/speech/chunk_00000/0017.mp3 [OUTPUT]Traceback (most recent call last): File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/swift/cli/infer.py", line 5, in infer_main() File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/swift/utils/run_utils.py", line 32, in x_main result = llm_x(args, **kwargs) File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/swift/llm/infer.py", line 558, in llm_infer response, _ = inference( File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/swift/llm/utils/utils.py", line 869, in inference generate_ids = model.generate(streamer=streamer, generation_config=generation_config, **inputs) File "/home3/tools/anaconda3/envs/py39/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/home3/nlp/llamo/LLaMA-Omni/omni_speech/model/speech_generator/generation.py", line 62, in generate self._validate_assistant(assistant_model) TypeError: _validate_assistant() missing 2 required positional arguments: 'tokenizer' and 'assistant_tokenizer'
> 
> 请问是哪里没有传入tokenizer吗？

问题解决了吗？也遇到了同样的问题

**Comment by jin1258804025** [comment]
> 微信群： ![20241105-151437](https://private-user-images.githubusercontent.com/11754220/383042391-3116a206-21e0-4ce0-bdd5-96370d0fca29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjA2NzIsIm5iZiI6MTczMTkyMDM3MiwicGF0aCI6Ii8xMTc1NDIyMC8zODMwNDIzOTEtMzExNmEyMDYtMjFlMC00Y2UwLWJkZDUtOTYzNzBkMGZjYTI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA4NTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNzYxODA1ODY0NmViMzc2NTMzY2UyMWZjMTcxZThhNzFiOGQyMTE1NWU1NmQyNWZmMzI0MzJjNzFiZWU0NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yu2IfhjrQZgb_Y-wjs9pDa8jfSXuyeVLF_pKe7SRHSI)

可以拉我进下群吗？微信:jin1258804025,感谢大佬！

**Comment by z0o0ey** [comment]
Please try again using the latest versions of Swift and VLLM. If the problem persists or you have any new suggestions or comments, please feel free to create a new question.
