### ISSUE TITLE
无法导入prepare_vllm_engine_template

### ISSUE THREAD

**Issue by LixiangHello** [modelscope/ms-swift#2270]
Traceback (most recent call last):
  File "/root/miniconda3/envs/env/lib/python3.12/site-packages/swift/cli/deploy.py", line 5, in <module>
    deploy_main()
  File "/root/miniconda3/envs/env/lib/python3.12/site-packages/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/env/lib/python3.12/site-packages/swift/llm/deploy.py", line 880, in llm_deploy
    from .utils import prepare_vllm_engine_template
ImportError: cannot import name 'prepare_vllm_engine_template' from 'swift.llm.utils' (/root/miniconda3/envs/env/lib/python3.12/site-packages/swift/llm/utils/__init__.py)

# 版本
ms-swift==2.5.0.post1

**Comment by Jintao-Huang** [comment]
import vllm
看是否正常

**Comment by LixiangHello** [comment]
![image](https://github.com/user-attachments/assets/0756497c-2b9d-460c-9b39-8423312bdfb3)

# 版本
vllm==0.6.3

**Comment by Jintao-Huang** [comment]
请提issue到vllm
