### ISSUE TITLE
AttributeError: 'FieldInfo' object has no attribute 'required'. Did you mean: 'is_required'?

### ISSUE THREAD

**Issue by Labmem009** [modelscope/ms-swift#2291]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

Traceback (most recent call last):
  File "/ssd4/zhuyongchi/facemoji_rephrase/SimejiUM/ms-swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/ssd4/zhuyongchi/facemoji_rephrase/SimejiUM/ms-swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/ssd4/zhuyongchi/facemoji_rephrase/SimejiUM/ms-swift/swift/llm/sft.py", line 541, in llm_sft
    return trainer_train(args, model, template, train_dataset, val_dataset, callbacks=callbacks, msg=msg)
  File "/ssd4/zhuyongchi/facemoji_rephrase/SimejiUM/ms-swift/swift/llm/sft.py", line 491, in trainer_train
    trainer.train(training_args.resume_from_checkpoint)
  File "/ssd4/zhuyongchi/facemoji_rephrase/SimejiUM/ms-swift/swift/trainers/mixin.py", line 479, in train
    self._save_initial_model(self.args.output_dir)
  File "/ssd4/zhuyongchi/facemoji_rephrase/SimejiUM/ms-swift/swift/trainers/mixin.py", line 179, in _save_initial_model
    model = unwrap_model(self.model)
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/modeling_utils.py", line 5237, in unwrap_model
    return extract_model_from_parallel(model, **kwargs)
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/other.py", line 77, in extract_model_from_parallel
    from deepspeed import DeepSpeedEngine
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/__init__.py", line 22, in <module>
    from . import module_inject
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 567, in <module>
    from ..pipe import PipelineModule
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 26, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 29, in <module>
    from .zero.config import get_zero_config, ZeroStageEnum
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/runtime/zero/__init__.py", line 6, in <module>
    from .partition_parameters import ZeroParamType
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 709, in <module>
    class Init(InsertPostInitMethodToModuleSubClasses):
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 711, in Init
    param_persistence_threshold = get_config_default(DeepSpeedZeroConfig, "param_persistence_threshold")
  File "/ssd4/zhuyongchi/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/runtime/config_utils.py", line 116, in get_config_default
    field_name).required, f"'{field_name}' is a required field and does not have a default value"
AttributeError: 'FieldInfo' object has no attribute 'required'. Did you mean: 'is_required'?

**Comment by Jintao-Huang** [comment]
pip install deepspeed==0.14.5
