### ISSUE TITLE
量化qwen2-audio-7b 报错

### ISSUE THREAD

**Issue by Liufeiran123** [modelscope/ms-swift#2306]
详细报错信息
Traceback (most recent call last):
  File "/mnt/d/ai/swift/swift/cli/export.py", line 5, in <module>
    export_main()
  File "/mnt/d/ai/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/mnt/d/ai/swift/swift/llm/export.py", line 263, in llm_export
    gptq_quantizer = gptq_model_quantize(model, template.tokenizer, args.quant_batch_size)
  File "/mnt/d/ai/swift/swift/llm/export.py", line 162, in gptq_model_quantize
    gptq_quantizer.quantize_model(model, tokenizer)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 570, in quantize_model
    self.pack_model(model=model, quantizers=quantizers)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 641, in pack_model
    self._replace_by_quant_layers(model, quantizers)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 299, in _replace_by_quant_layers
    self._replace_by_quant_layers(child, names, name + "." + name1 if name != "" else name1)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 267, in _replace_by_quant_layers
    layer = getattr(module, attr)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Qwen2AudioEncoder' object has no attribute '_supports_sdpa'

**Comment by slin000111** [comment]
关于此报错的命令行有吗？

**Comment by Liufeiran123** [comment]
swift export --model_type qwen2-audio-7b-instruct --quant_bits 4 --dataset alpaca-zh --quant_method gptq

**Comment by Jintao-Huang** [comment]
我这里测试一切正常啊
你的transformers版本是?

**Comment by Liufeiran123** [comment]
那很奇怪了，我的 transformers    版本为        4.45.2

**Comment by Liufeiran123** [comment]
optimum                   1.23.1

**Comment by Jintao-Huang** [comment]
> swift export --model_type qwen2-audio-7b-instruct --quant_bits 4 --dataset alpaca-zh --quant_method gptq

please use optimum==1.22.0
