### ISSUE TITLE
lora微调后再量化，报错， 详细如下：

### ISSUE THREAD

**Issue by gracelinlin** [modelscope/ms-swift#2318]
**Describe the bug**
命令行：
CUDA_VISIBLE_DEVICES=5,6,7 nohup swift export \
  --ckpt_dir '/...../checkpoint-2793'  \
  --model_id_or_path /home/ubuntu/workspace/lin/qwen2.5_72b/Qwen2.5-72B-instruct \
  --model_type qwen2_5-72b-instruct  \
  --merge_lora true  \
  --quant_bits 4  \
  --quant_method awq  \
  --dataset /xxxx/all_ans_and_ana.csv > log_export_awq 2>&1  &
报错如下：
AWQ:  99%|█████████▉| 79/80 [3:05:39<02:21, 141.00s/it]
 71 Traceback (most recent call last):
 72   File "/home/ubuntu/miniconda3/envs/lin_svr/lib/python3.11/site-packages/swift/cli/export.py", line 5, in <module>
 73     export_main()
 74   File "/home/ubuntu/miniconda3/envs/lin_svr/lib/python3.11/site-packages/swift/utils/run_utils.py", line 32, in x_main
 75     result = llm_x(args, **kwargs)
 76              ^^^^^^^^^^^^^^^^^^^^^
 77   File "/home/ubuntu/miniconda3/envs/lin_svr/lib/python3.11/site-packages/swift/llm/export.py", line 252, in llm_export
 78     awq_model_quantize(model, template.tokenizer, args.quant_batch_size)
 79   File "/home/ubuntu/miniconda3/envs/lin_svr/lib/python3.11/site-packages/swift/llm/export.py", line 138, in awq_model_quantize
 80     awq_model.quantize(tokenizer, quant_config=quant_config, n_parallel_calib_samples=batch_size)
 81   File "/home/ubuntu/miniconda3/envs/lin_svr/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
 82     return func(*args, **kwargs)
 83            ^^^^^^^^^^^^^^^^^^^^^
 84   File "/home/ubuntu/miniconda3/envs/lin_svr/lib/python3.11/site-packages/awq/models/base.py", line 231, in quantize
 85     self.quantizer.quantize()
 86   File "/home/ubuntu/miniconda3/envs/lin_svr/lib/python3.11/site-packages/awq/quantize/quantizer.py", line 166, in quantize
 87     scales_list = [
 88                   ^
 89   File "/home/ubuntu/miniconda3/envs/lin_svr/lib/python3.11/site-packages/awq/quantize/quantizer.py", line 167, in <listcomp>
 90     self._search_best_scale(self.modules[i], **layer)
 91   File "/home/ubuntu/miniconda3/envs/lin_svr/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
 92     return func(*args, **kwargs)
 93            ^^^^^^^^^^^^^^^^^^^^^
 94   File "/home/ubuntu/miniconda3/envs/lin_svr/lib/python3.11/site-packages/awq/quantize/quantizer.py", line 330, in _search_best_scale
 95     best_scales = self._compute_best_scale(
 96                   ^^^^^^^^^^^^^^^^^^^^^^^^^
 97   File "/home/ubuntu/miniconda3/envs/lin_svr/lib/python3.11/site-packages/awq/quantize/quantizer.py", line 409, in _compute_best_scale
 98     raise Exception
 99 client_loop: send disconnect: Broken pipe
运行2次都报这个错

**Your hardware and system info**
H100

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
报错信息嘞

**Comment by gracelinlin** [comment]
> 报错信息嘞

我发现是 autoAWQ的报错， issue url: [best_ratio](https://github.com/casper-hansen/AutoAWQ/issues/598)
这个bug提了2个月了没有优化
我们 swift 可以自已支持awq量化吗？

**Comment by ransheng11** [comment]
@Jintao-Huang 你好请问这个问题有优化吗
<img width="916" alt="image" src="https://github.com/user-attachments/assets/dbd5d0ce-6492-402f-8317-82ca43287a6e" />

**Comment by Jintao-Huang** [comment]
请使用gptq量化

**Comment by lzk9508** [comment]
> > 报错信息嘞
> 
> 我发现是 autoAWQ的报错， issue url: [best_ratio](https://github.com/casper-hansen/AutoAWQ/issues/598) 这个bug提了2个月了没有优化 我们 swift 可以自已支持awq量化吗？


你好，请问最后你是怎么通过awq量化的呢

**Comment by z0o0ey** [comment]
Please try again using the latest versions of Swift and VLLM. If the problem persists or you have any new suggestions or comments, please feel free to create a new question.
