### ISSUE TITLE
运行 RM示例 报错

### ISSUE THREAD

**Issue by guru4elephant** [modelscope/ms-swift#2327]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
执行
``` shell
CUDA_VISIBLE_DEVICES=1 \
swift rlhf \
    --rlhf_type rm \
    --model_type  internvl2-2b \
    --sft_type  lora \
    --dataset rlaif-v#1000 \
    --num_train_epochs  2  \
    --lora_target_modules  ALL  \
    --gradient_checkpointing  true  \
    --batch_size  1  \
    --learning_rate  5e-5  \
    --gradient_accumulation_steps  16  \
    --warmup_ratio  0.03  \
    --save_total_limit  2
```
报错
``` shell 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/swift/cli/rlhf.py", line 5, in <module>
    rlhf_main()
  File "/usr/local/lib/python3.10/site-packages/swift/utils/run_utils.py", line 22, in x_main
    args, remaining_argv = parse_args(args_class, argv)
  File "/usr/local/lib/python3.10/site-packages/swift/utils/utils.py", line 131, in parse_args
    args, remaining_args = parser.parse_args_into_dataclasses(argv, return_remaining_strings=True)
  File "/usr/local/lib/python3.10/site-packages/transformers/hf_argparser.py", line 339, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 238, in __init__
  File "/usr/local/lib/python3.10/site-packages/swift/llm/utils/argument.py", line 1793, in __post_init__
    super().__post_init__()
  File "/usr/local/lib/python3.10/site-packages/swift/llm/utils/argument.py", line 1151, in __post_init__
    self._init_training_args()
  File "/usr/local/lib/python3.10/site-packages/swift/llm/utils/argument.py", line 1203, in _init_training_args
    training_args = training_args_cls(
TypeError: 'NoneType' object is not callable
```

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
CUDA 12.2
GPU A100 40G x 8
torch 2.4.0

**Additional context**
Add any other context about the problem here(在这里补充其他信息)
暂无其他，拉取的最新版本

**Comment by JiaXinLI98** [comment]
您好请问您是如何解决的呢，我也是出的这个问题

**Comment by xuhzyy** [comment]
@guru4elephant @JiaXinLI98 遇到同样的问题，请问你们是怎么解决的呢？
