### ISSUE TITLE
NotImplementedError: data_seed requires Accelerate version `accelerate` >= 1.1.0. This is not supported and we recommend you to update your version.

### ISSUE THREAD

**Issue by jiabao-wang** [modelscope/ms-swift#2339]
**Describe the bug**
when run:
CUDA_VISIBLE_DEVICES=0 swift sft \
    --model_type deepseek-vl-7b-chat \
    --dataset coco-en-mini \

output:
NotImplementedError: data_seed requires Accelerate version `accelerate` >= 1.1.0. This is not supported and we recommend you to update your version.(描述bug以及复现过程，最好有截图)

But the funny thing is that the highest version of Accelerate  is 1.0.1

### so what should i do?

detail output:
run sh: `/home/wjb/anaconda3/envs/sd/bin/python /home/wjb/anaconda3/envs/sd/lib/python3.9/site-packages/swift/cli/sft.py --model_type deepseek-vl-1_3b-chat --dataset coco-en-mini`
[INFO:swift] Successfully registered `/home/wjb/anaconda3/envs/sd/lib/python3.9/site-packages/swift/llm/data/dataset_info.json`
[INFO:swift] No vLLM installed, if you are using vLLM, you will get `ImportError: cannot import name 'get_vllm_engine' from 'swift.llm'`
[INFO:swift] No LMDeploy installed, if you are using LMDeploy, you will get `ImportError: cannot import name 'prepare_lmdeploy_engine_template' from 'swift.llm'`
[INFO:swift] Start time of running main: 2024-10-25 15:16:55.796605
[INFO:swift] Setting template_type: deepseek-vl
[INFO:swift] Setting args.lazy_tokenize: True
[INFO:swift] Setting args.dataloader_num_workers: 1
Traceback (most recent call last):
  File "/home/wjb/anaconda3/envs/sd/lib/python3.9/site-packages/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/home/wjb/anaconda3/envs/sd/lib/python3.9/site-packages/swift/utils/run_utils.py", line 22, in x_main
    args, remaining_argv = parse_args(args_class, argv)
  File "/home/wjb/anaconda3/envs/sd/lib/python3.9/site-packages/swift/utils/utils.py", line 131, in parse_args
    args, remaining_args = parser.parse_args_into_dataclasses(argv, return_remaining_strings=True)
  File "/home/wjb/anaconda3/envs/sd/lib/python3.9/site-packages/transformers/hf_argparser.py", line 352, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 215, in __init__
  File "/home/wjb/anaconda3/envs/sd/lib/python3.9/site-packages/swift/llm/utils/argument.py", line 1151, in __post_init__
    self._init_training_args()
  File "/home/wjb/anaconda3/envs/sd/lib/python3.9/site-packages/swift/llm/utils/argument.py", line 1203, in _init_training_args
    training_args = training_args_cls(
  File "<string>", line 144, in __init__
  File "/home/wjb/anaconda3/envs/sd/lib/python3.9/site-packages/swift/trainers/arguments.py", line 39, in __post_init__
    super().__post_init__()
  File "/home/wjb/anaconda3/envs/sd/lib/python3.9/site-packages/transformers/training_args.py", line 2083, in __post_init__
    raise NotImplementedError(
NotImplementedError: data_seed requires Accelerate version `accelerate` >= 1.1.0. This is not supported and we recommend you to update your version.

**Comment by thonglv21** [comment]
Same issue

**Comment by jiabao-wang** [comment]
@Jintao-Huang help! thank you very much.

**Comment by thonglv21** [comment]
try `transformers==4.40.0`

> Same issue

**Comment by lzuliuyu** [comment]
Same issue

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/pull/2341

**Comment by lzuliuyu** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by vencentDebug** [comment]
pip install --upgrade accelerate
