### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused')

### ISSUE THREAD

**Issue by HMacro** [modelscope/ms-swift#2353]
Traceback (most recent call last):
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/http/client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/http/client.py", line 1058, in _send_output
    self.send(msg)
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/http/client.py", line 996, in send
    self.connect()
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd0adeec190>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0adeec190>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/blocks.py", line 2018, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/blocks.py", line 1579, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/utils.py", line 691, in async_iteration
    return await anext(iterator)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/utils.py", line 685, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/utils.py", line 668, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/gradio/utils.py", line 829, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "/data/dyh/llama3.2/swift/swift/ui/llm_infer/llm_infer.py", line 492, in send_message
    stream_resp = inference_client(
                  ^^^^^^^^^^^^^^^^^
  File "/data/dyh/llama3.2/swift/swift/llm/utils/client_utils.py", line 292, in inference_client
    model_list = get_model_list_client(host, port, api_key=api_key, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/llama3.2/swift/swift/llm/utils/client_utils.py", line 37, in get_model_list_client
    resp_obj = requests.get(url, **_get_request_kwargs(api_key)).json()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dyh/anaconda3/envs/swift/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0adeec190>: Failed to establish a new connection: [Errno 111] Connection refused'))

在进行推理的时候报错了，请问这个出现的原因是什么呢

**Comment by YangningLi1** [comment]
Hello 请问你是怎么解决的呀
