### ISSUE TITLE
QLORA 微调 qwen2-audio-7b-instruct 报错。

### ISSUE THREAD

**Issue by Liufeiran123** [modelscope/ms-swift#2369]
Traceback (most recent call last):
  File "/mnt/d/ai/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/mnt/d/ai/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/mnt/d/ai/swift/swift/llm/sft.py", line 542, in llm_sft
    return trainer_train(args, model, template, train_dataset, val_dataset, callbacks=callbacks, msg=msg)
  File "/mnt/d/ai/swift/swift/llm/sft.py", line 492, in trainer_train
    trainer.train(training_args.resume_from_checkpoint)
  File "/mnt/d/ai/swift/swift/trainers/mixin.py", line 480, in train
    res = super().train(resume_from_checkpoint, *args, **kwargs)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/transformers/trainer.py", line 2052, in train
    return inner_training_loop(
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/transformers/trainer.py", line 2388, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/transformers/trainer.py", line 3485, in training_step
    loss = self.compute_loss(model, inputs)
  File "/mnt/d/ai/swift/swift/trainers/trainers.py", line 161, in compute_loss
    outputs = model(**inputs)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1603, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 823, in forward
    return model_forward(*args, **kwargs)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 811, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 43, in decorate_autocast
    return func(*args, **kwargs)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/peft/peft_model.py", line 1577, in forward
    return self.base_model(
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 188, in forward
    return self.model.forward(*args, **kwargs)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/transformers/models/qwen2_audio/modeling_qwen2_audio.py", line 1210, in forward
    inputs_embeds, attention_mask, labels, position_ids, _ = self._merge_input_ids_with_audio_features(
  File "/mnt/d/envs_swift/lib/python3.10/site-packages/transformers/models/qwen2_audio/modeling_qwen2_audio.py", line 1108, in _merge_input_ids_with_audio_features
    final_embedding[audio_to_overwrite] = (
RuntimeError: Index put requires the source and destination dtypes match, got BFloat16 for the destination and Float for the source.

执行的命令如下：
swift sft  --model_type qwen2-audio-7b-instruct     --dataset /mnt/c/Users/zybx/Downloads/audio_train.jsonl  --model_id_or_path /mnt/c/models/Qwen2-Audio-7B-Instruct/  --output_dir /mnt/d/ai/pretrain_models/qwen2-audio-7b-instruct-int4-sft --target_regex '^language_model(?!.*(lm_head|output|emb|wte|shared)).*' --gradient_accumulation_steps 8 --sft_type lora  --quant_method bnb --quantization_bit 4

包版本
transformers 4.45.2

**Comment by slin000111** [comment]
> Index put requires the source and destination dtypes match, got BFloat16 for the destination and Float for the source.

加上`--torch_dtype bfloat16`试试
下面的环境中测试是正常的
```text
transformers                             4.48.0
peft                                     0.15.0
ms_swift                                 3.8.0.dev0

```
