### ISSUE TITLE
ValueError: The number of image start tokens and image end tokens should be the same.

### ISSUE THREAD

**Issue by Anindyadeep** [modelscope/ms-swift#2381]
I have been fine-tuning the model for document ocr (for a different language) and getting some error like this:

```
ValueError: The number of image start tokens and image end tokens should be the same.
```

Now this was the data preparation script I used:

```python 
import os
import json

def get_sorted_files(folder_path):
    files = os.listdir(folder_path)
    
    png_files = sorted([os.path.join(os.getcwd(), folder_path, f) for f in files if f.endswith('.png')])
    txt_files = sorted([os.path.join(os.getcwd(), folder_path, f) for f in files if f.endswith('.txt')])
    
    file_pairs = list(zip(png_files, txt_files))
    
    return file_pairs

folder_path = "text_chunks"
file_pairs = get_sorted_files(folder_path)

data = []
for i, (png_file, txt_file) in enumerate(file_pairs):
    with open(txt_file, 'r', encoding='utf-8') as f: 
        text_content = f.read().strip() 
        data.append({
            "query": "\nOCR",
            "response": text_content,
            "images": [png_file]
        })

with open('training_data_got.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Done ...")
```

And this is how ran the model:

```bash
CUDA_VISIBLE_DEVICES=0,1 \
NPROC_PER_NODE=2 \
swift sft \
    --model_type got-ocr2 \
    --model_id_or_path stepfun-ai/GOT-OCR2_0 \
    --dataset "./training_data_got.json" \
    --num_train_epochs 5 \
    --sft_type lora \
    --output_dir output \
    --max_length 4096 \
    --batch_size 4 \
    --learning_rate 1e-4 
```

Now this is happening in the 1280th iteration, before that everything was fine

```bash
Train:  12%|██████▎                                             | 1280/10575 [18:19<1:59:10,  1.30it/s]
[rank0]: Traceback (most recent call last):                                                            
[rank0]:   File "/root/anaconda3/envs/qwen/lib/python3.11/site-packages/swift/cli/sft.py", line 5, in 
<module>                                                                                               
[rank0]:     sft_main()                                                                                
[rank0]:   File "/root/anaconda3/envs/qwen/lib/python3.11/site-packages/swift/utils/run_utils.py", lin
e 32, in x_main                                                                                        
[rank0]:     result = llm_x(args, **kwargs)                                                            
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^                                                            
[rank0]:   File "/root/anaconda3/envs/qwen/lib/python3.11/site-packages/swift/llm/sft.py", line 545, i
n llm_sft                                                                                              
[rank0]:     return trainer_train(args, model, template, train_dataset, val_dataset, callbacks=callback
s, msg=msg)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/qwen/lib/python3.11/site-packages/swift/llm/sft.py", line 495, i
n trainer_train
[rank0]:     trainer.train(training_args.resume_from_checkpoint)
[rank0]:   File "/root/anaconda3/envs/qwen/lib/python3.11/site-packages/swift/trainers/mixin.py", line
 488, in train
[rank0]:     res = super().train(resume_from_checkpoint, *args, **kwargs)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/qwen/lib/python3.11/site-packages/transformers/trainer.py", line
 1948, in train
[rank0]:     return inner_training_loop(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/qwen/lib/python3.11/site-packages/transformers/trainer.py", line
 2289, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/qwen/lib/python3.11/site-packages/transformers/trainer.py", line
 3328, in training_step
[rank0]:     loss = self.compute_loss(model, inputs)
```

How should I resolve the error.

**Comment by Jintao-Huang** [comment]
This issue is quite frustrating. Please check the dataset to see if there are any <img> tags.

**Comment by Anindyadeep** [comment]
So the solution was to remove all the `<img>`, `</img> tags in the text corpus.
