### ISSUE TITLE
sharegpt格式的dpo数据集该如何注册

### ISSUE THREAD

**Issue by ex-yanminmin001** [modelscope/ms-swift#2404]
数据格式为：
{
    "conversations": [
      {
        "from": "human",
        "value": "lets work on a business plan for a business that provides services to individuals or organizations planning women's retreats"
      },
      {
        "from": "gpt",
        "value": "I. Executive Summary\n\nRecharge Retreats is a full-service retreat planning company, specializing in creating unforgettable and empowering women's retreats for individuals and organizations. Our mission is to provide seamless planning, organization, and execution of transformative retreats that foster personal growth, well-being, and connection among women.\n\nII. Company Overview\n\nA. Company Name: Recharge Retreats\n\nB. Company Structure: Limited Liability Company (LLC)\n\nC. Founders: [Your Name(s) & Relevant Experience]\n\nD. Location: [City, State]\n\nIII. Services Offered\n\nA. Custom Retreat Planning: We will work closely with clients to design and plan retreats tailored to their specific needs and objectives.\n\nB. Venue & Accommodation Booking: We will secure the perfect venue and accommodations for each retreat, ensuring a comfortable and inspiring environment.\n\nC. Activity Coordination: We will arrange a variety of workshops, seminars, and recreational activities, such as yoga, meditation, team-building exercises, and creative workshops.\n\nD. Guest Speakers & Facilitators: We will source and coordinate with expert guest speakers and facilitators, aligned with the retreat's theme and objectives.\n\nE. Catering & Meal Planning: We will arrange for healthy, delicious, and customizable meal options, accommodating dietary restrictions and preferences.\n\nF. Marketing & Promotion: We will assist clients in promoting their retreats through various channels, including social media, email marketing, and strategic partnerships.\n\nG. Budget Management: We will manage the retreat's budget and ensure that all expenses are carefully planned and monitored.\n\nIV. Market Analysis\n\nA. Target Market: Our target market includes:\n1. Women-focused organizations and businesses\n2. Wellness and personal development groups\n3. Women's networking and professional associations\n4. Individual women seeking to organize retreats for friends or interest-based groups\n\nB. Market Trends:\n1. Growing interest in wellness and self-care\n2. Increased demand for women's empowerment and networking opportunities\n3. A desire for unique and transformative experiences\n\nC. Competitor Analysis: [List and analyze your main competitors]\n\nV. Marketing & Sales Strategy\n\nA. Branding: Establish a strong, unique, and recognizable brand identity that reflects the values and mission of Recharge Retreats.\n\nB. Website: Create a visually appealing and user-friendly website that showcases our services, client testimonials, and past retreats.\n\nC. Social Media: Engage with our target audience through social media platforms, such as Instagram, Facebook, and LinkedIn.\n\nD. Networking & Partnerships: Forge strategic partnerships with women's organizations, wellness providers, and influencers in our target market.\n\nE. Email Marketing: Build an email list and create regular newsletters to keep subscribers informed about upcoming retreats and events.\n\nF. Public Relations: Leverage media coverage and guest blogging opportunities to increase our visibility and credibility.\n\nVI. Operations & Management\n\nA. Team Structure: Define roles and responsibilities for the management team, including sales and marketing, retreat planning, and operations.\n\nB. Workflow & Processes: Establish efficient systems and processes to ensure smooth and timely execution of retreat planning tasks.\n\nC. Client Relationship Management: Implement a CRM system to manage client information and communication effectively.\n\nVII. Financial Projections\n\nA. Revenue Streams: Outline expected revenue streams, such as retreat planning fees, commissions, and partnerships.\n\nB. Expenses: Estimate ongoing expenses, including salaries, office space, marketing, and travel costs.\n\nC. Break-Even Analysis: Calculate the break-even point to determine when Recharge Retreats will become profitable.\n\nD. Cash Flow Projections: Provide a detailed cash flow forecast, including anticipated revenue and expenses, to ensure financial stability.\n\nVIII. Future Growth & Expansion\n\nA. Scaling"
      },
      {
        "from": "human",
        "value": "continue"
      }
    ],
    "chosen": {
      "from": "gpt",
      "value": "As Recharge Retreats grows, we plan to expand our team with additional event coordinators and marketing specialists. To accommodate this growth, we will establish an office space that fosters collaboration and creativity among team members. We will also prioritize remote work options and streamlined communication tools to support remote team members.\n\nIn addition, we aim to diversify our retreat offerings to cater to different themes, such as solo travel retreats, wellness retreats for parents, and spiritual journeys. We will seek to partner with multiple venues across various locations worldwide to provide a diverse range of retreat experiences.\n\nWe will also expand our marketing efforts to reach a wider audience, maximizing brand exposure through influencer partnerships, experiential marketing, and virtual events. We will continuously strive to refine our services based on client feedback and identify industry trends to adapt our offerings to the ever-changing needs and preferences of our target market.\n\nAs we scale, we will remain committed to upholding our mission to empower and connect women through transformative retreat experiences that prioritize personal growth, wellness, and connection."
    },
    "rejected": {
      "from": "gpt",
      "value": "A. Scaling:\n\n1. Offer a franchise model: Allow others to open and operate Recharge Retreats franchises in different regions, expanding our reach and revenue potential.\n2. Develop online courses and coaching programs: Create supplementary income streams by offering training and support to individuals and organizations interested in organizing their own retreats.\n\nB. Diversification:\n\n1. Expand service offerings: Consider adding additional retreat-related services, such as coaching, ongoing support, retreat evaluation, or retreat financing options.\n2. Target new markets: Broadening our target market to include other demographics, such as men, families, or specific interest groups.\n\nC. International Expansion:\n\n1. Partner with local organizations: Collaborate with women's organizations abroad to plan international retreats and expand our global presence.\n2. Seek funding opportunities: Pursue grants, investments, and loans to finance international retreats and support expansion in new markets.\n\nBy following this business plan, Recharge Retreats has the potential to become a leading provider of women's retreat services, empowering individuals and organizations to foster growth, connection, and personal transformation through memorable and life-enhancing experiences."
    }
  },
修改的dataset_info.json为：
 "dpo_en": {
        "dataset_id": "./data/dpo_en.json",
        "columns":{
            "conversations": {
            "user_role": "human",
            "assistant_role": "gpt",
            "conversations_key": "conversations",
            "from_key": "from",
            "value_key": "value"
            },
            "chosen": "chosen",
            "rejected": "rejected"
        }    
    }
训练命令为：
 CUDA_VISIBLE_DEVICES=1 swift rlhf     --rlhf_type dpo     --model_type qwen2-7b-instruct     --model_id_or_path   /LLMs/Qwen2-7B-Instruct/      --dataset dpo_en     --num_train_epochs 1     --sft_type lora 
报错为：
Traceback (most recent call last):
  File "/workspace/ms-swift-main/swift/cli/rlhf.py", line 5, in <module>
    rlhf_main()
  File "/workspace/ms-swift-main/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/workspace/ms-swift-main/swift/llm/rlhf.py", line 45, in llm_rlhf
    train_dataset, val_dataset = prepare_dataset(args, template, msg)
  File "/workspace/ms-swift-main/swift/llm/sft.py", line 354, in prepare_dataset
    train_dataset, val_dataset = _get_train_val_dataset(args)
  File "/workspace/ms-swift-main/swift/llm/sft.py", line 32, in _get_train_val_dataset
    train_dataset, val_dataset = get_dataset(
  File "/workspace/ms-swift-main/swift/llm/utils/dataset.py", line 2924, in get_dataset
    dataset = get_function(
  File "/workspace/ms-swift-main/swift/llm/utils/dataset.py", line 494, in get_dataset_from_repo
    return _post_preprocess(dataset, dataset_sample, random_state, preprocess_func, dataset_test_ratio,
  File "/workspace/ms-swift-main/swift/llm/utils/dataset.py", line 464, in _post_preprocess
    dataset = preprocess_func(dataset)
  File "/workspace/ms-swift-main/swift/llm/utils/preprocess.py", line 386, in __call__
    dataset = dataset.rename_column(old_name, new_name)
  File "/usr/local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 602, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2285, in rename_column
    {
  File "/usr/local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2285, in <dictcomp>
    {
TypeError: unhashable type: 'dict'

**Comment by Jintao-Huang** [comment]
请查一下自定义数据集文档

**Comment by ex-yanminmin001** [comment]
> 请查一下自定义数据集文档

query = []
    response = []
    rejected_response = []
    history = []
    for d in dataset:
        temp = []
        history_temp = []
        # import pdb;pdb.set_trace()
        if len(d['conversations']) == 1:
            query.append(d["conversations"][0]["value"])
        if len(d['conversations']) > 1:
            query.append(d["conversations"][-1]["value"])
            for i in range(0, len(d['conversations'])-1, 2):
                temp.append(d['conversations'][i]['value'])
                temp.append(d['conversations'][i+1]['value'])
            history_temp.append(temp)
        history.append(history_temp)

        response.append(d['chosen']["value"])
        rejected_response.append(d['rejected']['value'])

    return HfDataset.from_dict({'query': query, 'response': response, 'rejected_response':rejected_response, 'history':history})
这么写好像也不行 能帮忙看看吗

**Comment by ex-yanminmin001** [comment]
> 请查一下自定义数据集文档

`query = []
    response = []
    rejected_response = []
    history = []
    for d in dataset:
        temp = []
        history_temp = []
        # import pdb;pdb.set_trace()
        if len(d['conversations']) == 1:
            query.append(d["conversations"][0]["value"])
        if len(d['conversations']) > 1:
            query.append(d["conversations"][-1]["value"])
            for i in range(0, len(d['conversations'])-1, 2):
                temp.append(d['conversations'][i]['value'])
                temp.append(d['conversations'][i+1]['value'])
            history_temp.append(temp)
        history.append(history_temp)

        response.append(d['chosen']["value"])
        rejected_response.append(d['rejected']['value'])

    return HfDataset.from_dict({'query': query, 'response': response, 'rejected_response':rejected_response, 'history':history})
`
这么写也不对，能帮忙看看吗？

**Comment by 1571859588** [comment]
你好，请问解决了吗，我发现文档似乎确实缺少了自定义数据集的细节，最近卡在这里，想取一下经

**Comment by slin000111** [comment]
> > 请查一下自定义数据集文档
> 
> `query = [] response = [] rejected_response = [] history = [] for d in dataset: temp = [] history_temp = [] # import pdb;pdb.set_trace() if len(d['conversations']) == 1: query.append(d["conversations"][0]["value"]) if len(d['conversations']) > 1: query.append(d["conversations"][-1]["value"]) for i in range(0, len(d['conversations'])-1, 2): temp.append(d['conversations'][i]['value']) temp.append(d['conversations'][i+1]['value']) history_temp.append(temp) history.append(history_temp)
> 
> ```
>     response.append(d['chosen']["value"])
>     rejected_response.append(d['rejected']['value'])
> 
> return HfDataset.from_dict({'query': query, 'response': response, 'rejected_response':rejected_response, 'history':history})
> ```
> 
> ` 这么写也不对，能帮忙看看吗？

写个python脚本转成下面这种格式
```json
{"messages": [{"role": "system", "content": "你是个有用无害的数学计算器"}, {"role": "user", "content": "1+1等于几"}, {"role": "assistant", "content": "等于2"}, {"role": "user", "content": "再加1呢"}, {"role": "assistant", "content": "等于3"}], "rejected_response": "我不知道"}
```
