### ISSUE TITLE
Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'

### ISSUE THREAD

**Issue by gaussiangit** [modelscope/ms-swift#2512]
CUDA_VISIBLE_DEVICES=0 swift sft --model_type florence-2-large-ft --num_train_epochs 10 --warmup_ratio 0.4 --batch_size 4 --dataset multi.json  --lora_target_modules ALL

> 
> Train:   0%|                                                                                     | 0/83650 [00:00<?, ?it/s][ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> {'loss': 3.96798348, 'acc': 0.45118481, 'grad_norm': 13.62348366, 'learning_rate': 0.0, 'memory(GiB)': 5.71, 'train_speed(iter/s)': 0.107963, 'epoch': 0.0, 'global_step/max_steps': '1/83650', 'percentage': '0.00%', 'elapsed_time': '9s', 'remaining_time': '8d 17h 17m 0s'}
> Train:   0%|                                                                         | 1/83650 [00:09<209:13:50,  9.00s/it][ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> Train:   0%|                                                                         | 2/83650 [00:13<148:26:43,  6.39s/it][ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> Token indices sequence length is longer than the specified maximum sequence length for this model (1369 > 1024). Running this sequence through the model will result in indexing errors
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> Train:   0%|                                                                         | 3/83650 [00:18<135:13:57,  5.82s/it][ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> [ERROR:swift] Error occurs in lazy tokenize: unsupported operand type(s) for /: 'list' and 'int'
> ../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [3,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

**Comment by JHL328** [comment]
我之前有遇到相似的，我是由于继承问题导致的，你可以step in debug一下看看。我的解决方法在https://github.com/modelscope/ms-swift/issues/2409#issuecomment-2499862740

**Comment by JHL328** [comment]
还有可能是由于你的数据太长了，超过context window，要么在没报oom的情况下增大context window length这个参数，要么就删掉过长的数据

**Comment by JHL328** [comment]
希望我的解决方法对你有帮助

**Comment by gaussiangit** [comment]
Thanks! 
I fixed by flattening bboxes and setting max_length but now I get following 
```
`[INFO:swift] [INPUT_IDS] [0, 1185, 32, 10, 7163, 3167, 4, 50118, 50118, 48134, 3861, 35, 50118, 41552, 20094, 15698, 38195, 70, 8720, 50118, 50118, 48134, 6267, 35, 50118, 41552, 8304, 15698, 48395, 541, 2517, 4, 288, 6, 501, 1225, 4, 288, 6, 843, 5479, 4, 288, 6, 132, 25540, 4, 288, 7479, 646, 541, 3414, 4, 288, 6, 501, 3897, 4, 288, 6, 155, 29023, 4, 288, 6, 379, 4718, 4, 288, 7479, 646, 306, 30687, 4, 288, 6, 365, 2940, 4, 288, 6, 3550, 1244, 4, 288, 6, 508, 3272, 4, 288, 7479, 646, 1922, 5208, 4, 288, 6, 1132, 5046, 4, 288, 6, 706, 6617, 4, 288, 6, 389, 6551, 4, 288, 7479, 646, 1898, 6361, 4, 288, 6, 2993, 134, 4, 288, 6, 204, 39259, 4, 288, 6, 389, 6617, 4, 288, 7479, 646, 1922, 5067, 4, 288, 6, 290, 2890, 4, 288, 6, 706, 6232, 4, 288, 6, 361, 2022, 4, 288, 7479, 646, 2518, 1092, 4, 398, 27129, 26340, 4671, 2545, 6, 564, 3818, 4, 21070, 39356, 38588, 11338, 6, 971, 4280, 4, 38075, 4280, 22146, 6478, 2545, 6, 974, 612, 4, 1366, 4390, 6468, 2663, 4419, 1244, 7479, 646, 2518, 2518, 4, 38719, 2481, 4419, 1244, 6, 365, 2466, 4, 2940, 5677, 26758, 25534, 11338, 6, 971, 4718, 4, 4531, 541, 2518, 3079, 21353, 6, 8325, 406, 4, 39373, 4006, 31335, 4156, 21353, 48392, 49703, 8304, 15698, 2]
[INFO:swift] [INPUT] <s>You are a helpful assistant.

### Human:
<image>Find all objects

### Assistant:
<box> [[3028.0, 1411.0, 4078.0, 2167.0], [3049.0, 1443.0, 3184.0, 1577.0], [4272.0, 1180.0, 4425.0, 1337.0], [2398.0, 2989.0, 2492.0, 3082.0], [4583.0, 3001.0, 4672.0, 3092.0], [2376.0, 829.0, 2484.0, 935.0], [2712.81591796875, 2548.280517578125, 2866.628662109375, 2700.185791015625], [2727.697265625, 1160.8087158203125, 2877.85302734375, 1307.7484130859375]] </box></s>
[INFO:swift] [LABELS_IDS] [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 41552, 8304, 15698, 48395, 541, 2517, 4, 288, 6, 501, 1225, 4, 288, 6, 843, 5479, 4, 288, 6, 132, 25540, 4, 288, 7479, 646, 541, 3414, 4, 288, 6, 501, 3897, 4, 288, 6, 155, 29023, 4, 288, 6, 379, 4718, 4, 288, 7479, 646, 306, 30687, 4, 288, 6, 365, 2940, 4, 288, 6, 3550, 1244, 4, 288, 6, 508, 3272, 4, 288, 7479, 646, 1922, 5208, 4, 288, 6, 1132, 5046, 4, 288, 6, 706, 6617, 4, 288, 6, 389, 6551, 4, 288, 7479, 646, 1898, 6361, 4, 288, 6, 2993, 134, 4, 288, 6, 204, 39259, 4, 288, 6, 389, 6617, 4, 288, 7479, 646, 1922, 5067, 4, 288, 6, 290, 2890, 4, 288, 6, 706, 6232, 4, 288, 6, 361, 2022, 4, 288, 7479, 646, 2518, 1092, 4, 398, 27129, 26340, 4671, 2545, 6, 564, 3818, 4, 21070, 39356, 38588, 11338, 6, 971, 4280, 4, 38075, 4280, 22146, 6478, 2545, 6, 974, 612, 4, 1366, 4390, 6468, 2663, 4419, 1244, 7479, 646, 2518, 2518, 4, 38719, 2481, 4419, 1244, 6, 365, 2466, 4, 2940, 5677, 26758, 25534, 11338, 6, 971, 4718, 4, 4531, 541, 2518, 3079, 21353, 6, 8325, 406, 4, 39373, 4006, 31335, 4156, 21353, 48392, 49703, 8304, 15698, 2]
[INFO:swift] [LABELS] [-100 * 25]<box> [[3028.0, 1411.0, 4078.0, 2167.0], [3049.0, 1443.0, 3184.0, 1577.0], [4272.0, 1180.0, 4425.0, 1337.0], [2398.0, 2989.0, 2492.0, 3082.0], [4583.0, 3001.0, 4672.0, 3092.0], [2376.0, 829.0, 2484.0, 935.0], [2712.81591796875, 2548.280517578125, 2866.628662109375, 2700.185791015625], [2727.697265625, 1160.8087158203125, 2877.85302734375, 1307.7484130859375]] </box></s>
Map:   0%|                                                                                                                                                                                 | 0/133850 [00:00<?, ?it/s]Token indices sequence length is longer than the specified maximum sequence length for this model (1538 > 1024). Running this sequence through the model will result in indexing errors
Map:  22%|████████████████████████████████████▍     
```    

and then training fails with 
`Train:   0%|                                                                                                                                                                                 | 0/8365 [00:00<?, ?it/s]/home/u/miniconda3/envs/swift/lib/python3.11/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
Traceback (most recent call last):
  File "/home/u/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/home/u/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u/swift/swift/llm/sft.py", line 546, in llm_sft
    return trainer_train(args, model, template, train_dataset, val_dataset, callbacks=callbacks, msg=msg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u/swift/swift/llm/sft.py", line 496, in trainer_train
    trainer.train(training_args.resume_from_checkpoint)
  File "/home/u/swift/swift/trainers/mixin.py", line 493, in train
    res = super().train(resume_from_checkpoint, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/trainer.py", line 2123, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/u/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/trainer.py", line 2481, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/trainer.py", line 3612, in training_step
    self.accelerator.backward(loss, **kwargs)
  File "/home/u/miniconda3/envs/swift/lib/python3.11/site-packages/accelerate/accelerator.py", line 2241, in backward
    loss.backward(**kwargs)
  File "/home/u/miniconda3/envs/swift/lib/python3.11/site-packages/torch/_tensor.py", line 581, in backward
    torch.autograd.backward(
  File "/home/u/miniconda3/envs/swift/lib/python3.11/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/home/u/miniconda3/envs/swift/lib/python3.11/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
Train:   0%|         `

**Comment by z0o0ey** [comment]
please retry with latest swift and vllm, feel free to create a new issue if it the problem persists.
