### ISSUE TITLE
华为910B上推理Qwen2.5报错RuntimeError: call aclnnIndex failed, detail:EZ9999: Inner Error!

### ISSUE THREAD

**Issue by guihonghao** [modelscope/ms-swift#2517]
使用下面脚本进行推理时，报错RuntimeError: call aclnnIndex failed, detail:EZ9999: Inner Error!，但是推理glm4-9b的时候不会
```
export ASCEND_RT_VISIBLE_DEVICES=3
export ASCEND_LAUNCH_BLOCKING=1 
python3 examples/pytorch/llm/llm_infer.py \
    --model_type "qwen2_5-7b-instruct" \
    --model_id_or_path "/data1/guihonghao/models/Qwen2.5-7B-Instruct" \
    --ckpt_dir "/data1/guihonghao/lora_outputs/qwen2_5-7b-instruct-ie-v2/qwen2_5-7b-instruct/v9-20241125-193129/checkpoint-2158" \
    --val_dataset "/data1/guihonghao/data/test_data/IE-v2/test_zero.json" \
    --use_flash_attn false \
    --max_length 4000 \
    --do_sample false \
    --max_new_tokens 1024 \
    --show_dataset_sample -1 \
    --merge_lora true 
```
报错信息：
```
Traceback (most recent call last):
  File "/data1/guihonghao/ms-swift/examples/pytorch/llm/llm_infer.py", line 11, in <module>
    result = infer_main()
  File "/data1/guihonghao/ms-swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/data1/guihonghao/ms-swift/swift/llm/infer.py", line 475, in llm_infer
    response, _ = inference(
  File "/data1/guihonghao/anaconda3/envs/uie/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data1/guihonghao/ms-swift/swift/llm/utils/utils.py", line 869, in inference
    generate_ids = model.generate(streamer=streamer, generation_config=generation_config, **inputs)
  File "/data1/guihonghao/anaconda3/envs/uie/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/guihonghao/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2215, in generate
    result = self._sample(
  File "/home/guihonghao/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 3199, in _sample
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/home/guihonghao/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 387, in prepare_inputs_for_generation
    input_ids = input_ids[:, cache_position]
RuntimeError: call aclnnIndex failed, detail:EZ9999: Inner Error!
EZ9999  Tiling failed
        TraceBack (most recent call last):
        Tiling Failed.
        Kernel Run failed. opType: 117, Index
        launch failed for Index, errno:561103.

[ERROR] 2024-11-27-10:42:11 (PID:2463956, Device:0, RankID:-1) ERR01100 OPS call acl api failed
```

**Comment by jiaj12** [comment]
你确定你用的是910b吗

**Comment by Fengsbq** [comment]
怎么解决的呢

**Comment by co1dspring** [comment]
请问解决了吗？
