### ISSUE TITLE
"Too many 500 error responses" when trying to download model weights

### ISSUE THREAD

**Issue by sidyakinian** [modelscope/ms-swift#2539]
**Describe the bug**

As of Dec 3, when trying to download weights for any model, I get this issue (illustrated with `Qwen2-VL-7B-Instruct` but I've tried with other models as well):

```
Downloading Model to directory: /home/yans/.cache/modelscope/hub/qwen/Qwen2-VL-7B-Instruct
urllib3.exceptions.ResponseError: too many 500 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yans/ms-swift/.venv/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/yans/ms-swift/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
  File "/home/yans/ms-swift/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
  File "/home/yans/ms-swift/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 934, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/yans/ms-swift/.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/qwen/Qwen2-VL-7B-Instruct/repo/files?Revision=master&Recursive=True (Caused by ResponseError('too many 500 error responses'))
```

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

Linux VMs.

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by heylamourding** [comment]
+1

**Comment by yingdachen** [comment]
modelscope hub was experiencing abnormal traffic, it is now recovered back to normal. please reopen the issue if the problem still persisit on your end.
