### ISSUE TITLE
Internvl25-8B 是否不支持 lora微调？执行失败。本地已安装最新版ms-swift

### ISSUE THREAD

**Issue by evanlin88** [modelscope/ms-swift#2608]
**Describe the bug**
一：**sh脚本** ：
CUDA_VISIBLE_DEVICES=2,3 swift sft \
  --model_type internvl2_5 \
  --model /data/internvl25-8b/models/InternVL2_5-8B \
  --sft_type lora \
  --dataset /data/dataset/internvl25-8b-20241210-select/train_data.jsonl \
  --output_dir /data/internvl25-8b/swift-fine-tuning/output \
  --num_train_epochs 1 \
  --max_steps 1000 \
  --per_device_train_batch_size 1 \
  --gradient_accumulation_steps 4 \
  --learning_rate 2e-5 \
  --lora_rank 8 \
  --lora_alpha 32 \
  --lora_dropout 0.05 \
  --evaluation_strategy steps \
  --eval_steps 200 \
  --save_strategy steps \
  --save_steps 200

二：**Exception Info 异常信息**：ValueError: remaining_argv: ['--sft_type', 'lora']
Traceback (most recent call last):
  File "/data/ms-swift-internvl25/ms-swift-main/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/data/ms-swift-internvl25/ms-swift-main/swift/llm/train/sft.py", line 306, in sft_main
    return SwiftSft(args).main()
  File "/data/ms-swift-internvl25/ms-swift-main/swift/llm/train/sft.py", line 31, in __init__
    super().__init__(args)
  File "/data/ms-swift-internvl25/ms-swift-main/swift/llm/base.py", line 18, in __init__
    self.args = self._parse_args(args)
  File "/data/ms-swift-internvl25/ms-swift-main/swift/llm/base.py", line 32, in _parse_args
    raise ValueError(f'remaining_argv: {remaining_argv}')
ValueError: remaining_argv: ['--sft_type', 'lora']

**Your hardware and system info**
ms-swift                      3.0.0.dev0
transformers                  4.46.3
torch                         2.5.1

**Comment by Jeremy-J-J** [comment]
--model_type internvl2-8b

**Comment by evanlin88** [comment]
> --model_type internvl2-8b

将--sft_type lora 换成 --train_type lora
