### ISSUE TITLE
多模态模型测试报错：Input type (torch.cuda.FloatTensor) and weight type (CUDABFloat16Type) should be the same

### ISSUE THREAD

**Issue by Polarisamoon** [modelscope/ms-swift#2622]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
运行
```
swift eval \
  --model AI-ModelScope/paligemma-3b-mix-224 \
  --eval_limit 10 \
  --eval_dataset MME \
```
报错:
```
INFO:     127.0.0.1:53392 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
[2024-12-11 09:53:15,862] ERROR - ChatAPI - gpt.py: generate_inner - 218: <class 'json.decoder.JSONDecodeError'>: Expecting value: line 1 column 1 (char 0)
2024-12-11 09:53:15,862 - ChatAPI - ERROR - <class 'json.decoder.JSONDecodeError'>: Expecting value: line 1 column 1 (char 0)
[2024-12-11 09:53:15,862] ERROR - ChatAPI - gpt.py: generate_inner - 219: Internal Server Error
2024-12-11 09:53:15,862 - ChatAPI - ERROR - Internal Server Error
[2024-12-11 09:53:15,862] INFO - ChatAPI - base.py: generate - 256: RetCode: 500
Answer: Failed to obtain answer via API.
Log: Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/llm/ms-swift/swift/llm/infer/deploy.py", line 143, in create_chat_completion
    res_or_gen = await self.infer_async(infer_request, request_config, template=self.template)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/llm/ms-swift/swift/llm/infer/infer_engine/pt_engine.py", line 307, in infer_async
    res_or_gen = self.infer([infer_request],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/llm/ms-swift/swift/llm/infer/infer_engine/pt_engine.py", line 410, in infer
    res += self._infer(
           ^^^^^^^^^^^^
  File "/home/longchen/llm/ms-swift/swift/llm/infer/infer_engine/pt_engine.py", line 370, in _infer
    return self._update_metrics(self._infer_full(**kwargs), metrics)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/llm/ms-swift/swift/llm/infer/infer_engine/pt_engine.py", line 262, in _infer_full
    output = dict(self.model.generate(**generate_kwargs))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/generation/utils.py", line 2215, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/generation/utils.py", line 3206, in _sample
    outputs = self(**model_inputs, return_dict=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/models/paligemma/modeling_paligemma.py", line 496, in forward
    image_features = self.get_image_features(pixel_values)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/models/paligemma/modeling_paligemma.py", line 405, in get_image_features
    image_outputs = self.vision_tower(pixel_values)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/models/siglip/modeling_siglip.py", line 1190, in forward
    return self.vision_model(
           ^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/models/siglip/modeling_siglip.py", line 1089, in forward
    hidden_states = self.embeddings(pixel_values, interpolate_pos_encoding=interpolate_pos_encoding)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/models/siglip/modeling_siglip.py", line 311, in forward
    patch_embeds = self.patch_embedding(pixel_values)  # shape = [*, width, grid, grid]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
**RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (CUDABFloat16Type) should be the same**
```

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here (在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
ms-swift                      3.0.0.dev0  
transformers                  4.46.3
Platform: Linux-6.8.0-47-generic-x86_64-with-glibc2.35
PyTorch version: 2.5.1+cu124 (GPU)
GPU type: NVIDIA GeForce RTX 3090

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by CLL112** [comment]
测试在```MMMU_DEV_VAL```上也报相同的错误，我没有修改任何代码

**Comment by slin000111** [comment]
> **Describe the bug** What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图) 运行
> 
> ```
> swift eval \
>   --model AI-ModelScope/paligemma-3b-mix-224 \
>   --eval_limit 10 \
>   --eval_dataset MME \
> ```
> 
> 报错:
> 
> ```
> INFO:     127.0.0.1:53392 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
> [2024-12-11 09:53:15,862] ERROR - ChatAPI - gpt.py: generate_inner - 218: <class 'json.decoder.JSONDecodeError'>: Expecting value: line 1 column 1 (char 0)
> 2024-12-11 09:53:15,862 - ChatAPI - ERROR - <class 'json.decoder.JSONDecodeError'>: Expecting value: line 1 column 1 (char 0)
> [2024-12-11 09:53:15,862] ERROR - ChatAPI - gpt.py: generate_inner - 219: Internal Server Error
> 2024-12-11 09:53:15,862 - ChatAPI - ERROR - Internal Server Error
> [2024-12-11 09:53:15,862] INFO - ChatAPI - base.py: generate - 256: RetCode: 500
> Answer: Failed to obtain answer via API.
> Log: Internal Server Error
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
>     return await self.app(scope, receive, send)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
>     await super().__call__(scope, receive, send)
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
>     raise exc
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
>     await self.app(scope, receive, _send)
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
>     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     raise exc
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
>     await app(scope, receive, sender)
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
>     await route.handle(scope, receive, send)
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
>     await self.app(scope, receive, send)
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
>     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     raise exc
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
>     await app(scope, receive, sender)
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
>     response = await f(request)
>                ^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
>     raw_response = await run_endpoint_function(
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
>     return await dependant.call(**values)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/llm/ms-swift/swift/llm/infer/deploy.py", line 143, in create_chat_completion
>     res_or_gen = await self.infer_async(infer_request, request_config, template=self.template)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/llm/ms-swift/swift/llm/infer/infer_engine/pt_engine.py", line 307, in infer_async
>     res_or_gen = self.infer([infer_request],
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/llm/ms-swift/swift/llm/infer/infer_engine/pt_engine.py", line 410, in infer
>     res += self._infer(
>            ^^^^^^^^^^^^
>   File "/home/longchen/llm/ms-swift/swift/llm/infer/infer_engine/pt_engine.py", line 370, in _infer
>     return self._update_metrics(self._infer_full(**kwargs), metrics)
>                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/llm/ms-swift/swift/llm/infer/infer_engine/pt_engine.py", line 262, in _infer_full
>     output = dict(self.model.generate(**generate_kwargs))
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/generation/utils.py", line 2215, in generate
>     result = self._sample(
>              ^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/generation/utils.py", line 3206, in _sample
>     outputs = self(**model_inputs, return_dict=True)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/accelerate/hooks.py", line 170, in new_forward
>     output = module._old_forward(*args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/models/paligemma/modeling_paligemma.py", line 496, in forward
>     image_features = self.get_image_features(pixel_values)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/models/paligemma/modeling_paligemma.py", line 405, in get_image_features
>     image_outputs = self.vision_tower(pixel_values)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/models/siglip/modeling_siglip.py", line 1190, in forward
>     return self.vision_model(
>            ^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/models/siglip/modeling_siglip.py", line 1089, in forward
>     hidden_states = self.embeddings(pixel_values, interpolate_pos_encoding=interpolate_pos_encoding)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/accelerate/hooks.py", line 170, in new_forward
>     output = module._old_forward(*args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/transformers/models/siglip/modeling_siglip.py", line 311, in forward
>     patch_embeds = self.patch_embedding(pixel_values)  # shape = [*, width, grid, grid]
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/accelerate/hooks.py", line 170, in new_forward
>     output = module._old_forward(*args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 554, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/longchen/miniconda3/envs/swift/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
>     return F.conv2d(
>            ^^^^^^^^^
> **RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (CUDABFloat16Type) should be the same**
> ```
> 
> **Your hardware and system info** Write your system info like CUDA version/system/GPU/torch version here (在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等) ms-swift 3.0.0.dev0 transformers 4.46.3 Platform: Linux-6.8.0-47-generic-x86_64-with-glibc2.35 PyTorch version: 2.5.1+cu124 (GPU) GPU type: NVIDIA GeForce RTX 3090
> 
> **Additional context** Add any other context about the problem here(在这里补充其他信息)

可能是transformers版本的原因，参考这个[#issue](https://github.com/deepspeedai/DeepSpeed/issues/1327)
也可以试试ms-swift升级到最新版本，transformers升级到4.51.3
