### ISSUE TITLE
qwen2_vl_7b  SFT 加载数据报错。

### ISSUE THREAD

**Issue by CoderXiaopang** [modelscope/ms-swift#2623]
12.11.8:00    ----------->            pull 

## 执行命令

swift sft \
    --model /root/autodl-tmp/modelscope/hub/Qwen/Qwen2-VL-7B-Instruct \
    --dataset /root/autodl-tmp/train_VL.jsonl \
    --output_dir output \
    --model_type qwen2_vl \
    --train_type lora \
    --max_length 2048 \
    --per_device_train_batch_size 1 \
    --gradient_checkpointing True \
    --lazy_tokenize True \
    --check_model True \
    --num_train_epochs 10 \
    --truncation_strategy delete \
    --save_strategy steps \
    --save_steps 50 \
    --save_total_limit 10 \
    --eval_strategy steps \
    --eval_steps 50 \
    --save_only_model False

## 数据集组织形式
{"query":"XXXXXX","response":"XXXXX","images":["/root/xxxxxx.jpg","/root/xxxxx.jpg"]}
{"query":"XXXXXX","response":"XXXXX","images":["/root/xxxxxx.jpg","/root/xxxxx.jpg"]}
{"query":"XXXXXX","response":"XXXXX","images":["/root/xxxxxx.jpg","/root/xxxxx.jpg"]}
{"query":"XXXXXX","response":"XXXXX","images":["/root/xxxxxx.jpg","/root/xxxxx.jpg"]}
.......

## 报错信息
``` bash
Train:   0%|                                          | 0/41370 [00:00<?, ?it/s][WARNING:swift] Current length of row(2792) is larger than the max_length(2048), deleted.
Traceback (most recent call last):
  File "/root/ms-swift/swift/cli/sft_rewrite.py", line 49, in <module>
    run_sft()
  File "/root/ms-swift/swift/cli/sft_rewrite.py", line 42, in run_sft
    result = sft_main(args)
             ^^^^^^^^^^^^^^
  File "/root/ms-swift/swift/llm/train/sft.py", line 299, in sft_main
    return SwiftSft(args).main()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/ms-swift/swift/llm/base.py", line 45, in main
    result = self.run()
             ^^^^^^^^^^
  File "/root/ms-swift/swift/llm/train/sft.py", line 166, in run
    return self.train(trainer)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/ms-swift/swift/llm/train/sft.py", line 218, in train
    trainer.train(trainer.args.resume_from_checkpoint)
  File "/root/ms-swift/swift/trainers/mixin.py", line 240, in train
    return super().train(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/transformers/trainer.py", line 2123, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/transformers/trainer.py", line 2481, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/transformers/trainer.py", line 3573, in training_step
    inputs = self._prepare_inputs(inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/transformers/trainer.py", line 3524, in _prepare_inputs
    f"training dataset contains keys expected by the model: {','.join(self._signature_columns)}."
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can only join an iterable

```

**Comment by Jintao-Huang** [comment]
换个seed看看，感觉是有条数据有点问题

比如不含labels

**Comment by gzhuinjune** [comment]
> {"query":"XXXXXX","response":"XXXXX","images":["/root/xxxxxx.jpg","/root/xxxxx.jpg"]}
> {"query":"XXXXXX","response":"XXXXX","images":["/root/xxxxxx.jpg","/root/xxxxx.jpg"]}
> {"query":"XXXXXX","response":"XXXXX","images":["/root/xxxxxx.jpg","/root/xxxxx.jpg"]}
> {"query":"XXXXXX","response":"XXXXX","images":["/root/xxxxxx.jpg","/root/xxxxx.jpg"]}

哥们，请问可以提供qwen-2vl的微调实践的文档吗，已经看不到了，谢谢您

**Comment by Jintao-Huang** [comment]
https://swift2x.readthedocs.io/zh-cn/latest/

**Comment by ltqqq** [comment]
朋友，请问你现在能找到办法定位到是哪条数据有问题吗

**Comment by z0o0ey** [comment]
please retry with latest swift and vllm, feel free to create a new issue if it the problem persists.
