### ISSUE TITLE
3.0 SFT&DPO InternVL2d5 meets some problems

### ISSUE THREAD

**Issue by bonre** [modelscope/ms-swift#2646]
叨扰贵组了！
这是之前两个问题的再提，因为issue不知道为啥看不到了。
第一个问题的报错信息：
```
Traceback (most recent call last):
[rank5]:   File "/home/workspace/InternVL_2d5/package/swift/swift/cli/rlhf.py", line 5, in <module>
[rank5]:     rlhf_main()
[rank5]:   File "/home/workspace/InternVL_2d5/package/swift/swift/llm/train/rlhf.py", line 61, in rlhf_main
[rank5]:     return SwiftRLHF(args).main()
[rank5]:   File "/home/workspace/InternVL_2d5/package/swift/swift/llm/base.py", line 45, in main
[rank5]:     result = self.run()
[rank5]:   File "/home/workspace/InternVL_2d5/package/swift/swift/llm/train/sft.py", line 166, in run
[rank5]:     return self.train(trainer)
[rank5]:   File "/home/workspace/InternVL_2d5/package/swift/swift/llm/train/sft.py", line 218, in train
[rank5]:     trainer.train(trainer.args.resume_from_checkpoint)
[rank5]:   File "/home/workspace/InternVL_2d5/package/swift/swift/trainers/mixin.py", line 229, in train
[rank5]:     if self.model.model_meta.is_multimodal:
[rank5]:   File "/home/workspace/InternVL_2d5/package/swift/swift/trainers/rlhf_trainer/rlhf_mixin.py", line 30, in __getattr__
[rank5]:     return super().__getattr__(key)
[rank5]:   File "/home/anaconda3/envs/swift3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
[rank5]:     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[rank5]: AttributeError: 'ModelWrapper' object has no attribute 'model_meta'
```
发生在DPO的时候，DPO的shell代码如下：
```
NPROC_PER_NODE=8 \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
swift rlhf \
    --rlhf_type dpo \
    --model /data/InternVL2d5/experience_2412/Full_1211_tar/v1-20241211-171915/checkpoint-2000 \
    --model_type 'internvl2_5' \
    --ref_model /data/InternVL2d5/experience_2412/Full_1211_tar/v1-20241211-171915/checkpoint-2000 \
    --ref_model_type 'internvl2_5' \
    --output_dir ${OUTPUT_DIR} \
    --torch_dtype 'bfloat16' \
    --beta 0.1 \
    --label_smoothing 0.1 \
    --rpo_alpha 0.5 \
    --dataset /home/workspace/InternVL_2d5/data/dpo/1212_v0.jsonl \
    --split_dataset_ratio 0 \
    --num_train_epochs  1  \
    --train_type  full \
    --freeze_vit true \
    --gradient_checkpointing  true  \
    --gradient_checkpointing_kwargs '{"use_reentrant": false}' \
    --attn_impl 'flash_attn' \
    --per_device_train_batch_size 1 \
    --learning_rate  5e-6  \
    --gradient_accumulation_steps  4  \
    --warmup_ratio  0.01  \
    --max_length 8192 \
    --save_total_limit  2 \
    --save_strategy 'epoch' \
    --logging_steps 2 \
    --deepspeed zero3_offload \
    --save_only_model true \
    --logging_steps  5  > "${OUTPUT_DIR}/train.log" 2>&1
```

**Comment by bonre** [comment]
第二个报错是SFT的时候发生的：
对于这个报错：
```
Traceback (most recent call last):
  File "/home/workspace/InternVL_2d5/package/ms-swift-main/swift/llm/dataset/utils.py", line 176, in __getitem__
    res = self.encode_func(data)
  File "/home/workspace/InternVL_2d5/package/ms-swift-main/swift/llm/template/base.py", line 205, in encode
    encoded = self._encode(inputs)
  File "/home/workspace/InternVL_2d5/package/ms-swift-main/swift/llm/template/template/internvl.py", line 150, in _encode
    assert len(num_patches) == len(
AssertionError: len(num_patches): 1, len(idx_list): 0

[ERROR:swift] 👆👆👆There are errors in the template.encode, and another piece of data will be randomly selected.
```
我发现系数据过长导致的，当数据过长时，就会报错如上，且我在`"role": "user", "content"`中**是否有**`<image>`**都会报错**；
这个过长的长度阈值在哪我并没有测试出来，但我在vscode中观察数据，当超出了vscode的`editor.maxTokenizationLineLength`就一定会报如上错。

然后就是这个报错：
```
Traceback (most recent call last):
  File "/home/workspace/InternVL_2d5/package/swift/swift/llm/dataset/utils.py", line 176, in __getitem__
    res = self.encode_func(data)
  File "/home/workspace/InternVL_2d5/package/swift/swift/llm/template/base.py", line 199, in encode
    self._preprocess_inputs(inputs)
  File "/home/workspace/InternVL_2d5/package/swift/swift/llm/template/base.py", line 156, in _preprocess_inputs
    self._add_default_tags(inputs)
  File "/home/workspace/InternVL_2d5/package/swift/swift/llm/template/base.py", line 470, in _add_default_tags
    assert num_new_tags >= 0, f'Number of media: {num_media}, number of media_tags: {num_media_tags}'
AssertionError: Number of media: 1, number of media_tags: 2
```
这个是由于我的数据里面，存在多轮对话的数据，当两轮的 `"role": "user", "content"` 中都有`<image>`就会报错。
针对上面的两个报错原因，应该如何解决呢？
这个长度的数据，在swift2.x版本中并没有类似的报错提示，
然后是多轮对话的数据，`<image>`又该如何设置？

**Comment by Jintao-Huang** [comment]
第一个问题我复现了

**Comment by Jintao-Huang** [comment]
可以看一下数据集的格式不

**Comment by Jintao-Huang** [comment]
下面一个报错的原因是，图片的数量和<image>标签的数量个数不同导致的

**Comment by bonre** [comment]
> 可以看一下数据集的格式不

```
{
        "query": "aa<image>bb",
        "response": "ccc",
        "images": [
            "xxx/xx.png"
        ]
    }
```
这是2.x时用的数据集格式，然后我按照3.0的文档转换成message格式，依然存在第二个问题的第一个报错。

**Comment by bonre** [comment]
然后数量不一致的问题，如果是多轮对话的话，只需要在第一次对话指定image就可以嘛？我的对话是两轮，任务是分别对同一张图片做两次不同的信息识别。

**Comment by Jintao-Huang** [comment]
其实不需要转成messages格式，query response也能跑的

我修复了一版，你再拉一下代码试试

**Comment by bonre** [comment]
> 其实不需要转成messages格式，query response也能跑的
> 
> 我修复了一版，你再拉一下代码试试

@Jintao-Huang 感谢您及时修复！！！卡空了我再测试看看。

我看代码改动里面有改rlhf，是修复了dpo的那个报错吗？

另外，我这边有一个新的问题：
如果使用messages格式，我看默认有system字段，之前用query response我没有设置
3.0使用messages格式时，我修改了system字段，然后我看日志，在推理的时候会有如下这行：
`[INFO:swift] default_system: 你是书生·万象，英文名是InternVL，是由上海人工智能实验室、清华大学及多家合作单位联合开发的多模态大语言模型。`
请问，实际模型推理的时候，使用的system prompt是我在val_dataset里面自定义的prompt，还是默认的prompt呢？
因为之前我单独使用lmdeploy的时候，我记得它的推理pipline是有一个参数可以设置system prompt的，如果没有设置就会设置为默认，下面是我的推理代码：
```
CUDA_VISIBLE_DEVICES=0,1 swift infer \
            --model_type 'internvl2_5' \
            --ckpt_dir ${CKPT_DIR} \
            --infer_backend lmdeploy \
            --val_dataset /home/workspace/InternVL_2d5/data/eval/test/test.jsonl \
            --max_new_tokens 8192 \
            --temperature 0 \
            --repetition_penalty 1.0 \
            --tp 2 \
            --result_path /home/workspace/InternVL_2d5/data/eval/test/result.jsonl
```

**Comment by Jintao-Huang** [comment]
dataset中的sytem优先级最高的
