### ISSUE TITLE
merge multi loras

### ISSUE THREAD

**Issue by bingwork** [modelscope/ms-swift#2702]
peft                              0.14.0
ms-swift                          2.6.1

在目录/workspace/wubing/loras下面有两个lora模型文件：3420和3367，其中3367文件如下
<img width="333" alt="企业微信截图_20241219130958" src="https://github.com/user-attachments/assets/6b972991-f173-45f5-8759-cbcfd666cb9b" />
我是用以下代码，合并lora
`
from transformers import Qwen2VLForConditionalGeneration
from swift import Swift

category_lora_id_mapping = {
    "physical_relation": 3420,
    "future_prediction": 3367,
}
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "/models/Qwen2-VL-72B-Instruct", torch_dtype="auto", device_map="cpu"
)
adapter_name = {str(v): k for k, v in category_lora_id_mapping.items()}
model = Swift.from_pretrained(
    model, model_id="/workspace/wubing/loras/", adapter_name=adapter_name
)
adapters = list(category_lora_id_mapping.keys())
model.add_weighted_adapter(
    adapters=adapters,
    weights=[1.0] * len(adapters),
    adapter_name="merge",
    combination_type="ties",
    density=0.2,
)
`
最终报错：
`
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 38/38 [00:03<00:00, 12.46it/s]
Traceback (most recent call last):
  File "/workspace/wubing/titan/scripts/leaderboard/lora/merge_loras_swift copy.py", line 16, in <module>
    model.add_weighted_adapter(
  File "/workspace/wubing/anaconda3/envs/titan/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 697, in add_weighted_adapter
    target_lora_A.data, target_lora_B.data = self._generalized_task_arithmetic_weighted_adapter(
  File "/workspace/wubing/anaconda3/envs/titan/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 794, in _generalized_task_arithmetic_weighted_adapter
    valid_weights = torch.tensor(valid_weights).to(lora_A_deltas[0].device)
IndexError: list index out of range
`

请问是哪里有问题吗？

**Comment by bingwork** [comment]
参考https://huggingface.co/docs/peft/developer_guides/model_merging?ties=instruct，它会报vocabulary size不一致，
我改为如下代码：
`
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "6"

from peft import PeftConfig, PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

config = PeftConfig.from_pretrained("smangrul/tinyllama_lora_norobots")
model = AutoModelForCausalLM.from_pretrained(config.base_model_name_or_path, load_in_4bit=True, device_map="auto").eval()
tokenizer = AutoTokenizer.from_pretrained("smangrul/tinyllama_lora_norobots")

model.config.vocab_size = 32005  # 如果适配器需要更大的词汇表大小
model.resize_token_embeddings(32005)


model = PeftModel.from_pretrained(model, "smangrul/tinyllama_lora_norobots", adapter_name="norobots")
_ = model.load_adapter("smangrul/tinyllama_lora_sql", adapter_name="sql")


print("***** named_parameters")
for name, param in model.named_parameters():
    if 'model.layers.0.self_attn.q_proj' in name:
        print(f"Weight Name: {name}")


print("**** model.modules: ", model.modules)


print("***** named_modules")
for name, param in model.named_modules():
    if 'model.layers.0.self_attn.q_proj' in name:
        print(f"Module Name: {name}")


adapters = ["norobots", "sql"]
weights = [2.0, 1.0]
adapter_name = "merge"
density = 0.2
model.add_weighted_adapter(adapters, weights, adapter_name, combination_type="ties", density=density)

model.set_adapter("merge")

messages = [
    {"role": "user", "content": "Write an essay about Generative AI."},
]
text = tokenizer.apply_chat_template(messages, add_generation_prompt=True, tokenize=False)
inputs = tokenizer(text, return_tensors="pt")
inputs = {k: v.to("cuda") for k, v in inputs.items()}
outputs = model.generate(**inputs, max_new_tokens=256, do_sample=True, top_p=0.95, temperature=0.2, repetition_penalty=1.2, eos_token_id=tokenizer.eos_token_id)
print(tokenizer.decode(outputs[0]))

`


另外我在 /workspace/wubing/anaconda3/envs/titan/lib/python3.10/site-packages/peft/tuners/lora/model.py 添加一行打印
<img width="517" alt="企业微信截图_20241219153246" src="https://github.com/user-attachments/assets/9f01afde-342b-47f4-9731-77cec2d1dd21" />

model.layers.0相关的 keys如下，q_proj、k_proj等都只有一行。

***** key:  model.layers.0.self_attn.q_proj
***** key:  model.layers.0.self_attn.k_proj
***** key:  model.layers.0.self_attn.v_proj
***** key:  model.layers.0.self_attn.o_proj
***** key:  model.layers.0.mlp.gate_proj
***** key:  model.layers.0.mlp.up_proj
***** key:  model.layers.0.mlp.down_proj

model.layers.0相关的 modules如下，lora_A.norobots、lora_A.sql等都并级的。

***** named_modules
Module Name: base_model.model.model.layers.0.self_attn.q_proj
Module Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_dropout
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_dropout.norobots
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_dropout.sql
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.norobots
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.sql
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.norobots
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.sql
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_embedding_A
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_embedding_B
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_magnitude_vector

选择down_proj, lora_A 里面的norobots、sql等都并级的。

**** model.modules:  <bound method Module.modules of PeftModelForCausalLM(


              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5632, out_features=2048, bias=False)
                (lora_dropout): ModuleDict(
                  (norobots): Dropout(p=0.1, inplace=False)
                  (sql): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (norobots): Linear(in_features=5632, out_features=8, bias=False)
                  (sql): Linear(in_features=5632, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (norobots): Linear(in_features=8, out_features=2048, bias=False)
                  (sql): Linear(in_features=8, out_features=2048, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )


选择model.layers.0, lora_A 里面的norobots、sql等都并级的。

***** named_parameters
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.norobots.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.sql.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.norobots.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.sql.weight




但是如果是自己运行的话，

model.layers.0.self_attn.q_proj 会跑三次，这个不对，应该只有一次。

***** key:  model.layers.0.self_attn.q_proj
***** key:  model.layers.0.self_attn.q_proj.base_layer
***** key:  model.layers.0.self_attn.q_proj.base_layer.base_layer


future_prediction 都拼接到 physical_relation后面去了

***** named_parameters
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.base_layer.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.base_layer.bias
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.lora_A.future_prediction.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.lora_B.future_prediction.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation.base_layer.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation.lora_A.future_prediction.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation.lora_B.future_prediction.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.future_prediction.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation.base_layer.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation.lora_A.future_prediction.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation.lora_B.future_prediction.weight
Weight Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.future_prediction.weight

q_proj里面lora_A里面有physical_relation，里面又有future_prediction

**** model.modules:  <bound method Module.modules of PeftModelForCausalLM(

              (q_proj): lora.Linear(
                (base_layer): lora.Linear(
                  (base_layer): Linear(in_features=8192, out_features=8192, bias=True)
                  (lora_dropout): ModuleDict(
                    (future_prediction): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (future_prediction): Linear(in_features=8192, out_features=64, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (future_prediction): Linear(in_features=64, out_features=8192, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (lora_dropout): ModuleDict(
                  (physical_relation): Dropout(p=0.05, inplace=False)
                  (future_prediction): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (physical_relation): lora.Linear(
                    (base_layer): Linear(in_features=8192, out_features=64, bias=False)
                    (lora_dropout): ModuleDict(
                      (future_prediction): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (future_prediction): Linear(in_features=8192, out_features=64, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (future_prediction): Linear(in_features=64, out_features=64, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (future_prediction): Linear(in_features=8192, out_features=64, bias=False)
                )
                (lora_B): ModuleDict(
                  (physical_relation): lora.Linear(
                    (base_layer): Linear(in_features=64, out_features=8192, bias=False)
                    (lora_dropout): ModuleDict(
                      (future_prediction): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (future_prediction): Linear(in_features=64, out_features=64, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (future_prediction): Linear(in_features=64, out_features=8192, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (future_prediction): Linear(in_features=64, out_features=8192, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )


future_prediction 都拼接到 physical_relation后面去了


***** named_modules
Module Name: base_model.model.model.layers.0.self_attn.q_proj
Module Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer
Module Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.base_layer
Module Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.lora_dropout
Module Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.lora_dropout.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.lora_A
Module Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.lora_A.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.lora_B
Module Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.lora_B.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.lora_embedding_A
Module Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.lora_embedding_B
Module Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer.lora_magnitude_vector
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_dropout
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_dropout.physical_relation
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_dropout.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation.base_layer
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation.lora_dropout
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation.lora_dropout.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation.lora_A
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation.lora_A.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation.lora_B
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation.lora_B.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation.lora_embedding_A
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation.lora_embedding_B
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation.lora_magnitude_vector
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation.base_layer
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation.lora_dropout
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation.lora_dropout.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation.lora_A
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation.lora_A.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation.lora_B
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation.lora_B.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation.lora_embedding_A
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation.lora_embedding_B
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation.lora_magnitude_vector
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_embedding_A
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_embedding_B
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_magnitude_vector

**Comment by bingwork** [comment]
以下方式可以了，

将adapter_config.json 中的
   "target_modules": "^(model)(?!.*(lm_head|output|emb|wte|shared)).*",
改为
  "target_modules": [
    "down_proj",
    "gate_proj",
    "up_proj",
    "k_proj",
    "o_proj",
    "q_proj",
    "v_proj"
  ],

下面的显示是对的了

`
***** named_modules
Module Name: base_model.model.model.layers.0.self_attn.q_proj
Module Name: base_model.model.model.layers.0.self_attn.q_proj.base_layer
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_dropout
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_dropout.physical_relation
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_dropout.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.physical_relation
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_A.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.physical_relation
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_B.future_prediction
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_embedding_A
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_embedding_B
Module Name: base_model.model.model.layers.0.self_attn.q_proj.lora_magnitude_vector

add_weighted_adapter 时也正常了。

***** key:  model.layers.0.self_attn.q_proj
***** key:  model.layers.0.self_attn.k_proj
***** key:  model.layers.0.self_attn.v_proj
***** key:  model.layers.0.self_attn.o_proj
***** key:  model.layers.0.mlp.gate_proj
***** key:  model.layers.0.mlp.up_proj
***** key:  model.layers.0.mlp.down_proj


`
