### ISSUE TITLE
微调glmglm-4-9b-chat-hf 时报 “KeyError: 'auto_map'”错误

### ISSUE THREAD

**Issue by jsxyhelu** [modelscope/ms-swift#2716]
微调glmglm-4-9b-chat-hf 时报 “KeyError: 'auto_map'”错误

```
(base) root@autodl-container-54ed41a6ad-ac200117:~/swift# CUDA_VISIBLE_DEVICES=0 \
swift sft \
    --model /root/autodl-tmp/ZhipuAI/glm-4-9b-chat-hf \
    --model_type glm4 \
    --train_type lora \
    --dataset  swift/classical_chinese_translate#500 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --learning_rate 1e-4 \
    --lora_rank 8 \
    --lora_alpha 32 \
    --target_modules all-linear \
    --gradient_accumulation_steps 16 \
    --eval_steps 50 \
    --save_steps 50 \
    --save_total_limit 2 \
    --logging_steps 5 \
    --max_length 2048 \
    --output_dir output \
    --system 'You are a helpful assistant.' \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 4 \
    --model_author swift \
    --model_name swift-robot
run sh: `/root/miniconda3/bin/python /root/swift/swift/cli/sft.py --model /root/autodl-tmp/ZhipuAI/glm-4-9b-chat-hf --model_type glm4 --train_type lora --dataset swift/classical_chinese_translate#500 --num_train_epochs 1 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --learning_rate 1e-4 --lora_rank 8 --lora_alpha 32 --target_modules all-linear --gradient_accumulation_steps 16 --eval_steps 50 --save_steps 50 --save_total_limit 2 --logging_steps 5 --max_length 2048 --output_dir output --system You are a helpful assistant. --warmup_ratio 0.05 --dataloader_num_workers 4 --model_author swift --model_name swift-robot`
[INFO:swift] Successfully registered `/root/swift/swift/llm/dataset/data/dataset_info.json`
[INFO:swift] Successfully registered `[]`
[INFO:swift] rank: -1, local_rank: -1, world_size: 1, local_world_size: 1
[INFO:swift] Loading the model using model_dir: /root/autodl-tmp/ZhipuAI/glm-4-9b-chat-hf
[INFO:swift] Setting torch_dtype: torch.bfloat16
[INFO:swift] Setting args.lazy_tokenize: False
/root/miniconda3/lib/python3.12/site-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
[INFO:swift] output_dir: output/v5-20241220-143518
[INFO:swift] args: TrainArguments(
_n_gpu=-1,
acc_steps=1,
acc_strategy=token,
accelerator_config={'dispatch_batches': False},
adafactor=False,
adalora_beta1=0.85,
adalora_beta2=0.85,
adalora_deltaT=1,
adalora_init_r=12,
adalora_orth_reg_weight=0.5,
adalora_target_r=8,
adalora_tfinal=0,
adalora_tinit=0,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
adapter_act=gelu,
adapter_length=128,
adapters=[],
add_version=True,
attn_impl=None,
auto_find_batch_size=False,
average_tokens_across_devices=False,
batch_eval_metrics=False,
bf16=True,
bf16_full_eval=False,
bnb_4bit_compute_dtype=torch.bfloat16,
bnb_4bit_quant_storage=None,
bnb_4bit_quant_type=nf4,
bnb_4bit_use_double_quant=True,
boft_block_num=0,
boft_block_size=4,
boft_dropout=0.0,
boft_n_butterfly_factor=1,
check_model=True,
ckpt_dir=None,
custom_dataset_info=[],
custom_register_path=[],
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=4,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
dataset=['swift/classical_chinese_translate#500'],
dataset_num_proc=1,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=None,
deepspeed=None,
device_map=None,
disable_tqdm=None,
dispatch_batches=None,
do_eval=False,
do_predict=False,
do_train=False,
download_mode=reuse_dataset_if_exists,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=50.0,
eval_strategy=steps,
eval_use_gather_object=False,
evaluation_strategy=steps,
fourier_n_frequency=2000,
fourier_scaling=300.0,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
freeze_aligner=True,
freeze_llm=False,
freeze_parameters=[],
freeze_parameters_ratio=0.0,
freeze_vit=True,
fsdp=,
fsdp_config=None,
fsdp_min_num_params=0,
fsdp_num=1,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
galore_cos_threshold=0.4,
galore_gamma_proj=2,
galore_optim_per_parameter=False,
galore_proj_bits=4,
galore_proj_group_size=256,
galore_proj_quant=False,
galore_proj_type=std,
galore_quantization=False,
galore_queue_size=5,
galore_rank=128,
galore_scale=1.0,
galore_target_modules=None,
galore_update_proj_gap=50,
galore_with_embedding=False,
generation_config=None,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=16,
gradient_checkpointing=True,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hqq_axis=None,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_args_error=False,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=False,
include_tokens_per_second=False,
init_weights=True,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
lazy_tokenize=False,
learning_rate=0.0001,
length_column_name=length,
lisa_activated_layers=0,
lisa_step_interval=20,
llamapro_num_groups=None,
llamapro_num_new_blocks=4,
load_args=True,
load_best_model_at_end=False,
load_data_args=False,
load_dataset_config=None,
load_from_cache_file=False,
local_rank=-1,
local_repo_path=None,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=/root/swift/output/v5-20241220-143518/runs,
logging_first_step=True,
logging_nan_inf_filter=True,
logging_steps=5,
logging_strategy=steps,
lora_alpha=32,
lora_bias=none,
lora_dropout=0.05,
lora_dtype=None,
lora_ga_batch_size=2,
lora_ga_direction=ArB2r,
lora_ga_iters=2,
lora_ga_max_length=1024,
lora_ga_scale=stable,
lora_ga_stable_gamma=16,
lora_modules=[],
lora_rank=8,
lorap_lr_ratio=None,
loss_scale=default,
loss_type=None,
lr_scheduler_kwargs=None,
lr_scheduler_type=cosine,
max_grad_norm=1.0,
max_length=2048,
max_new_tokens=64,
max_pixels=None,
max_steps=-1,
metric=None,
metric_for_best_model=loss,
metric_warmup_step=0,
model=/root/autodl-tmp/ZhipuAI/glm-4-9b-chat-hf,
model_author=['swift'],
model_kwargs={},
model_layer_cls_name=None,
model_name=['swift-robot'],
model_revision=None,
model_type=glm4,
modules_to_save=[],
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_beams=1,
num_labels=None,
num_train_epochs=1.0,
optim=adamw_torch,
optim_args=None,
optim_target_modules=None,
optimizer=None,
output_dir=/root/swift/output/v5-20241220-143518,
overwrite_output_dir=False,
packing=False,
past_index=-1,
per_device_eval_batch_size=1,
per_device_train_batch_size=1,
predict_with_generate=False,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
quant_bits=None,
quant_method=None,
ray_scope=last,
reft_args=None,
reft_intervention_type=LoreftIntervention,
reft_layer_key=None,
reft_layers=None,
reft_rank=4,
remove_unused_columns=False,
repetition_penalty=None,
report_to=['tensorboard'],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
resume_only_model=False,
rope_scaling=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=50.0,
save_strategy=steps,
save_total_limit=2,
seed=42,
sequence_parallel_size=1,
skip_memory_metrics=True,
sortish_sampler=False,
split_batches=None,
split_dataset_ratio=0.01,
stop_words=[],
stream=False,
streaming=False,
strict=False,
system=You are a helpful assistant.,
target_modules=['all-linear'],
target_regex=None,
temperature=0.0,
template=glm4,
template_backend=swift,
tf32=None,
tools_prompt=react_en,
top_k=None,
top_p=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_dtype=torch.bfloat16,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
train_type=lora,
trainable_parameters=[],
truncation_strategy=delete,
tuner_backend=peft,
use_chat_template=True,
use_cpu=False,
use_dora=False,
use_galore=False,
use_hf=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_liger=False,
use_liger_kernel=False,
use_mps_device=False,
use_rslora=False,
use_swift_lora=False,
val_dataset=[],
vera_d_initial=0.1,
vera_dropout=0.0,
vera_projection_prng_key=0,
vera_rank=256,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.1,
)
[INFO:swift] The TrainArguments will be saved in: /root/swift/output/v5-20241220-143518/args.json
[INFO:swift] Loading the model using model_dir: /root/autodl-tmp/ZhipuAI/glm-4-9b-chat-hf
Traceback (most recent call last):
  File "/root/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/root/swift/swift/llm/train/sft.py", line 272, in sft_main
    return SwiftSft(args).main()
           ^^^^^^^^^^^^^^
  File "/root/swift/swift/llm/train/sft.py", line 32, in __init__
    self._prepare_model_tokenizer()
  File "/root/swift/swift/llm/train/sft.py", line 63, in _prepare_model_tokenizer
    self.model, self.processor = args.get_model_processor()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/swift/swift/llm/argument/base_args/base_args.py", line 259, in get_model_processor
    model, processor = get_model_tokenizer(**kwargs, model_kwargs=model_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/swift/swift/llm/model/register.py", line 497, in get_model_tokenizer
    model, processor = get_function(model_dir, model_info, model_kwargs, load_model, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/swift/swift/llm/model/model/glm.py", line 101, in get_model_tokenizer_glm4
    model, tokenizer = get_model_tokenizer_chatglm(model_dir, model_info, model_kwargs, load_model, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/swift/swift/llm/model/model/glm.py", line 38, in get_model_tokenizer_chatglm
    class_ref = tokenizer_config['auto_map']['AutoTokenizer'][0]
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'auto_map'
(base) root@autodl-container-54ed41a6ad-ac200117:~/swift# 
```

**Comment by 450586509** [comment]
+1

**Comment by 450586509** [comment]
修改以下参数可以训练：
--model ZhipuAI/glm-4-9b-chat
--model_type glm4
--template glm4

**Comment by Jintao-Huang** [comment]
我没有复现啊
