### ISSUE TITLE
autoawq failed: unexpected keyword argument 'use_cache'

### ISSUE THREAD

**Issue by gjmzj** [modelscope/ms-swift#2729]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
```
CUDA_VISIBLE_DEVICES=0,1,2,3 \
NPROC_PER_NODE=2 \
nohup swift export \
  --ckpt_dir qwen2.5-72b-instruct/checkpoint-140 \
  --quant_n_samples 64 \
  --quant_seqlen 2048 \
  --merge_lora true \
  --quant_bits 4 \
  --load_dataset_config true \
  --quant_method awq
```
error info:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/swift/cli/export.py", line 5, in <module>
    export_main()
  File "/usr/local/lib/python3.10/dist-packages/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/swift/llm/export.py", line 278, in llm_export
    model, template = prepare_model_template(
  File "/usr/local/lib/python3.10/dist-packages/swift/llm/infer.py", line 190, in prepare_model_template
    model, tokenizer = get_model_tokenizer(
  File "/usr/local/lib/python3.10/dist-packages/swift/llm/utils/model.py", line 7350, in get_model_tokenizer
    model, tokenizer = get_function(model_dir, torch_dtype, model_kwargs, load_model, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/swift/llm/utils/model.py", line 3869, in get_model_tokenizer_qwen2_chat
    return get_model_tokenizer_with_flash_attn(model_dir, torch_dtype, model_kwargs, load_model, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/swift/llm/utils/model.py", line 3016, in get_model_tokenizer_with_flash_attn
    return get_model_tokenizer_from_repo(
  File "/usr/local/lib/python3.10/dist-packages/swift/llm/utils/model.py", line 1112, in get_model_tokenizer_from_repo
    model = automodel_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/awq/models/auto.py", line 82, in from_pretrained
    return AWQ_CAUSAL_LM_MODEL_MAP[model_type].from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/awq/models/base.py", line 371, in from_pretrained
    model = target_cls.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 4130, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: Qwen2ForCausalLM.__init__() got an unexpected keyword argument 'use_cache'
```

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
L20 GPUs 0,1,2,3,
```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0
```
pip freeze
```
absl-py==2.1.0
accelerate==1.2.1
addict==2.4.0
aiofiles==23.2.1
aiohappyeyeballs==2.4.4
aiohttp==3.11.11
aiosignal==1.3.2
airportsdata==20241001
aliyun-python-sdk-core==2.16.0
aliyun-python-sdk-kms==2.16.5
annotated-types==0.7.0
anyio==4.7.0
astor==0.8.1
async-timeout==5.0.1
attrdict==2.0.1
attrs==24.3.0
autoawq==0.2.7.post3
binpacking==1.5.2
blake3==1.0.0
certifi==2024.12.14
cffi==1.17.1
charset-normalizer==3.4.0
click==8.1.8
cloudpickle==3.1.0
compressed-tensors==0.8.1
contourpy==1.3.1
cpm-kernels==1.0.11
crcmod==1.7
cryptography==44.0.0
cycler==0.12.1
dacite==1.8.1
datasets==3.0.1
depyf==0.18.0
dill==0.3.8
diskcache==5.6.3
distro==1.9.0
docstring_parser==0.16
einops==0.8.0
exceptiongroup==1.2.2
fastapi==0.115.6
ffmpy==0.5.0
filelock==3.16.1
fonttools==4.55.3
frozenlist==1.5.0
fsspec==2024.6.1
future==1.0.0
gguf==0.10.0
gradio==5.9.1
gradio_client==1.5.2
grpcio==1.68.1
h11==0.14.0
httpcore==1.0.7
httptools==0.6.4
httpx==0.28.1
huggingface-hub==0.27.0
idna==3.10
importlib_metadata==8.5.0
iniconfig==2.0.0
interegular==0.3.3
jieba==0.42.1
Jinja2==3.1.5
jiter==0.8.2
jmespath==0.10.0
joblib==1.4.2
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
kiwisolver==1.4.7
lark==1.2.2
lm-format-enforcer==0.10.9
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.10.0
mdurl==0.1.2
mistral_common==1.5.1
modelscope==1.21.0
mpmath==1.3.0
ms-swift==2.6.1
msgpack==1.1.0
msgspec==0.18.6
multidict==6.1.0
multiprocess==0.70.16
nest-asyncio==1.6.0
networkx==3.4.2
nltk==3.9.1
numpy==1.26.4
nvidia-cublas-cu12==12.4.5.8
nvidia-cuda-cupti-cu12==12.4.127
nvidia-cuda-nvrtc-cu12==12.4.127
nvidia-cuda-runtime-cu12==12.4.127
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.1.3
nvidia-curand-cu12==10.3.5.147
nvidia-cusolver-cu12==11.6.1.9
nvidia-cusparse-cu12==12.3.1.170
nvidia-ml-py==12.560.30
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.4.127
openai==1.58.1
opencv-python-headless==4.10.0.84
orjson==3.10.12
oss2==2.19.1
outlines==0.1.11
outlines_core==0.1.26
packaging==24.2
pandas==2.2.3
partial-json-parser==0.2.1.1.post4
peft==0.12.0
pillow==10.4.0
pluggy==1.5.0
prometheus-fastapi-instrumentator==7.0.0
prometheus_client==0.21.1
propcache==0.2.1
protobuf==5.29.2
psutil==6.1.1
py-cpuinfo==9.0.0
pyarrow==18.1.0
pybind11==2.13.6
pycountry==24.6.1
pycparser==2.22
pycryptodome==3.21.0
pydantic==2.10.4
pydantic_core==2.27.2
pydub==0.25.1
Pygments==2.18.0
pyparsing==3.2.0
pytest==8.3.4
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-multipart==0.0.20
pytz==2024.2
PyYAML==6.0.2
pyzmq==26.2.0
ray==2.40.0
referencing==0.35.1
regex==2024.11.6
requests==2.32.3
rich==13.9.4
rouge==1.0.1
rpds-py==0.22.3
ruff==0.8.4
safehttpx==0.1.6
safetensors==0.4.5
scipy==1.14.1
semantic-version==2.10.0
sentencepiece==0.2.0
shellingham==1.5.4
shtab==1.7.1
simplejson==3.19.3
six==1.17.0
sniffio==1.3.1
sortedcontainers==2.4.0
starlette==0.41.3
sympy==1.13.1
tensorboard==2.18.0
tensorboard-data-server==0.7.2
tiktoken==0.7.0
tokenizers==0.21.0
tomli==2.2.1
tomlkit==0.13.2
torch==2.5.1
torchvision==0.20.1
tqdm==4.67.1
transformers==4.47.1
transformers-stream-generator==0.0.5
triton==3.1.0
trl==0.11.4
typeguard==4.4.1
typer==0.15.1
typing_extensions==4.12.2
tyro==0.9.4
tzdata==2024.2
urllib3==2.2.3
uvicorn==0.34.0
uvloop==0.21.0
vllm==0.6.5
watchfiles==1.0.3
websockets==14.1
Werkzeug==3.1.3
xformers==0.0.28.post3
xgrammar==0.1.7
xxhash==3.5.0
yarl==1.18.3
zipp==3.21.0
zstandard==0.23.0
```

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
autoawq==0.2.7.post2

**Comment by gjmzj** [comment]
> autoawq==0.2.7.post2

many thanks! it works
