### ISSUE TITLE
fsdp + qlora 单机多卡运行失败

### ISSUE THREAD

**Issue by 450586509** [modelscope/ms-swift#2737]
**Describe the bug**
执行这个训练脚本：
bash ./examples/train/multi-gpu/fsdp_qlora/train.sh
模型已改为：Qwen2.5-14B-Instruct
config_file改为：./examples/train/multi-gpu/fsdp_qlora/fsdp_offload.json
其它配置没有改变

报以下错误信息

`[INFO:swift] The logging file will be saved in: /disk1/home/xiewenwen/projects/github/ms-swift/output/Qwen2.5-14B-Instruct/v5-20241223-170529/logging.jsonl
Train:   0%|                                                                                                                                     | 0/62 [00:00<?, ?it/s]W1223 17:10:13.662000 530255 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 530296 closing signal SIGTERM
E1223 17:10:17.404000 530255 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -9) local_rank: 1 (pid: 530297) of binary: /disk1/miniconda3/envs/ms_swift/bin/python
Traceback (most recent call last):
  File "/disk1/miniconda3/envs/ms_swift/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/disk1/miniconda3/envs/ms_swift/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/disk1/miniconda3/envs/ms_swift/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1155, in launch_command
    multi_gpu_launcher(args)
  File "/disk1/miniconda3/envs/ms_swift/lib/python3.10/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/disk1/miniconda3/envs/ms_swift/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/disk1/miniconda3/envs/ms_swift/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/disk1/miniconda3/envs/ms_swift/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
swift/cli/sft.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-23_17:10:13
  host      : hltn-System-Product-Name
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 530297)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 530297
=======================================================`

**Your hardware and system info**
cuda: 12.6
gpu: 两个4090
torch==2.5.1

**Comment by 450586509** [comment]
官方文档中提到通过fsdp+qlora， 可以在双卡3090运行70B模型的训练，有人成功过吗？
如果在3090下可以运行，在4090下应该也可以吧，我是在双卡4090下测试的，但是没有复现。
官方文档链接：https://swift.readthedocs.io/zh-cn/latest/Instruction/%E9%A2%84%E8%AE%AD%E7%BB%83%E5%8F%8A%E5%BE%AE%E8%B0%83.html

**Comment by AriesJin** [comment]
解决了嘛？我碰到ValueError: Must flatten tensors with uniform `requires_grad` when `use_orig_params=False`

**Comment by z0o0ey** [comment]
please retry with latest swift and vllm, feel free to create a new issue if it the problem persists.
