### ISSUE TITLE
MaxLengthError for pre-training 

### ISSUE THREAD

**Issue by liuyixin-louis** [modelscope/ms-swift#2745]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

 when doing pre-training, each row can be very long, and it seems that it directly drops the row instead of doing some samples packing. Streaming yields time out since the network is not stable in my env.  

Map (num_proc=128):   0%|                                       | 5000/5489000 [00:06<1:34:21, 968.70 examples/s]
Traceback (most recent call last):
  File "swift/llm/dataset/preprocessor/core.py", line 155, in batched_preprocess
    row = self.preprocess(row)
  File "swift/llm/dataset/utils.py", line 202, in preprocess
    return self.template.encode(row)
  File "swift/llm/template/base.py", line 205, in encode
    encoded = self._encode(inputs)
  File "swift/llm/template/base.py", line 628, in _encode
    raise MaxLengthError(f'Current length of row({len(input_ids)}) is larger'
swift.llm.template.base.MaxLengthError: Current length of row(5762) is larger than the max_length(2048).

[ERROR:swift] 👆👆👆There are errors in the dataset, the data will be deleted

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
You can control it through `--max_length xxx`.

**Comment by liuyixin-louis** [comment]
Thanks for quick response! Another quick question: what is the typical max_length value for the pre-training dataest, and also can I use the --packing true to pack the examples?

**Comment by Jintao-Huang** [comment]
Yes, you can use --packing true for packing examples. The value of max_length depends on the GPU memory situation.

**Comment by Barry1915** [comment]
> You can control it through `--max_length xxx`.



> You can control it through `--max_length xxx`.

但是感觉手动改max_length有点机械，就不能把超过max_length的数据自动跳过吗

**Comment by GEHAH** [comment]
Can we truncate samples longer than --max_length instead of deleting them?
