### ISSUE TITLE
pretrain的数据结构问题

### ISSUE THREAD

**Issue by YingchaoX** [modelscope/ms-swift#2750]
**Describe the bug**
我参考了[Custom-dataset](https://swift.readthedocs.io/en/latest/Customization/Custom-dataset.html#pre-training)这个文档的pt的数据结构，也就是
```bash
{"messages": [{"role": "assistant", "content": "I love music"}]}
{"messages": [{"role": "assistant", "content": "Coach, I want to play basketball"}]}
```
但是训练报错
```bash
[ERROR:swift] 👆👆👆There are errors in the dataset, the data will be deleted
Traceback (most recent call last):
  File "/home/xiongyc/miniconda3/envs/llm/lib/python3.10/site-packages/swift/llm/dataset/preprocessor/core.py", line 162, in batched_preprocess
    self._check_messages(r)
  File "/home/xiongyc/miniconda3/envs/llm/lib/python3.10/site-packages/swift/llm/dataset/preprocessor/core.py", line 60, in _check_messages
    assert len(messages) > 0, f'messages: {messages}'
AssertionError: messages: []
[ERROR:swift] 👆👆👆There are errors in the dataset, the data will be deleted
```

不过使用旧的数据结构是没有问题的，也就是：
```bash
{"response": "I love music"}
{"response": "Coach, I want to play basketball"}
```

目前3.0版本还是需要使用旧的pretrain数据结构么？

**Your hardware and system info**
python 3.10
ms-swift 3.0.0

**Comment by tastelikefeet** [comment]
我用你的格式试了下没问题
```text
{"messages": [{"role": "assistant", "content": "I love music"}]}
{"messages": [{"role": "assistant", "content": "Coach, I want to play basketball"}]}
```
你是不是哪里写的有问题啊，仔细看下呢

**Comment by YingchaoX** [comment]
额，确实是我的配置问题，谢谢！

**Comment by cooperong** [comment]
> 额，确实是我的配置问题，谢谢！

请问你是怎么解决的，碰到跟你一样的问题

**Comment by fortuneate3** [comment]
> 额，确实是我的配置问题，谢谢！

我也遇到了同样的问题，请问是怎么解决的呀？😵

**Comment by manglu097** [comment]
@YingchaoX 请问你是怎么解决的啊

**Comment by YingchaoX** [comment]
> [@YingchaoX](https://github.com/YingchaoX) 请问你是怎么解决的啊

我这里没有按照文档构造数据，，，可以再检查一下数据，哪个不满文档中的格式要求
