### ISSUE TITLE
DeepSeek-VL2推理报错

### ISSUE THREAD

**Issue by NB-wo** [modelscope/ms-swift#2763]
**Describe the bug**
使用DeepSeek-VL2推理报错：RuntimeError: cannot reshape tensor of 0 elements into shape [1, 0, -1, 128] because the unspecified dimension size -1 can be any value and is ambiguous

推理命令：

CUDA_VISIBLE_DEVICES=1 \
swift infer \
    --checkpoint checkpoint-9942 \
    --infer_backend pt \
    --val_dataset test.jsonl \
    --max_batch_size 1 \
    --max_new_tokens 512

完整报错如下：
`[INFO:swift] Start time of running main: 2024-12-25 14:56:43.035142
[INFO:swift] Global seed set to 42
[INFO:swift] request_config: RequestConfig(max_tokens=512, temperature=None, top_k=None, top_p=None, repetition_penalty=None, num_beams=1, stop=[], seed=None, stream=False, logprobs=False, top_logprobs=None, n=1, best_of=None, presence_penalty=0.0, frequency_penalty=0.0, length_penalty=1.0)
Generating train split: 1 examples [00:00, 185.51 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 72.91 examples/s]
[INFO:swift] val_dataset: Dataset({
    features: ['images', 'messages'],
    num_rows: 1
})
  0%|                                                                                                   | 0/1 [00:00<?, ?it/s]You're using a LlamaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.
`get_max_cache()` is deprecated for all Cache classes. Use `get_max_cache_shape()` instead. Calling `get_max_cache()` will raise error from v4.48
Traceback (most recent call last):
  File "path/ms-swift/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "path/ms-swift/swift/llm/infer/infer.py", line 208, in infer_main
    return SwiftInfer(args).main()
  File "path/ms-swift/swift/llm/infer/infer.py", line 83, in main
    return super().main()
  File "path/ms-swift/swift/llm/base.py", line 45, in main
    result = self.run()
  File "path/ms-swift/swift/llm/infer/infer.py", line 90, in run
    result = self.infer_dataset()
  File "path/ms-swift/swift/llm/infer/infer.py", line 191, in infer_dataset
    resp_list = self.infer(
  File "path/envs/swift3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "path/ms-swift/swift/llm/infer/infer_engine/pt_engine.py", line 427, in infer
    res += self._infer(
  File "path/ms-swift/swift/llm/infer/infer_engine/pt_engine.py", line 383, in _infer
    return self._update_metrics(self._infer_full(**kwargs), metrics)
  File "path/ms-swift/swift/llm/infer/infer_engine/pt_engine.py", line 272, in _infer_full
    output = dict(template.generate(self.model, **generate_kwargs))
  File "path/ms-swift/swift/llm/template/base.py", line 236, in generate
    return model.generate(*args, **kwargs)
  File "path/ms-swift/swift/llm/model/utils.py", line 315, in _new_func
    res = _old_func(submodel, *args, **kwargs)
  File "path/envs/swift3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "path/envs/swift3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2252, in generate
    result = self._sample(
  File "path/envs/swift3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3251, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "path/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "path/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "path/ms-swift/swift/llm/model/utils.py", line 315, in _new_func
    res = _old_func(submodel, *args, **kwargs)
  File "/home/hadoop-seccv/.cache/modelscope/hub/_github/DeepSeek-VL2/deepseek_vl2/models/modeling_deepseek.py", line 1723, in forward
    outputs = self.model(
  File "path/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "path/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hadoop-seccv/.cache/modelscope/hub/_github/DeepSeek-VL2/deepseek_vl2/models/modeling_deepseek.py", line 1592, in forward
    layer_outputs = decoder_layer(
  File "path/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "path/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hadoop-seccv/.cache/modelscope/hub/_github/DeepSeek-VL2/deepseek_vl2/models/modeling_deepseek.py", line 1306, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "path/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "path/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "path/envs/swift3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 309, in forward
    query_states = query_states.view(bsz, q_len, -1, self.head_dim).transpose(1, 2)
RuntimeError: cannot reshape tensor of 0 elements into shape [1, 0, -1, 128] because the unspecified dimension size -1 can be any value and is ambiguous`

**Your hardware and system info**
linux
A100 40G
torch                         2.5.1+cu118
torchvision                   0.20.1+cu118
transformers                  4.47.1
ms-swift                      3.1.0.dev0

**Comment by tastelikefeet** [comment]
transformers<=4.42

**Comment by JimmyMa99** [comment]
Traceback (most recent call last):
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/cli/infer.py", line 2, in <module>
    from swift.llm import infer_main
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/utils/import_utils.py", line 83, in __getattr__
    value = getattr(module, name)
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/utils/import_utils.py", line 82, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/utils/import_utils.py", line 91, in _get_module
    return importlib.import_module('.' + module_name, self.__name__)
  File "/root/.conda/envs/swift-new-4/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/llm/infer/infer.py", line 10, in <module>
    from swift.llm import InferArguments, InferRequest, SwiftPipeline, load_dataset, prepare_model_template, sample_dataset
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/utils/import_utils.py", line 82, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/utils/import_utils.py", line 91, in _get_module
    return importlib.import_module('.' + module_name, self.__name__)
  File "/root/.conda/envs/swift-new-4/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/llm/argument/__init__.py", line 2, in <module>
    from .app_args import AppArguments
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/llm/argument/app_args.py", line 6, in <module>
    from ..model import get_matched_model_meta
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/llm/model/__init__.py", line 2, in <module>
    from . import model
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/llm/model/model/__init__.py", line 1, in <module>
    from . import (baai, baichuan, bert, codefuse, deepseek, gemma, glm, internlm, llama, llava, llm, mamba, microsoft,
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/llm/model/model/baai.py", line 8, in <module>
    from swift.llm import TemplateType
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/utils/import_utils.py", line 82, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/utils/import_utils.py", line 91, in _get_module
    return importlib.import_module('.' + module_name, self.__name__)
  File "/root/.conda/envs/swift-new-4/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/llm/template/__init__.py", line 2, in <module>
    from . import template
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/llm/template/template/__init__.py", line 1, in <module>
    from . import (deepseek, emu3, gemma, glm, got_ocr, idefics3, internlm, internvl, llama, llava, llm, megrez, microsoft,
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/llm/template/template/deepseek.py", line 8, in <module>
    from ..base import Template
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/swift/llm/template/base.py", line 16, in <module>
    from peft import PeftModel
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/peft/auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/peft/mapping.py", line 25, in <module>
    from .mixed_model import PeftMixedModel
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/peft/mixed_model.py", line 29, in <module>
    from .peft_model import PeftModel
  File "/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/peft/peft_model.py", line 37, in <module>
    from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel
ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (/root/.conda/envs/swift-new-4/lib/python3.10/site-packages/transformers/__init__.py)

**Comment by JimmyMa99** [comment]
使用了transformers==4.41.1

**Comment by Jintao-Huang** [comment]
> 使用了transformers==4.41.1

降低peft版本

**Comment by gromtang** [comment]
> > 使用了transformers==4.41.1
> 
> 降低peft版本

transformers==4.41.1
peft==0.13.2问题解决

**Comment by corkiyao** [comment]
> > > 使用了transformers==4.41.1
> > 
> > 
> > 降低peft版本
> 
> transformers==4.41.1 peft==0.13.2问题解决

你好，请问你的deepseek-vl2的数据集需要转换成千分位吗？就是坐标 / img_width * 1000? 还是保持原有的，不做变化？
