### ISSUE TITLE
请问下断点重训具体命令是什么啊

### ISSUE THREAD

**Issue by ransheng11** [modelscope/ms-swift#2768]
我查看了其他issue，在重训时加了--resume_from_checkpoint  —resume_only_model但仍然报错，主要是梯度重复计算，我的命令是
<img width="791" alt="f0c0cff84cb064ce7b345f39105f60a" src="https://github.com/user-attachments/assets/2f9baaca-25c7-44b5-bba3-110c760e8cb8" />

**Comment by ransheng11** [comment]
`Traceback (most recent call last):
  File "/root/autodl-tmp/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/root/autodl-tmp/swift/swift/llm/train/sft.py", line 272, in sft_main
    return SwiftSft(args).main()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/swift/swift/llm/base.py", line 45, in main
    result = self.run()
             ^^^^^^^^^^
  File "/root/autodl-tmp/swift/swift/llm/train/sft.py", line 139, in run
    return self.train(trainer)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/swift/swift/llm/train/sft.py", line 191, in train
    trainer.train(trainer.args.resume_from_checkpoint)
  File "/root/autodl-tmp/swift/swift/trainers/mixin.py", line 261, in train
    return super().train(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/minicpm-v/lib/python3.11/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/minicpm-v/lib/python3.11/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/minicpm-v/lib/python3.11/site-packages/transformers/trainer.py", line 3147, in training_step
    self.accelerator.backward(loss)
  File "/root/miniconda3/envs/minicpm-v/lib/python3.11/site-packages/accelerate/accelerator.py", line 2125, in backward
    loss.backward(**kwargs)
  File "/root/miniconda3/envs/minicpm-v/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/root/miniconda3/envs/minicpm-v/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/minicpm-v/lib/python3.11/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/minicpm-v/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 288, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/root/miniconda3/envs/minicpm-v/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 391 with name base_model.model.llm.model.layers.27.mlp.down_proj.lora_B.default.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.`

**Comment by Jintao-Huang** [comment]
看看报错信息

**Comment by ransheng11** [comment]
我现在按照之前的命令训练又好了，但昨天报错信息有
`Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the forward function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple checkpoint functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 391 with name base_model.model.llm.model.layers.27.mlp.down_proj.lora_B.default.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.`
` assert self.params_already_reduced[param_id] == False, 
AssertionError: The parameter 551 has already been reduced.                     Gradient computed twice for this partition.                     Multiple gradient reduction is currently not supported`

**Comment by Jintao-Huang** [comment]
--gradient_checkpointing_kwargs '{"use_reentrant": false}'
