### ISSUE TITLE
支持Valley多模态模型

### ISSUE THREAD

**Issue by ttttyyyy-beep** [modelscope/ms-swift#2786]
Valley是由字节跳动开发的前沿多模态大模型，旨在处理涉及文本、图像和视频数据的多种任务。该模型在内部电商和短视频基准测试中取得了最佳结果，并在OpenCompass测试中表现出色，尤其是在小于10B参数规模的模型中排名前二。

模型链接：https://huggingface.co/bytedance-research/Valley-Eagle-7B

**Comment by Jintao-Huang** [comment]
支持中...

**Comment by Jintao-Huang** [comment]
已支持

**Comment by oswardlx** [comment]
> 已支持

怎么启动呀

报错：
$CUDA_VISIBLE_DEVICES=0 swift infer     --model /home/admin/model/model     --stream false     --infer_backend pt     --max_new_tokens 2048
run sh: `/usr/local/bin/python3.10 /home/admin/.local/lib/python3.10/site-packages/swift/cli/infer.py --model /home/admin/model/model --stream false --infer_backend pt --max_new_tokens 2048`
[INFO:swift] Successfully registered `/home/admin/.local/lib/python3.10/site-packages/swift/llm/dataset/data/dataset_info.json`.
[INFO:swift] rank: -1, local_rank: -1, world_size: 1, local_world_size: 1
[INFO:swift] Loading the model using model_dir: /home/admin/model/model
[INFO:swift] Setting model_type: valley
[INFO:swift] Setting torch_dtype: torch.bfloat16
[INFO:swift] Setting args.lazy_tokenize: True
[INFO:swift] args.result_path: /home/admin/result/model/infer_result/20250826-123338.jsonl
[INFO:swift] Setting args.eval_human: True
[INFO:swift] Global seed set to 42
[INFO:swift] args: InferArguments(model='/home/admin/model/model', model_type='valley', model_revision=None, task_type='causal_lm', torch_dtype=torch.bfloat16, attn_impl=None, new_special_tokens=[], num_labels=None, problem_type=None, rope_scaling=None, device_map=None, max_memory={}, max_model_len=None, local_repo_path=None, init_strategy=None, template='valley', system=None, max_length=None, truncation_strategy='delete', max_pixels=None, agent_template=None, norm_bbox=None, use_chat_template=True, padding_free=False, padding_side='right', loss_scale='default', sequence_parallel_size=1, response_prefix=None, template_backend='swift', dataset=[], val_dataset=[], split_dataset_ratio=0.0, data_seed=42, dataset_num_proc=1, load_from_cache_file=True, dataset_shuffle=True, val_dataset_shuffle=False, streaming=False, interleave_prob=None, stopping_strategy='first_exhausted', shuffle_buffer_size=1000, download_mode='reuse_dataset_if_exists', columns={}, strict=False, remove_unused_columns=True, model_name=None, model_author=None, custom_dataset_info=[], quant_method=None, quant_bits=None, hqq_axis=None, bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_quant_type='nf4', bnb_4bit_use_double_quant=True, bnb_4bit_quant_storage=None, max_new_tokens=2048, temperature=None, top_k=None, top_p=None, repetition_penalty=None, num_beams=1, stream=False, stop_words=[], logprobs=False, top_logprobs=None, ckpt_dir=None, lora_modules=[], tuner_backend='peft', train_type='lora', adapters=[], external_plugins=[], seed=42, model_kwargs={}, load_args=True, load_data_args=False, packing=False, lazy_tokenize=True, cached_dataset=[], custom_register_path=[], use_hf=False, hub_token=None, ddp_timeout=18000000, ddp_backend=None, ignore_args_error=False, use_swift_lora=False, vllm_gpu_memory_utilization=0.9, vllm_tensor_parallel_size=1, vllm_pipeline_parallel_size=1, vllm_enable_expert_parallel=False, vllm_max_num_seqs=256, vllm_max_model_len=None, vllm_disable_custom_all_reduce=True, vllm_enforce_eager=False, vllm_limit_mm_per_prompt={}, vllm_max_lora_rank=16, vllm_enable_prefix_caching=False, vllm_use_async_engine=False, vllm_quantization=None, vllm_data_parallel_size=1, gpu_memory_utilization=None, tensor_parallel_size=None, limit_mm_per_prompt=None, data_parallel_size=None, use_async_engine=None, sglang_tp_size=1, sglang_pp_size=1, sglang_dp_size=1, sglang_ep_size=1, sglang_enable_ep_moe=False, sglang_mem_fraction_static=None, sglang_context_length=None, sglang_disable_cuda_graph=False, sglang_quantization=None, sglang_kv_cache_dtype='auto', sglang_enable_dp_attention=False, sglang_disable_custom_all_reduce=True, lmdeploy_tp=1, lmdeploy_session_len=None, lmdeploy_cache_max_entry_count=0.8, lmdeploy_quant_policy=0, lmdeploy_vision_batch_size=1, merge_lora=False, safe_serialization=True, max_shard_size='5GB', infer_backend='pt', result_path='/home/admin/result/model/infer_result/20250826-123338.jsonl', write_batch_size=1000, metric=None, max_batch_size=1, val_dataset_sample=None)
[INFO:swift] Loading the model using model_dir: /home/admin/model/model
[INFO:swift] Run the command: `git -C /home/admin/.cache/modelscope/hub/_github/Valley fetch`
[INFO:swift] Run the command: `git -C /home/admin/.cache/modelscope/hub/_github/Valley pull`
Already up to date.
[INFO:swift] local_repo_path: /home/admin/.cache/modelscope/hub/_github/Valley
/home/admin/.local/lib/python3.10/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
[INFO:swift] Downloading the model from ModelScope Hub, model_id: AI-ModelScope/siglip-so400m-patch14-384
Downloading Model from https://www.modelscope.cn to directory: /home/admin/.cache/modelscope/hub/models/AI-ModelScope/siglip-so400m-patch14-384
[INFO:swift] Loading the model using model_dir: /home/admin/.cache/modelscope/hub/models/AI-ModelScope/siglip-so400m-patch14-384
[INFO:swift] Downloading the model from ModelScope Hub, model_id: Qwen/Qwen2-VL-7B-Instruct
Downloading Model from https://www.modelscope.cn to directory: /home/admin/.cache/modelscope/hub/models/Qwen/Qwen2-VL-7B-Instruct
[INFO:swift] Loading the model using model_dir: /home/admin/.cache/modelscope/hub/models/Qwen/Qwen2-VL-7B-Instruct
[INFO:swift] model_kwargs: {'device_map': 'cuda:0'}
language: english, vision_tower: /home/admin/.cache/modelscope/hub/models/AI-ModelScope/siglip-so400m-patch14-384
You are attempting to use Flash Attention 2 without specifying a torch dtype. This might lead to unexpected behaviour
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.09it/s]
The image processor of type `Qwen2VLImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. Note that this behavior will be extended to all models in a future release.
You have video processor config saved in `preprocessor.json` file which is deprecated. Video processor configs should be saved in their own `video_preprocessor.json` file. You can rename the file or load and save the processor back which renames it automatically. Loading from `preprocessor.json` will be removed in v5.0.
[INFO:swift] default_system: 'You are Valley, a large language and vision assistant trained by ByteDance.You are able to understand the visual content or video that the user provides, and assist the user with a variety of tasks using natural language.Follow the instructions carefully and explain your answers in detail.'
[INFO:swift] max_length: 32768
[INFO:swift] response_prefix: ''
[INFO:swift] agent_template: react_en
[INFO:swift] norm_bbox: norm1000
[INFO:swift] model: ValleyQwen2ForCausalLM(
  (model): ValleyQwen2Model(
    (embed_tokens): Embedding(151679, 3584)
    (layers): ModuleList(
      (0-27): 28 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear(in_features=3584, out_features=3584, bias=True)
          (k_proj): Linear(in_features=3584, out_features=512, bias=True)
          (v_proj): Linear(in_features=3584, out_features=512, bias=True)
          (o_proj): Linear(in_features=3584, out_features=3584, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=3584, out_features=18944, bias=False)
          (up_proj): Linear(in_features=3584, out_features=18944, bias=False)
          (down_proj): Linear(in_features=18944, out_features=3584, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((3584,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
    (vision_tower): SigLipVisionTower(
      (vision_tower): SiglipVisionModel(
        (vision_model): SiglipVisionTransformer(
          (embeddings): SiglipVisionEmbeddings(
            (patch_embedding): Conv2d(3, 1152, kernel_size=(14, 14), stride=(14, 14), padding=valid)
            (position_embedding): Embedding(729, 1152)
          )
          (encoder): SiglipEncoder(
            (layers): ModuleList(
              (0-26): 27 x SiglipEncoderLayer(
                (layer_norm1): LayerNorm((1152,), eps=1e-06, elementwise_affine=True)
                (self_attn): SiglipAttention(
                  (k_proj): Linear(in_features=1152, out_features=1152, bias=True)
                  (v_proj): Linear(in_features=1152, out_features=1152, bias=True)
                  (q_proj): Linear(in_features=1152, out_features=1152, bias=True)
                  (out_proj): Linear(in_features=1152, out_features=1152, bias=True)
                )
                (layer_norm2): LayerNorm((1152,), eps=1e-06, elementwise_affine=True)
                (mlp): SiglipMLP(
                  (activation_fn): PytorchGELUTanh()
                  (fc1): Linear(in_features=1152, out_features=4304, bias=True)
                  (fc2): Linear(in_features=4304, out_features=1152, bias=True)
                )
              )
            )
          )
          (post_layernorm): LayerNorm((1152,), eps=1e-06, elementwise_affine=True)
          (head): SiglipMultiheadAttentionPoolingHead(
            (attention): MultiheadAttention(
              (out_proj): NonDynamicallyQuantizableLinear(in_features=1152, out_features=1152, bias=True)
            )
            (layernorm): LayerNorm((1152,), eps=1e-06, elementwise_affine=True)
            (mlp): SiglipMLP(
              (activation_fn): PytorchGELUTanh()
              (fc1): Linear(in_features=1152, out_features=4304, bias=True)
              (fc2): Linear(in_features=4304, out_features=1152, bias=True)
            )
          )
        )
      )
    )
    (qwen2vl_vision_tower): Qwen2VisionTransformerPretrainedModel(
      (patch_embed): PatchEmbed(
        (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
      )
      (rotary_pos_emb): VisionRotaryEmbedding()
      (blocks): ModuleList(
        (0-31): 32 x Qwen2VLVisionBlock(
          (norm1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (norm2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (attn): VisionAttention(
            (qkv): Linear(in_features=1280, out_features=3840, bias=True)
            (proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (mlp): VisionMlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): QuickGELUActivation()
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
          )
        )
      )
      (merger): PatchMerger(
        (ln_q): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (mlp): Sequential(
          (0): Linear(in_features=5120, out_features=5120, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=5120, out_features=3584, bias=True)
        )
      )
    )
    (mm_projector): OvisConvAdapter(
      (conv): Conv2d(1152, 1152, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (mlp): Sequential(
        (0): Linear(in_features=1152, out_features=32000, bias=False)
        (1): LayerNorm((32000,), eps=1e-05, elementwise_affine=True)
      )
      (embedding): Embedding(32000, 3584)
    )
  )
  (lm_head): Linear(in_features=3584, out_features=151679, bias=False)
)
[INFO:swift] Start time of running main: 2025-08-26 12:33:45.342998
[INFO:swift] swift.__version__: 3.7.2
[INFO:swift] request_config: RequestConfig(max_tokens=2048, temperature=None, top_k=None, top_p=None, repetition_penalty=None, num_beams=1, stop=[], seed=None, stream=False, logprobs=False, top_logprobs=None, n=1, best_of=None, presence_penalty=0.0, frequency_penalty=0.0, length_penalty=1.0, return_details=False)
[INFO:swift] Input `exit` or `quit` to exit the conversation.
[INFO:swift] Input `multi-line` to switch to multi-line input mode.
[INFO:swift] Input `reset-system` to reset the system and clear the history.
[INFO:swift] Input `clear` to clear the history.
<<< 你好
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.10/site-packages/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "/home/admin/.local/lib/python3.10/site-packages/swift/llm/infer/infer.py", line 291, in infer_main
    return SwiftInfer(args).main()
  File "/home/admin/.local/lib/python3.10/site-packages/swift/llm/base.py", line 49, in main
    result = self.run()
  File "/home/admin/.local/lib/python3.10/site-packages/swift/llm/infer/infer.py", line 89, in run
    result = self.infer_cli()
  File "/home/admin/.local/lib/python3.10/site-packages/swift/llm/infer/infer.py", line 165, in infer_cli
    response = self.infer_single(data, request_config)
  File "/home/admin/.local/lib/python3.10/site-packages/swift/llm/infer/infer.py", line 109, in infer_single
    res_or_gen = self.infer([infer_request],
  File "/home/admin/.local/lib/python3.10/site-packages/swift/llm/infer/infer_engine/pt_engine.py", line 553, in infer
    res += self._infer(
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/admin/.local/lib/python3.10/site-packages/swift/llm/infer/infer_engine/pt_engine.py", line 516, in _infer
    res = infer_func(**kwargs)
  File "/home/admin/.local/lib/python3.10/site-packages/swift/llm/infer/infer_engine/pt_engine.py", line 369, in _infer_full
    output = dict(template.generate(self.model, **generate_kwargs))
  File "/home/admin/.local/lib/python3.10/site-packages/swift/llm/template/base.py", line 661, in generate
    return model.generate(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/admin/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2617, in generate
    result = self._sample(
  File "/home/admin/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 3604, in _sample
    model_kwargs = self._update_model_kwargs_for_generation(
  File "/home/admin/.cache/modelscope/hub/_github/Valley/valley_eagle/model/language_model/valley_qwen2.py", line 68, in _update_model_kwargs_for_generation
    attention_mask = outputs.attention_mask
AttributeError: 'CausalLMOutputWithPast' object has no attribute 'attention_mask'. Did you mean: 'attentions'?

**Comment by oswardlx** [comment]
> 已支持

有用加速吗，我对比两个图片的区别，感觉跟transformers效率差不多
