### ISSUE TITLE
qwen2.5，lora微调，用SequenceClassification训练后，不能量化

### ISSUE THREAD

**Issue by vibe-viscot** [modelscope/ms-swift#2795]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
CUDA_VISIBLE_DEVICES=0 swift export \
    --adapters 'output/Qwen2.5-0.5B/v0-20241227-182143/checkpoint-2400' \
    --quant_bits 4 \
    --load_data_args true \
    --quant_method gptq
    
    
报错：
run sh: `/home/sang/llm/bin/python3 /home/sang/llm/lib/python3.12/site-packages/swift/cli/export.py --adapters output/Qwen2.5-0.5B/v0-20241227-182143/checkpoint-2400 --quant_bits 4 --load_data_args true --quant_method gptq`
[INFO:swift] Successfully registered `/home/sang/llm/lib/python3.12/site-packages/swift/llm/dataset/data/dataset_info.json`
[INFO:swift] Loading the model using model_dir: output/Qwen2.5-0.5B/v0-20241227-182143/checkpoint-2400
[INFO:swift] Successfully loaded /home/sang/work/wsdm/output/Qwen2.5-0.5B/v0-20241227-182143/checkpoint-2400/args.json.
[INFO:swift] Successfully registered `[]`
[INFO:swift] rank: -1, local_rank: -1, world_size: 1, local_world_size: 1
[INFO:swift.hub.hub] Downloading the model from ModelScope Hub, model_id: 
Downloading Model to directory: /home/sang/.cache/modelscope/hub/
[ERROR:modelscope] 400 Client Error: Bad Request, Request id: e337facb70be4b339c677229f611eb59 for url: https://www.modelscope.cn/api/v1/models//revisions
Traceback (most recent call last):
  File "/home/sang/llm/lib/python3.12/site-packages/swift/cli/export.py", line 5, in <module>
    export_main()
  File "/home/sang/llm/lib/python3.12/site-packages/swift/llm/export/export.py", line 41, in export_main
    return SwiftExport(args).main()
           ^^^^^^^^^^^^^^^^^
  File "/home/sang/llm/lib/python3.12/site-packages/swift/llm/base.py", line 18, in __init__
    self.args = self._parse_args(args)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/llm/lib/python3.12/site-packages/swift/llm/base.py", line 27, in _parse_args
    args, remaining_argv = parse_args(self.args_class, args)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/llm/lib/python3.12/site-packages/swift/utils/utils.py", line 146, in parse_args
    args, remaining_args = parser.parse_args_into_dataclasses(argv, return_remaining_strings=True)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/llm/lib/python3.12/site-packages/transformers/hf_argparser.py", line 352, in parse_args_into_dataclasses
    obj = dtype(**inputs)
          ^^^^^^^^^^^^^^^
  File "<string>", line 83, in __init__
  File "/home/sang/llm/lib/python3.12/site-packages/swift/llm/argument/export_args.py", line 86, in __post_init__
    BaseArguments.__post_init__(self)
  File "/home/sang/llm/lib/python3.12/site-packages/swift/llm/argument/base_args/base_args.py", line 138, in __post_init__
    ModelArguments.__post_init__(self)
  File "/home/sang/llm/lib/python3.12/site-packages/swift/llm/argument/base_args/model_args.py", line 140, in __post_init__
    self._init_torch_dtype()
  File "/home/sang/llm/lib/python3.12/site-packages/swift/llm/argument/export_args.py", line 95, in _init_torch_dtype
    super()._init_torch_dtype()
  File "/home/sang/llm/lib/python3.12/site-packages/swift/llm/argument/base_args/model_args.py", line 91, in _init_torch_dtype
    self.torch_dtype: torch.dtype = self._init_model_info()
                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/llm/lib/python3.12/site-packages/swift/llm/argument/base_args/model_args.py", line 118, in _init_model_info
    self.model_info, self.model_meta = get_model_info_meta(**self.get_model_kwargs())
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/llm/lib/python3.12/site-packages/swift/llm/model/register.py", line 417, in get_model_info_meta
    model_dir = safe_snapshot_download(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/llm/lib/python3.12/site-packages/swift/llm/model/utils.py", line 262, in safe_snapshot_download
    model_dir = hub.download_model(model_id_or_path, revision, ignore_patterns, token=hub_token, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/llm/lib/python3.12/site-packages/swift/hub/hub.py", line 315, in download_model
    return snapshot_download(model_id_or_path, revision, ignore_patterns=ignore_patterns, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/llm/lib/python3.12/site-packages/modelscope/hub/snapshot_download.py", line 90, in snapshot_download
    return _snapshot_download(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/sang/llm/lib/python3.12/site-packages/modelscope/hub/snapshot_download.py", line 238, in _snapshot_download
    revision_detail = _api.get_valid_revision_detail(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/llm/lib/python3.12/site-packages/modelscope/hub/api.py", line 558, in get_valid_revision_detail
    all_branches_detail, all_tags_detail = self.get_model_branches_and_tags_details(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/llm/lib/python3.12/site-packages/modelscope/hub/api.py", line 643, in get_model_branches_and_tags_details
    handle_http_response(r, logger, cookies, model_id)
  File "/home/sang/llm/lib/python3.12/site-packages/modelscope/hub/errors.py", line 122, in handle_http_response
    raise HTTPError(http_error_msg, response=response)
requests.exceptions.HTTPError: 400 Client Error: Bad Request, Request id: e337facb70be4b339c677229f611eb59 for url: https://www.modelscope.cn/api/v1/models//revisions

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
cuda12.4 ubuntu22.04 GPU:4070

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
先merge-lora再量化

**Comment by vibe-viscot** [comment]
ok解决了。我还想请教一下，SequenceClassification训练出的模型，推理除了--infer_backend pt，别的比如vllm啥的是不是用不了？

**Comment by Jintao-Huang** [comment]
分类模型不需要推理加速的

**Comment by Jintao-Huang** [comment]
直接用batch推理好了 --max_batch_size 16

**Comment by Jintao-Huang** [comment]
--full_determinism true

**Comment by vibe-viscot** [comment]
--full_determinism true没有用。不过我在register.py加了torch.manual_seed(TrainArguments.seed)后解决了。
https://github.com/modelscope/ms-swift/blob/1b132f644eccb1990a6fcb604271b82b9a068dae/swift/llm/model/register.py#L178-L183

改为：
    if tokenizer is None:
        tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
    from ..argument import TrainArguments
    torch.manual_seed(TrainArguments.seed)
    num_labels = model_kwargs.pop('num_labels', None)
    if num_labels:
        model_config.num_labels = num_labels
