### ISSUE TITLE
3.0 无HubApi的问题

### ISSUE THREAD

**Issue by moutozf04** [modelscope/ms-swift#2797]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/swift/cli/sft.py", line 2, in <module>
    from swift.llm import sft_main
  File "/usr/local/lib/python3.10/site-packages/swift/utils/import_utils.py", line 86, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/site-packages/swift/utils/import_utils.py", line 95, in _get_module
    return importlib.import_module('.' + module_name, self.__name__)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/site-packages/swift/llm/train/__init__.py", line 3, in <module>
    from .pt import SwiftPt, pt_main
  File "/usr/local/lib/python3.10/site-packages/swift/llm/train/pt.py", line 4, in <module>
    from ..argument import TrainArguments
  File "/usr/local/lib/python3.10/site-packages/swift/llm/argument/__init__.py", line 2, in <module>
    from .base_args import BaseArguments
  File "/usr/local/lib/python3.10/site-packages/swift/llm/argument/base_args/__init__.py", line 2, in <module>
    from .base_args import BaseArguments
  File "/usr/local/lib/python3.10/site-packages/swift/llm/argument/base_args/base_args.py", line 12, in <module>
    from swift.llm import Processor, Template, get_model_tokenizer, get_template, load_by_unsloth, safe_snapshot_download
  File "/usr/local/lib/python3.10/site-packages/swift/utils/import_utils.py", line 86, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/site-packages/swift/utils/import_utils.py", line 95, in _get_module
    return importlib.import_module('.' + module_name, self.__name__)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/site-packages/swift/llm/utils/__init__.py", line 3, in <module>
    from .argument import (AppUIArguments, DeployArguments, EvalArguments, ExportArguments, InferArguments, PtArguments,
  File "/usr/local/lib/python3.10/site-packages/swift/llm/utils/argument.py", line 23, in <module>
    from swift.hub import HubApi, ModelScopeConfig
ImportError: cannot import name 'HubApi' from 'swift.hub' (/usr/local/lib/python3.10/site-packages/swift/hub/__init__.py)

![image](https://github.com/user-attachments/assets/4755f342-bb76-4d06-ab63-298f44096ebc)

**Your hardware and system info**
ms-swift 3.0.1.post

**Additional context**
上周直接从GitHub拉的代码安装的，1230更新后会报另外一个training arguement的错，直接安装3.0会报这个错，请问更新的是不是有问题

**Comment by Jintao-Huang** [comment]
啊
你把当前目录中的build文件夹删除，再安装一下
