### ISSUE TITLE
使用最新仓库sft微调报错

### ISSUE THREAD

**Issue by jdsjnng** [modelscope/ms-swift#2799]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

[INFO:swift] Successfully registered `/xxx/ms-swift/swift/llm/dataset/data/dataset_info.json`
[INFO:swift] rank: -1, local_rank: -1, world_size: 1, local_world_size: 1
[INFO:swift] Loading the model using model_dir: /workspace/answerdotai/ModernBERT-large
[WARNING:swift] Please install the package: `pip install "transformers>=4.48" -U`.
Traceback (most recent call last):
  File "/xxx/ms-swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/xxx/ms-swift/swift/llm/train/sft.py", line 272, in sft_main
    return SwiftSft(args).main()
           ^^^^^^^^^^^^^^
  File "/xxx/ms-swift/swift/llm/train/sft.py", line 28, in __init__
    super().__init__(args)
  File "/xxx/ms-swift/swift/llm/base.py", line 18, in __init__
    self.args = self._parse_args(args)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/ms-swift/swift/llm/base.py", line 27, in _parse_args
    args, remaining_argv = parse_args(self.args_class, args)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/ms-swift/swift/utils/utils.py", line 146, in parse_args
    args, remaining_args = parser.parse_args_into_dataclasses(argv, return_remaining_strings=True)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/envs/loramoe/lib/python3.11/site-packages/transformers/hf_argparser.py", line 352, in parse_args_into_dataclasses
    obj = dtype(**inputs)
          ^^^^^^^^^^^^^^^
  File "<string>", line 281, in __init__
  File "/xxx/ms-swift/swift/llm/argument/train_args.py", line 136, in __post_init__
    Seq2SeqTrainingOverrideArguments.__post_init__(self)
  File "/xxx/ms-swift/swift/llm/argument/train_args.py", line 60, in __post_init__
    self.average_tokens_across_devices = self.world_size > 1
                                         ^^^^^^^^^^^^^^^
  File "/xxx/envs/loramoe/lib/python3.11/site-packages/transformers/training_args.py", line 2342, in world_size
    if self.distributed_state is not None:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TrainArguments' object has no attribute 'distributed_state'

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

ms-swift版本v3.0.1
transformer版本4.48.0.dev0

脚本：
CUDA_VISIBLE_DEVICES=0 \
swift sft \
    --model /workspace/answerdotai/ModernBERT-large \
    --train_type lora \
    --dataset 'DAMO_NLP/jd:cls#2000' \
    --torch_dtype bfloat16 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --learning_rate 1e-4 \
    --lora_rank 8 \
    --lora_alpha 32 \
    --target_modules all-linear \
    --gradient_accumulation_steps 16 \
    --eval_steps 50 \
    --save_steps 50 \
    --save_total_limit 2 \
    --logging_steps 5 \
    --max_length 2048 \
    --output_dir output \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 4 \
    --num_labels 2 \
    --task_type seq_cls \
    --use_chat_template false

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

主要目的是想微调modernbert做文本分类

**Comment by Jintao-Huang** [comment]
已经修复了
