### ISSUE TITLE
微调任务是，中断网页再次打开，找回运行时任务，运行状态无法可视化

### ISSUE THREAD

**Issue by xrzlizheng** [modelscope/ms-swift#588]
untimeError: Event loop is closed
Traceback (most recent call last):
  File "/home/zli/miniconda3/lib/python3.8/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/zli/miniconda3/lib/python3.8/site-packages/gradio/route_utils.py", line 253, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/zli/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1695, in process_api
    result = await self.call_function(
  File "/home/zli/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1235, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/zli/miniconda3/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/zli/miniconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/zli/miniconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/zli/miniconda3/lib/python3.8/site-packages/gradio/utils.py", line 692, in wrapper
    response = f(*args, **kwargs)
  File "/home/zli/swift/swift/ui/llm_train/model.py", line 97, in update_model_id_or_path
    model_state[model_type] = model_id_or_path
TypeError: unhashable type: 'list'
Traceback (most recent call last):
  File "/home/zli/miniconda3/lib/python3.8/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/zli/miniconda3/lib/python3.8/site-packages/gradio/route_utils.py", line 253, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/zli/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1695, in process_api
    result = await self.call_function(
  File "/home/zli/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1235, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/zli/miniconda3/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/zli/miniconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/zli/miniconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/zli/miniconda3/lib/python3.8/site-packages/gradio/utils.py", line 692, in wrapper
    response = f(*args, **kwargs)
  File "/home/zli/swift/swift/ui/llm_train/model.py", line 97, in update_model_id_or_path
    model_state[model_type] = model_id_or_path
TypeError: unhashable type: 'list'
![image](https://github.com/modelscope/swift/assets/33617203/c45aec21-8278-48d0-8056-3c66f98800ef)

**Comment by tastelikefeet** [comment]
理论上这个错误并不影响后续功能，考虑杀死界面后重新启动一下，sft任务不会受到影响
