### ISSUE TITLE
自定义推理文件无法使用两卡以上多卡推理

### ISSUE THREAD

**Issue by vivixx1** [modelscope/ms-swift#638]
Traceback (most recent call last):
  File "myinfer.py", line 75, in <module>
    response = inference(model, template, query)
  File "/swift/swift/llm/utils/utils.py", line 709, in inference
    generate_ids = model.generate(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 1592, in generate
    return self.sample(
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 2696, in sample
    outputs = self(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/qwen2/modeling_qwen2.py", line 1173, in forward
    outputs = self.model(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/qwen2/modeling_qwen2.py", line 1058, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/qwen2/modeling_qwen2.py", line 773, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/qwen2/modeling_qwen2.py", line 676, in forward
    query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin, position_ids)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/qwen2/modeling_qwen2.py", line 167, in apply_rotary_pos_emb
    q_embed = (q * cos) + (rotate_half(q) * sin)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/qwen2/modeling_qwen2.py", line 140, in rotate_half
    return torch.cat((-x2, x1), dim=-1)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [96,0,0], thread: [0,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [96,0,0], thread: [1,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.

上面是报错信息，下面是我自定义的推理代码

import json
import os
from transformers.debug_utils import DebugUnderflowOverflow
from modelscope import GenerationConfig

os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'

from swift.llm import (
    get_model_tokenizer, get_template, inference, ModelType, get_default_template_type
)
from swift.tuners import Swift

ckpt_dir = '/ai/outfile/qwen1half-72b-chat/v3-20240331-163441/checkpoint-50'
model_type = ModelType.qwen1half_72b_chat
template_type = get_default_template_type(model_type)
model_id_or_path = '/ai/qwenhalf72bchat/Qwen1.5-72B-Chat/'

model, tokenizer = get_model_tokenizer(model_type, model_id_or_path=model_id_or_path, model_kwargs={'device_map': 'auto'})

model = Swift.from_pretrained(model, ckpt_dir, inference_mode=True)

template = get_template(template_type, tokenizer)

model.generation_config = GenerationConfig(
            max_new_tokens=8192,
            temperature=0.9,
            repetition_penalt=1.05,
            do_sample=True
)

with open('/ai/123/测试集4.1knn.jsonl', 'r', encoding='utf-8') as f:
    data = [json.loads(item) for item in f]

output_data = []
flag = 0
for line in data:
    # query = prompt + '题目:' + line['query']
    query = line['query']
    response = inference(model, template, query)
    print(f'response: {response}')
    output_data.append(response)
    flag += 1
    if flag == 10:
        with open('/ai/outfile/qwen1half_72b_chat_test1.jsonl', 'a', encoding='utf-8') as f:
            for line in output_data:
                f.write(json.dumps({'response': line}, ensure_ascii=False) + '\n')
        output_data = []
        flag = 0

**Comment by vivixx1** [comment]
我的推理query比较长，大概有7000个token，只用两张卡进行推理的时候会OOM，结果用四张卡的时候出现了上面的bug，望作者帮忙看看是什么原因

**Comment by tastelikefeet** [comment]
看起来和卡数没关系，这个错误应该是推理长度过长导致的

**Comment by tastelikefeet** [comment]
可以换一个后缀是32k的模型试试看

**Comment by vivixx1** [comment]
这个我注意过，qwen1.572b-chat模型的上下文是32k的
![image](https://github.com/modelscope/swift/assets/143391981/fa14c0fb-f2e3-4045-a7e8-a4805c25113e)

**Comment by vivixx1** [comment]
还是没用，我把max_token调到10000了，最长的一条数据是7000左右的token，微调的时候没报错，就是推理的时候不行

比较奇怪的是我加入了os.environ["CUDA LAUNCH BLOCKING"]="1"之后，也没有更细节的报错信息

![image](https://github.com/modelscope/swift/assets/143391981/71883390-3d7b-4c51-a66c-3e9cb1ca5018)

**Comment by vivixx1** [comment]
经过测试确实不是token过长问题，降到800个token左右，用4卡也无法推理，2卡是没有问题的，也不会oom

**Comment by vivixx1** [comment]
甚至3000token，两卡的A800*80gb也会oom，四卡仍然会出现上面的问题

我查看别人的帖子，有人说是数据标签错误，但我这个数据不涉及标签，并且800token在四卡也会出问题，说明不是数据问题
有人说os.environ["CUDA LAUNCH BLOCKING"]="1"可以有更细节报错，我这里也没有
还有人说禁用gpu，通过cpu跑也可能出现更多报错，跑了4个小时，也没有出现更多报错

还有可能是什么原因呢，麻烦作者再帮我看看可能是什么问题

**Comment by vivixx1** [comment]
![image](https://github.com/modelscope/swift/assets/143391981/19feac42-d8c8-465e-ba7b-61b7094437df)
训练时候的generation config里面的max_new_token应该不影响后面的推理吧，推理的时候设置max_new_token就可以了吧

**Comment by vivixx1** [comment]
这个问题卡好几天了，还请作者们能帮我看看，确定一下可能的原因。。。

**Comment by vivixx1** [comment]
1

**Comment by tastelikefeet** [comment]
我用A100*4试了下没有发现有问题啊，能否发下prompt，如果是很短的prompt会不会出问题

**Comment by kksmi** [comment]
你好请问这个问题解决了吗，我是在微调过程出现这个错误
