### ISSUE TITLE
Infer internlm-xcomposer2 lead to `ValueError: Input length of input_ids is 0, but `max_length` is set to -1066.`

### ISSUE THREAD

**Issue by piqiuni** [modelscope/ms-swift#862]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

Running finetuned `internlm-xcomposer2-7b-chat` lead to error. 

```
token len:history:113, query:1706

Traceback (most recent call last):
  File "/home/ldl/pi_code/swift/pi_code/infer_internlm-xcomposer2.py", line 83, in <module>
    response, _ = inference(model, template, value, history)
  File "/home/ldl/pi_code/swift/swift/llm/utils/utils.py", line 692, in inference
    generate_ids = model.generate(
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/peft/peft_model.py", line 1190, in generate
    outputs = self.base_model.generate(*args, **kwargs)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/generation/utils.py", line 1449, in generate
    self._validate_generated_length(generation_config, input_ids_length, has_default_max_length)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/generation/utils.py", line 1140, in _validate_generated_length
    raise ValueError(
ValueError: Input length of input_ids is 0, but `max_length` is set to -1066. This can lead to unexpected behavior. You should consider increasing `max_length` or, better yet, setting `max_new_tokens`.

```

Also, running web-ui with the training data got wrong reply.
`CUDA_VISIBLE_DEVICES=0 swift app-ui --share True  --ckpt_dir ckp_output/internlm-xcomposer2-7b-chat/v10-20240502-202001/checkpoint-60/ --load_dataset_config true`

`I'm sorry,butIamunabletoanalyzetheimagesaslamatext-basedAlassistant and do not have the ability to view or interpret images.`

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by piqiuni** [comment]
with `CUDA_VISIBLE_DEVICES=0,1 swift infer --ckpt_dir ckp_output/internlm-xcomposer2-7b-chat/v10-20240502-202001/checkpoint-60/` it works, but the VMem usage goes from 18GB to 48+GB with only 4 questions(6pics+text) and lead to OOM? Is this a bug?

**Comment by piqiuni** [comment]
I tried again with python code and it lead to a new ERROR:
```
Traceback (most recent call last):
  File "/home/ldl/pi_code/swift/pi_code/infer_internlm-xcomposer2.py", line 82, in <module>
    print(f"token len:{get_length(model, template, str(history))}, {get_length(model, template, value)}")
  File "/home/ldl/pi_code/swift/swift/llm/utils/utils.py", line 722, in get_length
    inputs, tokenizer_kwargs = template.encode(example)
  File "/home/ldl/pi_code/swift/swift/llm/utils/template.py", line 938, in encode
    images = self.model.encode_img(images)
  File "/home/ldl/pi_code/swift/swift/llm/utils/model.py", line 2635, in _new_encode_img
    img_embeds, atts_img, img_target = self.img2emb(image)
  File "/home/ldl/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-7b/modeling_internlm_xcomposer2.py", line 122, in img2emb
    img_embeds = self.vision_proj(self.vit(image.to(self.device)))
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/ldl/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-7b/build_mlp.py", line 133, in forward
    image_forward_outs = self.vision_tower(
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/hooks.py", line 161, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/hooks.py", line 356, in pre_forward
    return send_to_device(args, self.execution_device), send_to_device(
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 180, in send_to_device
    return honor_type(
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 81, in honor_type
    return type(obj)(generator)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 181, in <genexpr>
    tensor, (send_to_device(t, device, non_blocking=non_blocking, skip_keys=skip_keys) for t in tensor)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 174, in send_to_device
    raise error
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 158, in send_to_device
    return tensor.to(device, non_blocking=non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

**Comment by piqiuni** [comment]
I tried to run with python code again and got a new error
```
Traceback (most recent call last):
  File "/home/ldl/pi_code/swift/pi_code/infer_internlm-xcomposer2.py", line 83, in <module>
    response, _ = inference(model, template, value, history)
  File "/home/ldl/pi_code/swift/swift/llm/utils/utils.py", line 628, in inference
    inputs, tokenizer_kwargs = template.encode(example)
  File "/home/ldl/pi_code/swift/swift/llm/utils/template.py", line 938, in encode
    images = self.model.encode_img(images)
  File "/home/ldl/pi_code/swift/swift/llm/utils/model.py", line 2635, in _new_encode_img
    img_embeds, atts_img, img_target = self.img2emb(image)
  File "/home/ldl/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-7b/modeling_internlm_xcomposer2.py", line 122, in img2emb
    img_embeds = self.vision_proj(self.vit(image.to(self.device)))
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/ldl/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-7b/build_mlp.py", line 133, in forward
    image_forward_outs = self.vision_tower(
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/hooks.py", line 161, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/hooks.py", line 356, in pre_forward
    return send_to_device(args, self.execution_device), send_to_device(
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 180, in send_to_device
    return honor_type(
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 81, in honor_type
    return type(obj)(generator)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 181, in <genexpr>
    tensor, (send_to_device(t, device, non_blocking=non_blocking, skip_keys=skip_keys) for t in tensor)
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 174, in send_to_device
    raise error
  File "/home/ldl/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 158, in send_to_device
    return tensor.to(device, non_blocking=non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

**Comment by piqiuni** [comment]
Change `model.generation_config.max_new_tokens` solved the problem. 
But I'm still confused about the difference of these params, can you help to explain it?
```
form https://modelscope.cn/models/Shanghai_AI_Laboratory/internlm-xcomposer2-7b/files
model.config.max_length
model.generation_config.max_length
model.generation_config.max_length
model.generation_config.max_new_tokens
```

**Comment by Jintao-Huang** [comment]
Refer to this link: https://huggingface.co/docs/transformers/main_classes/text_generation
